### ISSUE TITLE
I have a problem with my Meross mss 710 

### ISSUE THREAD

**Issue by ComeDow** [donavanbecker/homebridge-meross#110]
I can only switch the light on and not off :/. I have an mss 710 smart switch to turn on and off my light with the Meross app. I have it already in the home bridge and also HomeKit but I can switch the light on but not off. 

The Homeride shows:

!-- [11/20/2020, 2:41:26 AM] [Licht Küche Ein] Failed to POST to the Meross Device MSS710 at "IP ADRESS": Error: connect ECONNREFUSED "IP ADRESS". -->

**Comment by donavanbecker** [comment]
please fill out issue template. need more info about devices, need more logs, and if you can put on homebridge debug logs that would also help.
