### ISSUE TITLE
Add support for MSS570x dimmer switch

### ISSUE THREAD

**Issue by zpeters90** [donavanbecker/homebridge-meross#120]
Would it be possible to add support for Meross MSS570x 3 way smart dimmer switch? The current version works for my light switch but does not support the dimming function. Really appreciate your work on this and happy to contribute how I can!

**Comment by zpeters90** [comment]
Also, it looks like this was done for a mss560 switch already, is it possible for me to just classify the switch as a 560 to get the brightness controls?

**Comment by donavanbecker** [comment]
See #151

**Comment by tphalp** [comment]
> Also, it looks like this was done for a mss560 switch already, is it possible for me to just classify the switch as a 560 to get the brightness controls?

FYI, I set my 570 as a 560, and the dimmer functionality works in the Home app.

**Comment by zpeters90** [comment]
> > Also, it looks like this was done for a mss560 switch already, is it possible for me to just classify the switch as a 560 to get the brightness controls?
> 
> FYI, I set my 570 as a 560, and the dimmer functionality works in the Home app.

How did you set it as a 560?

**Comment by tphalp** [comment]
> > > Also, it looks like this was done for a mss560 switch already, is it possible for me to just classify the switch as a 560 to get the brightness controls?
> 
> > 
> 
> > FYI, I set my 570 as a 560, and the dimmer functionality works in the Home app.
> 
> 
> 
> How did you set it as a 560?

I just chose the 560 in the homebridge Meross plug-in config, instead of the 570.

**Comment by donavanbecker** [comment]
@zpeters90 I have added the mss570x as an option in the latest beta, if you could try it and let me know how it works. it will show up as a light bulb.

Beta: `4.0.1-beta.12`
