### ISSUE TITLE
HomeKit showing as "Update Available"

### ISSUE THREAD

**Issue by matclothier** [donavanbecker/homebridge-meross#121]
I have added a MSS210 plug and it works perfectly, but the Apple Home app shows as an update is available and a link to the Meross app.  All of the devices are up to date, can this be overridden?

**Comment by donavanbecker** [comment]
can you show the firmware version of the mss210 plug in the meross app?

**Comment by matclothier** [comment]
2.1.7

[Image.jpeg]
Thanks,

Mat
+44 (0)7990 591055

________________________________

**Comment by matclothier** [comment]
![EF948D5E-7339-41B4-88CF-1E0CA259F506](https://user-images.githubusercontent.com/55290749/100654454-b9eadd80-3341-11eb-91b1-8cd77f296a82.png)

**Comment by donavanbecker** [comment]
there must be something else that is catching this, since the plugin version is v3.x.x

**Comment by matclothier** [comment]
In Apple Home is shows as 3.4 which is the plug-in version. 

![9A84D524-4AC5-44D3-BD33-6D91511AB748](https://user-images.githubusercontent.com/55290749/100665037-0e955500-3350-11eb-980d-679ae1bee247.png)
![DF52D30E-DE2D-4ECC-9588-4579AE511A90](https://user-images.githubusercontent.com/55290749/100665093-10f7af00-3350-11eb-88b2-c87a101c74f8.png)

**Comment by matclothier** [comment]
It shows ad up to date in the Meross app. 

![D0F070E0-99F9-4A42-8D3A-A7431FBC45BB](https://user-images.githubusercontent.com/55290749/100666015-413f4d80-3350-11eb-9bae-0be7bd8428bd.png)

**Comment by matclothier** [comment]
Hi, any ideas how to fix this?

**Comment by bywalec1** [comment]
I have the same problem. My plugin symbol, plugin firmware in Meross and Homekit are also the same.

**Comment by donavanbecker** [comment]
@bywalec1 and @matclothier,

Can you test the latest beta and then input a firmware version higher then the one for your outlet and let me know if it goes away.

**Comment by matclothier** [comment]
The plugs don’t work in Homebridge or home at all with the new beta. I tried with the working confit from before and with adding the new options.

**Comment by donavanbecker** [comment]
@matclothier Do you have errors you can provide?

**Comment by matclothier** [comment]
Error -113 for all 3 devices. 
![AF816B6D-E7D8-4C6D-B254-7042520067C6](https://user-images.githubusercontent.com/55290749/101842606-53836d80-3b40-11eb-9840-d83678c3321e.jpeg)

**Comment by donavanbecker** [comment]
@matclothier I would check again? because I am not getting this.

**Comment by matclothier** [comment]
OK, it looks like it is working now and the update notice has gone away.  Thanks for sorting this.

**Comment by donavanbecker** [comment]
@matclothier You can actually set the firmware in the plugin settings on Homebridge UI.

**Comment by bywalec1** [comment]
Everything works fine now. Thank you very much.

**Comment by johnmullaney** [comment]
The beta resolved issue for me too - Thanks
