### ISSUE TITLE
MSL320CHK support

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [donavanbecker/homebridge-meross#124]
**Is your feature request related to a problem? Please describe.**
The MSL320CHK is perfectly working as an Outlet, I can switch it on and off. So, no problem so far. 

**Describe the solution you'd like**
I'd like to see this plugin to control the MSL320CHK as a lightbulb or LED stripe, i.e. color, brightness, etc. should be controllable. 

**Describe alternatives you've considered**
No idea, sorry. 

**Additional context**
I was perfectly able to get the Credential defaults with the App HTTP Catcher. However, I did not need to install Charles or any other proxy, I got all the credential info from the response headers inside HTTP Catcher.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
Just an Idea - the project [MerossIot](https://github.com/albertogeniola/MerossIot) has a very nice sniffer which catches the MQTT commands being sent around and which gathers every action sent out from the App to the Device. Wouldn't that be an idea to get the controllable properties of a Device?

**Comment by donavanbecker** [comment]
@MichaelMichaelMichaelMichaelMichael If you implement it, we would definitely accept the PR. Was thinking of doing it but it would take a lot of my time right now.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
Currently, I'm also a bit short of time and that's why I'd rather contribute by testing and filing in observations. What I did though: I've duplicated those (same) two lines 
` case 'MSL-100':`
and I've added
` case 'MSL320CHK':`
in that context (twice, as mentioned: [here](https://github.com/donavanbecker/homebridge-meross/blob/master/src/index.ts#L213) and [here](https://github.com/donavanbecker/homebridge-meross/blob/master/src/index.ts#L280)) and I could make the following observations as regards the Apple Home App:
* Homekit sees the MSL320CHK properly as a lamp
* I can feed the MSL320CHK with RGB values
* I cannot adjust the Brightness, it's always at 100%
* When adjusting Brightness (or trying to), there seems to be flooding of commands to the Device and the Device seems to Block commands for a while. After a while of no commands, the gate is open again. 
* When being blocked, the control via Meross App is still possible

Hope it helps.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
Testing around I was able to set some colors, but I must say, the plugin is no other use for me other than switching on and off the LED stripe or setting a color out of an automation. It has nothing to with your plugin, it's obviously the flooding protection from the Device side. When changing colors, I use a [Müller Licht MLI-404011 via Zigbee2MQTT](https://www.zigbee2mqtt.io/devices/MLI-404011.html) and I translate the resulting MQTT-Messages in commands to update the Device (done via [NodeRed](https://nodered.org/)). 
This remote doesn't necessarily have to fire events very quickly, just approaching the colors a bit by pressing the color wheel several times makes the Device block and makes NodeRed report:
`"0E:11:CE:D1:..:.. -> Error: ESOCKETTIMEDOUT -> undefined"`
So sorry, but that mechanism only is good to execute not too many actions at once. But not too quickly. 

I'll open another issue for this flooding problem.

**Comment by donavanbecker** [comment]
See #151
