### ISSUE TITLE
Force device type?

### ISSUE THREAD

**Issue by remino** [donavanbecker/homebridge-meross#143]
**Describe Your Problem:**

I updated Node, Homebridge, and the Meross and UI plug-ins this week. Since then, I have some MSS110 devices set up to display as power outlets in the Meross app on iOS and yet they show up as lights in the Home app and Homebridge UI.

Is there a way to change the type of a device to a power outlet instead of a light?

**Environment:**

* **Node.js Version**:  14.15.3
* **NPM Version**:  6.14.9
* **Homebridge Version**:  1.1.7
* **Homebridge Meross Plugin Version**: 3.4.1
* **Homebridge Config UI X Plugin Version**: 4.36.0
* **Operating System**:  Raspbian

**Comment by remino** [comment]
I just reverted the Meross plugin to 3.1.0 and that seems to fix the issue. Maybe it's a bug?

**Comment by donavanbecker** [comment]
See #151

**Comment by remino** [comment]
#151 isn’t addressing the issue described here, or at least not directly. It’s about what I read is going to become a new plugin for Meross cloud support.

I’m just not going to update the plugin, as the old one is working got me, and wait.

**Comment by MrJer** [comment]
Proposed #170 to fix this problem

**Comment by donavanbecker** [comment]
@MrJer I have pushed through your PR! Thanks! It is in the beta branch which will push a new beta if that want's to be tested out?

**Comment by MrJer** [comment]
@donavanbecker happy to help! Just pulled down v3.4.2-beta.4 and MSS110-2 is showing correctly as outlet now.
