### ISSUE TITLE
MSS310 issue --> continuing "Set failed: false"

### ISSUE THREAD

**Issue by nunoftheabove** [donavanbecker/homebridge-meross#158]
retrieved all relevant data using http catcher. Plug is visible but cannot be switched on/off via homebridge. Error: Set failed: false

**To Reproduce:**
- run http cacher and start collecting data
- open Meross app
- switch on MSS310 plug in meross app
- stop collecting data in http catcher
- retrieve messageID, timestamp and sign from JSON response
- input data in meross-homebridge plugin via form
- save
- restart homebridge
- Meross Plug visibile in homebridge but switching on/off only prompts Error: Set failed: false

**Expected behavior:**

switch MSS310 plug on/off via homebridge

**Logs:**

```
Show the Homebridge logs here. If using Homebridge Config-UI-X, you can easly downlaod your log by visiting the log page on the UI and Clicking the Download Icon in the top right.
Remove any sensitive information, such as yourhomebridge-meross timestamp / sign / messageId / deviceUrl.

Please Turn on Debug Mode before submitting your Issue so more logs can be shared to fix the issue being submitted.
```

**Homebridge Config:**

```json
Paste your homebridge config.json here.
Remove any sensitive information, such as your homebridge-meross timestamp / sign / messageId / deviceUrl.

    "accessories": [
        {
            "accessory": "Meross",
            "channel": 0,
            "deviceUrl": "192.168.178.47",
            "model": "MSS310",
            "name": "Tiffy",
            "serialNumber": "*******************",
            "messageId": "*******************",
            "timestamp": *******************,
            "sign": "*******************",
            "hardwareVersion": "1.0.0",
            "firmwareRevision": "1.1.18"
        }
    ],

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

# **Environment:**

- **Node.js Version**: v14.15.1
- **NPM Version**: 6.14.8
- **Homebridge Version**:  HOOBS 3 Version | 3.3.1
- **Homebridge Meross Plugin Version**: 3.4.1
- **Homebridge Config UI X Plugin Version**:
- **Operating System**: Raspbian Release 10, Kernel 5.4.72-v7l+

**Comment by donavanbecker** [comment]
> * **Homebridge Version**:  HOOBS 3 Version | 3.3.1

this plugin is created for Homebridge not HOOBS. I don't have HOOBS and don't support it. I would recommend migrating to homebridge and then if you are still having issues I would be able to help you out.

[How-To-Migrate-From-HOOBS-To-Homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge)

**Comment by nunoftheabove** [comment]
Same issue with Homebridge 

I installed fresh from homebridge.io
Kernel version: 5.4
Node.js Version: v14.15.1
Homebridge Version: v1.1.6
Homebridge Config UI X Version: v4.36.0

{
    "bridge": {
        "name": "Homebridge 73F4",
        "username": "0E:**:BA:**:73:**",
        "port": 51895,
        "pin": "***-**-***"
    },
    "accessories": [
        {
            "model": "MSS310",
            "name": "Tiffy",
            "deviceUrl": "192.168.178.47",
            "channel": 0,
            "messageId": "******",
            "timestamp": ******,
            "sign": "******",
            "accessory": "Meross"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}

**Comment by DenR2** [comment]
Hi @donavanbeckern, i have the same issue 

**Environment:**
Node.js Version: v12.19.0
NPM Version: 6.14.8
Homebridge Version: 1.2.5
Homebridge Meross Plugin Version: 3.4.1
Operating System: Alpine Linux (3.12.0)
Homebridge config-ui-x v4.36.0

Homebridge is running with Docker using Container station on a Qnap TS251+

**Comment by nunoftheabove** [comment]
@donavanbecker HI, any ideas?
