### ISSUE TITLE
Aroma diffuser MOD100

### ISSUE THREAD

**Issue by Mikesmolto** [donavanbecker/homebridge-meross#181]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hi, I Wonder if you plan adding the diffuser model MOD100 to your plugin?

**Describe alternatives you've considered**

**Additional context**
Thanks a lot

**Comment by iMatux** [comment]
I tried too, but the support is missing
However timestamp, sign and messageID are there

**Comment by iMatux** [comment]
[This](https://github.com/albertogeniola/MerossIot/issues/170) maybe could help, there are some sniffing data and various commands from the Meross MOD100

**Comment by enigmat14** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> **Describe the solution you'd like**
> 
> Hi, I Wonder if you plan adding the diffuser model MOD100 to your plugin?
> **Describe alternatives you've considered**
> 
> **Additional context**
> Thanks a lot

Sorry I did not read the message.
It is not related to a problem, it is an integration request. The solution would be to integrate it into the library, my knowledge in Python development is null, sorry. I could perform the tests you need. 

Again sorry for not replying.

**Comment by bwp91** [comment]
@Mikesmolto 
Experimental support for the MOD100 is now available in the beta version of the plugin

**Comment by Mikesmolto** [comment]
Good one, i will use it after my vacation and tell about my experience 😎

**Comment by Mikesmolto** [comment]
Hi, thanks for adding the MOD100. Unfortunately I'm a not good in these things, I'm just a Homebridge user and have basic knowledge. Anyway I will give my experience with Meross Plug-in and my oil diffuser:
I'm using the EVE App, there it shows 2 criteria, 1.) Oil diffuser and 2.) Diffuser light
1.) offers Power-ON/OFF and Speed-0/50/100. The power button works only to power OFF. The Speed Control works on 0 (off) and 50/100 (on)
2.) Power, Color and Brightness works OK. Color Mode, Rainbow Mode and Temperature Mode doesn't show any function.
Anyway, good work and useful. Thanx a lot - Mike

**Comment by bwp91** [comment]
@Mikesmolto thanks for this. Could you update to beta version 6.7.3-beta.0 and let me know if any of the issues you noted have been fixed?

**Comment by Mikesmolto** [comment]
@bwp91 sorry mate, how I told you, I just have basic knowledge and homebridge Ui doesn't offer this update. Latest update is v6.7.2

**Comment by bwp91** [comment]
> @bwp91 sorry mate, how I told you, I just have basic knowledge and homebridge Ui doesn't offer this update. Latest update is v6.7.2

Here’s a link to a wiki page re installing the beta version:

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version#homebridge-ui

**Comment by Mikesmolto** [comment]
Thanks a lot. Installed. The light features work all right, except 3 switches for color mode, rainbow mode and temperature mode, but I also don't know what these are supposed to do. Oil diffuser works all right, the only thing is the switch on/off has no function when the velocity is on zero. So if you use the velocity regulator and put it on 50 or 100% the switch turn to ON. Function is sufficient in the EVE App, 
Good work, thank you
Mike

**Comment by bwp91** [comment]
Rainbow mode and temperature mode are modes that can be turned on for the light via the meross app? The colour mode is simply there to put the light back into normal rgb mode.

**Comment by bwp91** [comment]
They *should* work, but i don’t think they have been really tested. If you try to turn rainbow mode or temperature mode on, do any errors appear in the homebridge log?

**Comment by Mikesmolto** [comment]
I couldn't find these modes in the Meross App an if you turn them on or off, there is no function recognizable

**Comment by Mikesmolto** [comment]
[20/08/2021, 11:22:00] [Meross] [Oil Diffuser] current light brightness [100%].
[20/08/2021, 11:22:00] [Meross] [Oil Diffuser] current light mode [colour].
[20/08/2021, 11:22:00] [Meross] [Oil Diffuser] failed to refresh status as this.colourUtils.mr2hk is not a function or its return value is not iterable at deviceDIffuser.applyUpdate (/usr/local/lib/node_modules/homebridge-meross/lib/device/diffuser.js:751:46).
[20/08/2021,
That's the only error shown in the log file

**Comment by Mikesmolto** [comment]
I have to correct myself, rainbow mode is working, changing color 🌈

**Comment by bwp91** [comment]
> [20/08/2021, 11:22:00] [Meross] [Oil Diffuser] current light brightness [100%].
> [20/08/2021, 11:22:00] [Meross] [Oil Diffuser] current light mode [colour].
> [20/08/2021, 11:22:00] [Meross] [Oil Diffuser] failed to refresh status as this.colourUtils.mr2hk is not a function or its return value is not iterable at deviceDIffuser.applyUpdate (/usr/local/lib/node_modules/homebridge-meross/lib/device/diffuser.js:751:46).
> [20/08/2021,
> That's the only error shown in the log file

Thanks for this. This should be fixed in a new beta version, 6.7.3-beta.5.

And glad you found the rainbow mode! I don't think the temperature mode is very useful, I think it's just one colour that it changes the light to.
