### ISSUE TITLE
Accessory simulations

### ISSUE THREAD

**Issue by Lui5Jacint0** [donavanbecker/homebridge-meross#215]
**Is your feature request related to a problem? Please describe.**

It’s not a problem, is more a visual asset in HomeKit.

**Describe the solution you'd like**

I would like to see implementation of the accessory simulations like the eWeLink plugging to transform switches and lights into other HomeKit accessories (door locks, water valves etc).

**Describe alternatives you've considered**

**Additional context**

I have a meross plug 🔌 connected to a water valve for watering my garden, and i would like it to 
show in HomeKit like a sprinkler similar to eve aqua.

**Comment by Lui5Jacint0** [comment]
@donavanbecker could you add this feature?

**Comment by donavanbecker** [comment]
I will take pull requests. But I do this in my free time so don't have time to add all the different options
