### ISSUE TITLE
Several log entries

### ISSUE THREAD

**Issue by Perilax-De** [donavanbecker/homebridge-meross#217]
**Describe Your Problem:**
I get from time to time (in a period from 10-40 minutes) the same log entry. 

**Logs:**

[28.2.2021, 08:44:28] [homebridge-meross] This plugin generated a warning from the characteristic 'Obstruction Detected': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.

**Homebridge Config:**

{
"model": "MSG100",
"name": "Garagentor",
"deviceUrl": "192.168.178.30",
"channel": 0,
"messageId": "xxxxx",
"timestamp": xxxxxx,
"sign": "xxxxxx",
"accessory": "Meross"
}

**Environment:**

* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.1
* **Homebridge Meross Plugin Version**: 3.5.0
* **Homebridge Config UI X Plugin Version**: 4.39.1
* **Operating System**: Raspbian

**Comment by zonak** [comment]
Seeing the same thing in the same setup (fresh install).

**Comment by donavanbecker** [comment]
Check out #228

**Comment by donavanbecker** [comment]
dup of #204
