### ISSUE TITLE
Beta v5.0.0

### ISSUE THREAD

**Issue by donavanbecker** [donavanbecker/homebridge-meross#228]
### Breaking Changes

- The Plugin has been been changed from an `accessory` type to a `platform` type.
- You will have to change you config completely if you update to this version.
  - You can take your current `accessory` and move it to the platform config.
  - Example: 
   #### Before:
    ```json
    "accessories": [
        {
          "model": "MSS620",
          "name": "Outlet",
          "deviceUrl": "192.168.1.1",
          "channel": 0,
          "messageId": "abcdefghijklmnopqrstuvwxyz123456789",
          "timestamp": 123456789,
          "sign": "abcdefghijklmnopqrstuvwxyz123456789",
          "accessory": "Meross"
        }
    ]
    ```
   #### After:
    ```json
    "platforms": [
        {
        "name": "Meross",
        "devices": [
            <This_is_from_above>
            {
            "model": "MSS620",
            "name": "Outlet",
            "deviceUrl": "192.168.1.1",
            "channel": 0,
            "messageId": "abcdefghijklmnopqrstuvwxyz123456789",
            "timestamp": 123456789,
            "sign": "abcdefghijklmnopqrstuvwxyz123456789",
            "accessory": "Meross"  <You_Can_Remove_This.>
            }
            <Ends_here_from_above>
          ],
        "platform": "Meross"
        }
    ]
    ```

## Testers
Need Beta testers to try this and let me know if you have any issues and post here which model you are using and just say you have an issue, then open your own separate issue to try that model and Beta v5.0.0.

Let me know if you have any questions on updating to this beta. Easiest way is to use Homebridge UI.

### [Install Instructions](https://github.com/donavanbecker/homebridge-meross/wiki/Beta)

Beta: `4.0.2-beta.1` on `npm`

## Tested Models:
* [ ] MSS110-1
* [x] MSS110-2
* [ ] MSL-100
* [ ] MSL-120
* [ ] MSL-320
* [x] MSL-420
* [x] MSS210
* [x] MSS310
* [ ] MSS420F
* [ ] MSS425
* [x] MSS425E
* [x] MSS425F
* [ ] MSS510
* [ ] MSS510M
* [ ] MSS530H
* [ ] MSS550
* [ ] MSS560
* [ ] MSS570
* [ ] MSS570x
* [ ] MSS5X0
* [x] MSS620
* [x] MSS630
* [ ] MSS710
* [ ] MSG100
* [ ] MSG200

**Comment by MrJer** [comment]
Tested this with my MSS110-2s and they were working fine 👍

**Comment by donavanbecker** [comment]
@MrJer I have pushed another update out. Can you test it out and make sure it is still working?

Beta:`v4.0.1-beta.4`

**Comment by MrJer** [comment]
Pulled down `v4.0.1-beta.8` tonight and MSS110-2 is still performing as expected.

**Comment by bosco90** [comment]
Hi there!
Just installed v4.0.1-beta.9 and updated the config as indicated for my MSS425E and it works fine. All plugs and the usb are recognized properly, in the HB Log the plugin doesn't show any warning!

Good job so far!!

**Comment by Frankdoc** [comment]
Not working for MSG100.
Continously says:
"[3/5/2021, 11:35:03 AM] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info."

In homekit it shows as 'open' even though the garage door is closed. Pressing the button doesn't do anything either

**Comment by Write** [comment]
MSS-210 and MSS-310 work perfectly for me.

**Comment by donavanbecker** [comment]
@Write Thanks!

@Frankdoc thanks for testing. Can you open an issue for this? So I can track it by itself?

**Comment by juanfal** [comment]
Instalad last beta is possible through the web UI, but beta 5 is not listed.  How do you recommend to install it?  Should we previously uninstall 4 and then install with npm or so?  What is the exact command?  When to change the Configuration, before or after?  Home app will get meshed, won't it?

**Comment by donavanbecker** [comment]
@juanfal Beta.11 is the latest

**Comment by juanfal** [comment]
Beta 11 deletes everything from Meross on Home app. You need to rebuild everything after the catastrophe

**Comment by donavanbecker** [comment]
@juanfal weird because I haven't had this issue at all

**Comment by juanfal** [comment]
It’s happened 2 times to me. Fool of me. If I install las beta 11 all Meross devices disappear from Home app. A total disaster 


--
Juan miPhone

**Comment by rcoletti116** [comment]
Tested. MSS630 working perfectly.

**Comment by JackMorens** [comment]
Beta11 work with MSS425F and HB 1.3.2. The only problem I have, is that the on or off status is not updated with the Meross app.

**Comment by donavanbecker** [comment]
@JackMorens are you talking about if you control the device from the meross app? it won't be instant. that status is refreshed based off the refreshRate which you can override with advance settings of the plugin.

**Comment by JackMorens** [comment]
> @JackMorens are you talking about if you control the device from the meross app? it won't be instant. that status is refreshed based off the refreshRate which you can override with advance settings of the plugin.

Yes, if I turn on / off through the application or through the voice assistants, with the old version 3.50 the synchronization is fine, but with the 4.0.0 or this beta11 the status is not updated, even if I wait for the 300 seconds set by  default, the status is not updated.

**Comment by donavanbecker** [comment]
@JackMorens Do you have any error logs? Don't have much to go off of.

**Comment by JackMorens** [comment]
> @JackMorens Do you have any error logs? Don't have much to go off.

No, in the log I only see the on or off message, when I turn it on or off from the Home application. 
In this case the Switch 4 was already in the On state, to turn it Off I had to press 2 times, once to make it see On and once to actually turn it Off 

[3/8/2021, 9:57:29 PM] [Meross] Sending request On for Presa 4
[3/8/2021, 9:57:37 PM] [Meross] Sending request Off for Presa 4

**Comment by donavanbecker** [comment]
@JackMorens can you enable debug mode so we can see if there is any other info we are missing? also can you open this up in another issue to track it that way?

**Comment by JackMorens** [comment]
> @JackMorens can you enable debug mode so we can see if there is any other info we are missing? also can you open this up in another issue to track it that way?

Ok, I enable the debug mode and open new bug issue.

**Comment by osigge** [comment]
> Not working for MSG100.
> Continously says:
> "[3/5/2021, 11:35:03 AM] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected number and received undefined. See https://git.io/JtMGR for more info."
> 
> In homekit it shows as 'open' even though the garage door is closed. Pressing the button doesn't do anything either

I can confirm that MSG100 does not work. I get a different error:
[Meross] Failed to POST to the Meross Device MSG100 at <local IP address>: "socket hang up"

**Comment by donavanbecker** [comment]
Unfortunately I don't have a meross garage door so can't test this myself and can't see what needs to be sent to it. Unless someone can post what they sniff out with http catcher or Charlie's proxy. I might be able too.

**Comment by osigge** [comment]
> Unfortunately I don't have a meross garage door so can't test this myself and can't see what needs to be sent to it. Unless someone can post what they sniff out with http catcher or Charlie's proxy. I might be able too.

I'm currently working on a quick fix for myself. The latest "release" version doesn't also work for me. I need my garage door ;)
After that I will see what I can do to integrate a "real" fix.

**Comment by donavanbecker** [comment]
@osigge i have released a new Beta: `v4.0.1-beta.13`

Can you test it out?

**Comment by osigge** [comment]
> @osigge i have released a new Beta: `v4.0.1-beta.13`
> 
> Can you test it out?

Sorry, still the same issue :(

**Comment by donavanbecker** [comment]
@osigge okay try beta: `v4.0.1-beta.14` once it is published.

**Comment by osigge** [comment]
> @osigge okay try beta: `v4.0.1-beta.14` once it is published.

unfortunately I still get the same error

**Comment by donavanbecker** [comment]
@osigge does the latest beta work for you?

**Comment by osigge** [comment]
> @osigge does the latest beta work for you?
> 
> And what model of garage door do you have?

Version 4.0.2-beta.2 does work for me, yes. I have the MSG100.

**Comment by czm97176** [comment]
i am wondering will the plugin got updated if the devices turned on by another automation software? like Note-red?
i tried to switch-on/off my MS310 but the Home app is not update. I guess the plugin will not checking the status actively ?

**Comment by donavanbecker** [comment]
> i am wondering will the plugin got updated if the devices turned on by another automation software? like Note-red?
> 
> i tried to switch-on/off my MS310 but the Home app is not update. I guess the plugin will not checking the status actively ?

@czm97176 do you have the refreshrate set? If not, it will take 5 mins to update.
