### ISSUE TITLE
Hoobs crashed after update with this package

### ISSUE THREAD

**Issue by ash123-germany** [donavanbecker/homebridge-meross#229]
**Hoobs crashed after update with this package**

4.3.2021, 19:50:25 npm
4.3.2021, 19:50:25  WARN notsup Unsupported engine for homebridge-meross@4.0.0: wanted: {"node":">=14.15.4","homebridge":">=1.3.1"} (current: {"node":"14.15.1","npm":"6.14.8"})
npm WARN
4.3.2021, 19:50:25 
4.3.2021, 19:50:25 notsup
4.3.2021, 19:50:25  Not compatible with your version of node/npm: homebridge-meross@4.0.0
4.3.2021, 19:50:25 
4.3.2021, 19:50:25 + homebridge-meross@4.0.0
updated 1 package in 3.843s
4.3.2021, 19:50:25 
10 packages are looking for funding
  run `npm fund` for details
4.3.2021, 19:50:25 Plugin "homebridge-meross" updated.
4.3.2021, 19:50:25 Got SIGINT, shutting down Bridge...

I have HOOBS Version 3.3.3

**Comment by donavanbecker** [comment]
@ash123-germany, You need to have homebridge v1.3.1 installed as the changelogs says.

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).
