### ISSUE TITLE
Support for MSS420F

### ISSUE THREAD

**Issue by MatGriffin** [donavanbecker/homebridge-meross#24]
Does this support the mss420f power strip?
I tried but could not get it to work.

**Comment by donavanbecker** [comment]
@MatGriffin, I don't have that product. have you tested it with the power strip?

**Comment by MatGriffin** [comment]
Yes, I could not get it to work. I used Charles proxy and Thor app to try and grab the various bits but it just would not work. What I did not notice is that all calls are via https://iot.meross.com not local ip, no internet connection not control of the sockets.

**Comment by dylanfrankcom** [comment]
Hey @MatGriffin, we are looking to add support for as many devices as possible. That’s interesting about the calls. Typically you would see calls from an IP on your local network as well as iot.meross.com. 

Could you join the [Homebridge Discord](https://discord.gg/Z8jmyvb) and get in contact with me or @donavanbecker. It would be much easier to get information in real time.

**Comment by donavanbecker** [comment]
> Yes, I could not get it to work. I used Charles proxy and Thor app to try and grab the various bits but it just would not work. What I did not notice is that all calls are via https://iot.meross.com not local IP, no internet connection no control of the sockets.

can you post your config and any errors you are getting?

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try.

**Comment by donavanbecker** [comment]
See [Specific Model Configurations Wiki](https://github.com/donavanbecker/homebridge-meross/wiki/Specific-Model-Configurations) for more details on MSS420s...
