### ISSUE TITLE
MSG 200 not working please help

### ISSUE THREAD

**Issue by yonigold1** [donavanbecker/homebridge-meross#245]
**Describe The Bug:**
MSG 200 not working on the latest version of the plugin

After upgrading this plugin to version 4.0.0+ my MSG 200 garage door opener will not work from homebridge

**To Reproduce:**
Not sure as I don't know whats wrong

**Expected behavior:**
The garage to open and states to be correct

**Logs:**

```

```

<img width="1412" alt="Screen Shot 2021-03-12 at 7 45 36 PM" src="https://user-images.githubusercontent.com/34217684/111012872-87eb0d80-836b-11eb-95d1-8689ceac0bf3.png">

**Homebridge Config:**

```
    "accessories": [
        {
            "name": "Hot Plate",
            "deviceUrl": "192.168.2.**",
            "channel": 0,
            "messageId": "-----------------------",
            "timestamp": -----------------------,
            "sign": "-----------------------",
            "accessory": "Meross"
        },
        {
            "channel": 0,
            "deviceUrl": "192.168.2.**",
            "sign": "-----------------------",
            "name": "Crock Pot",
            "accessory": "Meross",
            "messageId": "-----------------------",
            "timestamp": -----------------------
        },
        {
            "model": "MSG200",
            "name": "Garage Door",
            "firmwareRevision": "4.1.3",
            "deviceUrl": "192.168.2.**",
            "channel": 1,
            "messageId": "-----------------------",
            "timestamp": -----------------------,
            "sign": "-----------------------",
            "garageDoorOpeningTime": 15,
            "accessory": "Meross"
        }


```

```json


```

**Screenshots:**

# **Environment:**

- **Node.js Version**: <Latest>
- **NPM Version**: <Latest→
- **Homebridge Version**: <1.3.3-→- **Homebridge Meross Plugin Version**:
- **Homebridge Config UI X Plugin Version**:  v4.40.0
- **Operating System**:

**Comment by yonigold1** [comment]
If someone could help me im losing my mind trying to figure out whats wrong.

**Comment by donavanbecker** [comment]
Revert back to v3.5.1

**Comment by donavanbecker** [comment]
@yonigold1 Can you try the latest beta?

**Comment by yonigold1** [comment]
Yea i tried the latest beta it still seems to not work. Also my 2 meross plugs don't work on the latest beta.
In addition my MSG200 stopped working on version 3.5.1 any idea why this is happening?

**Comment by christiantschoerner** [comment]
Same issue with MSG100 for me. Try Version "v3.4.1". Works for me now

**Comment by yonigold1** [comment]
@donavanbecker how come this was closed?

**Comment by donavanbecker** [comment]
V5.0.0 was released

**Comment by yonigold1** [comment]
i just updated to 5.0.0 now but it's still not working. My 2 meross plugs are working but my MSG200 is not.

**Comment by yonigold1** [comment]
perhaps this could be of help:
i have just fresh installed the plugin and reentered all the info using Http catcher my 2 plugs work but when i try to open the garage i get this error in homebridge:
`Failed to POST to the Meross Device MSG200 at 192.168.2.***: "socket hang up"`

**Comment by yonigold1** [comment]
I have figured out the issue for some reason the static IP i set for the MSG200 changed and i had the incorrect IP in the config however i have resolved it now :)

**Comment by yonigold1** [comment]
Hey @donavanbecker just a quick request for the garage doors. Can u add the ability to put a custom amount of time for the "Garage Door Opening Time" my garage door takes 12 seconds and the options are 10, 15, 20. I would really appreciate that :)

**Comment by donavanbecker** [comment]
@yonigold1 Can you open this in a new feature request to track this feature and I can look into it.

**Comment by yonigold1** [comment]
sure :))

**Comment by yonigold1** [comment]
Hey so ive still been experiencing status update issues and here are some of the errors that periodically appear:
` Failed to refresh status of Garage: "connect EHOSTUNREACH 192.168.2.***:80" undefined`
 and
`Failed to refresh status of Garage: "read ECONNRESET" undefined`

So I turned on Homebridge Debug mode and noticed how often the plugin Polls so I thought maybe its too much polling for the MSG200 to handle and maybe it just gives up on responding so I thought maybe I can adjust the Polling interval.

However when i went to adjust the setting in the config of the plugin i put the Refresh Rate to 600 (10 Minutes) however upon restarting the value disappeared from the config and doesn't save. 
If you could help me debug and fix that it would be greatly appreciated 

I also had a quick question what is the difference between Refresh Rate and Push Rate (what does Pushing do versus Refreshing)

**Comment by yonigold1** [comment]
Awesome thanks so much but quick question what is the difference between Refresh Rate and Push Rate?

**Comment by donavanbecker** [comment]
PushRate is the time that the plugin will wait before pushing the requested changes. So if you send and on action and then change your mind and push off, and you have your pushRate set higher it would only pickup the push off. It could also be used as a delay feature.
