### ISSUE TITLE
Meross MSS310 setup

### ISSUE THREAD

**Issue by marcocattaneogotam** [donavanbecker/homebridge-meross#25]
Hi!

This is my config for a smart plug MSS310

{
            "name": "presa",
            "deviceUrl": "http://192.168.1.141",
            "hardwareVersion": 1,
            "channel": 0,
            "messageId": "d8a5c2e967c923bd80014df179bbfb59",
            "timestamp": 0,
            "sign": "82aec8a0295bd874e12ab2c3f31f77",
            "accessory": "Meross"
        }

and this is the error I get

[Config] Failed to refresh characteristics for presa: socket hang up

node:346) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'control' of undefined
    at MerossPlug.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:203:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:346) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[4/24/2020, 8:50:46 PM] [Pihole] {"status":"enabled"}
(node:346) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'control' of undefined
    at MerossPlug.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:203:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:346) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

It doesn't retrieve the status nor works. 

thanks

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try.

**Comment by marcocattaneogotam** [comment]
Thanks. I've updated the plugin, the config (with the right model), but no, it doesn't work.

This is the current config:

{
            "model": "MSS310",
            "name": "presa",
            "deviceUrl": "192.168.1.141",
            "channel": 0,
            "messageId": "d8a5c2e967c923bd80014df179bbfb59",
            "timestamp": 0,
            "sign": "82aec8a0295bd874e12ab2c3f31f77",
            "accessory": "Meross"
        }

This is what I get:

[4/28/2020, 8:51:08 PM] [presa] Set succeeded: {
  header: {
    messageId: 'd8a5c2e967c923bd80014df179bbfb59',
    namespace: 'Appliance.Control.ToggleX',
    method: 'ERROR',
    payloadVersion: 1,
    from: '/appliance/1912249200127825188148e1e9146f24/publish',
    timestamp: 1588107068,
    timestampMs: 670,
    sign: '2487c9d69692f34d4bed1c79ca1d59e8'
  },
  payload: { error: { code: 5001, detail: 'sign error' } }
}
[4/28/2020, 8:51:08 PM] [presa] setOnCharacteristicHandler: false
[4/28/2020, 8:51:08 PM] [presa] calling getOnCharacteristicHandler for MSS310 at 192.168.1.141...
(node:374) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'digest' of undefined



[4/28/2020, 8:51:08 PM] [presa] calling getOnCharacteristicHandler for MSS310 at 192.168.1.141...
(node:374) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'digest' of undefined
    at Meross.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:297:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)



Thanks again

**Comment by donavanbecker** [comment]
@marcocattaneogotam what are you using to get your `timestamp`, `messageId`, and `sign`?

Can you provide the request body? from the /config.
![IMG_0074](https://user-images.githubusercontent.com/9875439/80537473-c05b4600-8969-11ea-92af-84a8b6a65063.PNG)
![IMG_C2CF02C82787-1](https://user-images.githubusercontent.com/9875439/80537442-b46f8400-8969-11ea-91d3-4506c9cfe0bb.jpeg)

**Comment by moviedan** [comment]
I’m having a similar issue. I originally used Charles Proxy on the device to sniff traffic to the plug, and retrieved similar time stamp, messageID, and Sign values to @marcocattaneogotam. 

I don’t think they’re right though. My understanding is we’re supposed to grab these as a result of the call to /config, but in Charles I keep getting a 503 when calling that end point. Any ideas?

**Comment by donavanbecker** [comment]
[HTTP Catcher](https://apps.apple.com/us/app/http-catcher/id1445874902), try this one! It is going to be a little different then my instructions, but it works.

- Hit Configure in the top right.
- Enable VPN.
- Hit Start to start collecting.
- In "Search URL", search for your IP of the meross plug.
- You will see a Post to /config with a `200` Response with `application/json`.
- Click into that and hit Response header.
- From there you will find the `sign`,`timestamp`, and `messageId`.

**Comment by moviedan** [comment]
Amazing @donavanbecker - worked like a charm. I’m going to work through and set the other plugs up now. Thanks for your help.

**Comment by marcocattaneogotam** [comment]
It worked for me too. Thanks!

**Comment by donavanbecker** [comment]
@marcocattaneogotam good to hear!!

**Comment by IsonCode** [comment]
Hello, I have the same problem with MSS310 plugin version v5.0.1, homebridge v1.3.4.
I have successfully set up 2 MSS210 plugs, but I have tried to set up with the same exact method a MS310 plug and it does not work.
I know how to proceed te setup (because I have already successfully setup 2 plugs).
