### ISSUE TITLE
Show power strips as a single device

### ISSUE THREAD

**Issue by bosco90** [donavanbecker/homebridge-meross#253]
**Is your feature request related to a problem? Please describe.**

Power strips should be shown as a single device with multiple outlet

**Describe the solution you'd like**

The same that happens with power strips that have HomeKit native support, like MSS425F

**Describe alternatives you've considered**

Using every outlet as a single device is fine but takes a lot of space in the Home app, grouping the accessories could be a solution but it would take too many steps to turn On/Off a single outlet.

**Additional context**

<a><img src="https://user-images.githubusercontent.com/78073930/111191990-e527ce80-85b8-11eb-9492-5c98f5401b2a.jpg" width="150px"></a>

<a><img src="https://user-images.githubusercontent.com/78073930/111191985-e35e0b00-85b8-11eb-91d5-d90d98b8b3e8.jpg" width="400px"></a>

**Comment by donavanbecker** [comment]
@bosco90 so for MSS425F does it show up as 4 outlets for the 4 outlets and then 1 outlet for the USB?

**Comment by bosco90** [comment]
MSS424F is HomeKit compatible and it shows as on the images on the original post, while the MSS425E that I expose via the plugin shows every outlet as a separate device.

**Comment by donavanbecker** [comment]
and MSS425E is 4 outlets and USB? are the USBs each individually able to be controlled? or are they all controlled off one button?

**Comment by bosco90** [comment]
All usb are controlled by one button on both devices
