### ISSUE TITLE
Custom Values for Garage Door Opening Time

### ISSUE THREAD

**Issue by yonigold1** [donavanbecker/homebridge-meross#254]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. 

**Describe the solution you'd like**
I would like to be able to enter a custom value for "Garage Door Opening Time"

**Describe alternatives you've considered**
Asked for help :)

**Additional context**

**Comment by donavanbecker** [comment]
@yonigold1 can you try the new beta?

Beta: `5.0.1-beta.1`

**Comment by yonigold1** [comment]
sure ill update to it now :)

**Comment by yonigold1** [comment]
Okay so i tested it today it seemed like it didn't work the accessory in homekit said opening for a few seconds extra I will count it next time to see whether or not its still 15 or if it went to the value I put (12)

**Comment by jjag65** [comment]
Hi, 
I have the MSG-100 garage door opener and I’m running v5.0.1.  The door opens/closes just fine through the HomeKit app, however, when I use the physical door open/ close button the status of the device gets screwed up in the HomeKit app.  Any advice is much appreciated.

**Comment by fpeghub** [comment]
Hi all,
would like to confirm the comment from jjag65.
Same problem with MSG-100 on my side.
Last working version was 3.5.0 all newer versions failed.
Kind regards

**Comment by yonigold1** [comment]
> Hi, 
> 
> I have the MSG-100 garage door opener and I’m running v5.0.1.  The door opens/closes just fine through the HomeKit app, however, when I use the physical door open/ close button the status of the device gets screwed up in the HomeKit app.  Any advice is much appreciated.

I'm having this same issue when the door opens through the keypad or any thing other than homekit the garage status in homekit says closing when it's open and is just incorrect.

**Comment by fpeghub** [comment]
Hi,
I can confirm the same issue. Last working version was 3.5.0
Am 1. Apr. 2021, 17:59 +0200 schrieb Jailbreaker ***@***.***>:

**Comment by yonigold1** [comment]
@donavanbecker was there any significant change to the garage controllers from v3.5.0 to v5.0.0?
