### ISSUE TITLE
Setting up with HOOBs

### ISSUE THREAD

**Issue by ChopsKingsland** [donavanbecker/homebridge-meross#26]
I am new to HOOBS, and I am very confused about how to set this up. Could I have some help, as the instructions are very confusing?

**Comment by donavanbecker** [comment]
@ChopsKingsland first of all, switch to using just [Homebridge](https://github.com/homebridge/homebridge) since the [Config UI](https://github.com/oznu/homebridge-config-ui-x/wiki) has it built in to allow for easier setup. second of all you will have to get information from Charles proxy app, either a computer or mobile device. this is where you will get the `timestamp`, `messageId`, `sign`, `IP`, and `channel`.

**Comment by ChopsKingsland** [comment]
What's the difference between Homebridge and HOOBS? HOOBS has a UI too

**Comment by donavanbecker** [comment]
Well homebridge is were it all started. HOOBs is based off homebridge.

also below is an example of the easy config you get with config ui.

<img width="409" alt="Screen Shot 2020-04-28 at 9 00 17 AM" src="https://user-images.githubusercontent.com/9875439/80496343-b0724080-892e-11ea-99b6-8534c567aa91.png">

**Comment by ChopsKingsland** [comment]
Charles Proxy on iOS costs £8.99, is there a free way of doing it?

**Comment by donavanbecker** [comment]
use free trial on mac. https://www.charlesproxy.com

**Comment by ChopsKingsland** [comment]
i dont own a mac...

**Comment by ChopsKingsland** [comment]
isnt there a simpler way, that connects straight to the Meross servers without charles?

**Comment by donavanbecker** [comment]
> i dont own a mac...

do you have a pc???

**Comment by ChopsKingsland** [comment]
yes

**Comment by donavanbecker** [comment]
> isn't there a simpler way, that connects straight to the Meross servers without Charles?

unfortunately as of now we don't have a simpler way. Possibly implementing a meross cloud way of setting up meross in the future. Which if you want to submit a pr for that, we would gladly implement it.

**Comment by donavanbecker** [comment]
> yes

there is a pc trial that you can download.

**Comment by donavanbecker** [comment]
> there is a pc trial that you can download.

@ChopsKingsland are you having luck with the pc app?

**Comment by donavanbecker** [comment]
also if you want to test our `beta` out we are trying to make the setup easier with config ui. 

Here are the install instructions:
```
sudo npm install -g --unsafe-perm homebridge-meross@beta
```
to revert back:
```
sudo npm install -g --unsafe-perm homebridge-meross@latest
```
<img width="409" alt="Screen Shot 2020-04-28 at 9 44 29 AM" src="https://user-images.githubusercontent.com/9875439/80501271-dd295680-8934-11ea-8db4-53e4f348e32d.png">

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try.

**Comment by ChopsKingsland** [comment]
What’s in the new version?

**Comment by donavanbecker** [comment]
visit the link provided.

**Comment by ChopsKingsland** [comment]
I moved over to Homebridge, as it works better with a different plugin that wouldn’t work with HOOBs

**Comment by donavanbecker** [comment]
> I moved over to Homebridge, as it works better with a different plugin that wouldn’t work with HOOBs

That’s awesome. Did you get this plugin to work?

**Comment by ChopsKingsland** [comment]
I’m trying to find a free alternative that can always run on my pi/iPad

**Comment by donavanbecker** [comment]
@ChopsKingsland are you talking about charles proxy?

**Comment by ChopsKingsland** [comment]
yep

**Comment by donavanbecker** [comment]
[HTTP Catcher](https://apps.apple.com/us/app/http-catcher/id1445874902)

**Comment by ChopsKingsland** [comment]
once its setup, do i need http catcher at all?

**Comment by donavanbecker** [comment]
Nope. After it’s setup you shouldn’t need it anymore.

**Comment by ChopsKingsland** [comment]
okey dokey

**Comment by ChopsKingsland** [comment]
its all setup now. Thanks!

**Comment by donavanbecker** [comment]
> its all setup now. Thanks!

Awesome!

**Comment by dennis1893** [comment]
Translate with google:

HI!!

When I start HTTP Catcher and open my garage, I get several / config application / json entries

How do I find the correct entry for "messageID" "timestamp" and "sign"

There are different entries with:

namespace: Appliance.System.Online

with another

namespace: Appliance.Digest.TimerX

namespace: Appliance.Digest.TriggerX

Which one is the right one

Thanks
