### ISSUE TITLE
Compatibility with Refoss devices?

### ISSUE THREAD

**Issue by arharp** [donavanbecker/homebridge-meross#260]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

I'm wondering if this plugin supports, or could easily support, Refoss garage door openers. They appear to be identical to the Meross devices.

**Describe alternatives you've considered**

It may not make sense to add support directly to this plugin, but I'm mainly wondering how easy it would be to adapt this plugin to support Refoss.

**Additional context**

No other additional context.

**Comment by donavanbecker** [comment]
@arharp It should work, you will need to use http catcher to get the needed info and then try it out.

**Comment by rcoletti116** [comment]
I have refoss devices (not garage door opener specifically) that work fine. The products are identical. Even the model numbers are the same compared to the meross versions.
