### ISSUE TITLE
[BUG] MSS510 Smart Wall Switches Not Responsive & Show incorrect firmware upgrade option in HomeKit

### ISSUE THREAD

**Issue by SemoTech** [donavanbecker/homebridge-meross#293]
**Description:
It seems that Single Pole Meross Smart Wall Switches (model MSS510) running latest v3.1.5 firmware, are showing in HomeKit that there is a firmware upgrade available, and they are also unresponsive.  A toggle seems to take effect but then quickly reverts. This is NOT happening with the MSS550 3-Way model Smart Wall Switches (firmware v3.1.3). Both the Meross App and their tech support team confirm there is no such upgrade for MSS510, and that the v3.1.5 firmware is the latest for the MSS510 smart switches. While not working in HomeKit, the MSS510 switches are able to be controlled normally through the Meross iOS App. 

**Summary:
HomeBridge somehow is misinforming HomeKit that there is a firmware update available for the Single Pole MSS510 smart switches, when in fact there is none. Side effect also seems lack of toggle/operational control. Interestingly the 3-Way MSS550 switches seem unaffected. 

**Steps to reproduce:
Add any MSS510 smart switch running latest v3.1.5 firmware to the Meross plugin.

**Expectation:
The MSS510 smart switches should be controllable through HomeKit, and not show there is a firmware upgrade when there isn't. 

**Logs:**
There are no logs in Homebridge (even in debug mode) pertinent to this issue and no visible errors.

**Homebridge Config (sanitized):**

```json 
{
    "bridge": {
        "name": "Homebridge 0BD2",
        "username": "0F:6C:13:C8:0B:D2",
        "port": 51605,
        "pin": "822-17-817",
        "bind": [
            "eth0"
        ],
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "delay": 5000,
            "disableSensor": false,
            "startOnReboot": false,
            "accessory": "DelaySwitch"
        },
        {
            "name": "Pi Hole Toggle",
            "auth": "6508b645731ddbf98e2b9ec5d",
            "ssl": false,
            "rejectUnauthorized": true,
            "host": "localhost",
            "port": 80,
            "baseDirectory": "/admin/",
            "time": 0,
            "reversed": false,
            "logLevel": 1,
            "accessory": "Pihole"
        },
        {
            "username": "email@domain.com",
            "password": "password",
            "name": "Sense Energy Meter",
            "pollingInterval": 300,
            "verbose": false,
            "accessory": "SensePowerMeter"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "172.31.0.1",
                    "password": "password",
                    "username": "homebridge@udm.com"
                }
            ],
            "verboseFfmpeg": false,
            "platform": "UniFi Protect"
        },
        {
            "name": "Govee Hydrometer",
            "batteryThreshold": 25,
            "debug": false,
            "platform": "GoveeHomebridgePlugin"
        },
        {
            "name": "Meross",
            "devices": [
                {
                    "name": "MBA Exhaust Vent Switch",
                    "model": "MSS510",
                    "serialNumber": "na",
                    "firmwareRevision": "3.1.5",
                    "deviceUrl": "172.31.0.82",
                    "messageId": "88fd5d123e1edb135bd56e1f445",
                    "timestamp": 1609812486,
                    "sign": "19f51e19dc190e491b0931c4ab"
                },
                {
                    "name": "Office Sconces Switch",
                    "model": "MSS510",
                    "serialNumber": "na",
                    "firmwareRevision": "3.1.5",
                    "deviceUrl": "172.31.0.105",
                    "messageId": "6413d1d6a5ab8786b070e593",
                    "timestamp": 1609721788,
                    "sign": "3fe104fe177894b3a3a530c81"
                },
                {
                    "name": "MBR Sconce Switch",
                    "model": "MSS510",
                    "serialNumber": "na",
                    "firmwareRevision": "3.1.5",
                    "deviceUrl": "172.31.0.141",
                    "messageId": "de0cb6ed8fc9b97ce95a9257",
                    "timestamp": 1610146761,
                    "sign": "a3570ac9470f971a6126b797b"
                },
                {
                    "name": "Backyard Right Sconce Switch",
                    "model": "MSS510",
                    "serialNumber": "",
                    "firmwareRevision": "3.1.5",
                    "deviceUrl": "172.31.0.77",
                    "messageId": "e6e3c89fc370ad15f602bea",
                    "timestamp": 1610146977,
                    "sign": "f669f0b51e3e2a90239ce0c"
                },
                {
                    "name": "Entrance Ceiling Lights",
                    "model": "MSS550",
                    "serialNumber": "na",
                    "firmwareRevision": "3.1.5",
                    "deviceUrl": "172.31.0.165",
                    "messageId": "8a90d76f13fa2b7a412a5c5",
                    "timestamp": 1611097245,
                    "sign": "ab0f0a8af0d722713d6d3b73"
                },
                {
                    "name": "Downstairs Hallway Light",
                    "model": "MSS550",
                    "serialNumber": "na",
                    "firmwareRevision": "3.1.2",
                    "deviceUrl": "172.31.0.169",
                    "messageId": "1674e764c74bc7406e",
                    "timestamp": 1611183821,
                    "sign": "bc7695c7fb771dc1b7cb"
                }
            ],
            "pushRate": 5,
            "platform": "Meross"
        },
        {
            "bonds": [
                {
                    "ip_address": "172.31.0.162",
                    "token": "e93434bec5"
                }
            ],
            "include_dimmer": true,
            "include_toggle_state": true,
            "fan_speed_values": true,
            "platform": "Bond"
        },
        {
            "email": "email@domain.com",
            "password": "afcaefacawerac",
            "name": "LiftMaster-MyQ",
            "platform": "myQ"
        }
    ]
}
```

**Screenshots:**
![IMG_2968](https://user-images.githubusercontent.com/1452100/122989891-2ff37800-d358-11eb-9a04-64c89b31cf6d.jpg)
![IMG_2969](https://user-images.githubusercontent.com/1452100/122989913-37b31c80-d358-11eb-9a8f-d764da5e6aa9.jpg)

# **Environment:**

- **Node.js Version**: v14.17.1
- **NPM Version**: v7.18.1
- **Homebridge Version**: v1.3.4
- **Homebridge Meross Plugin Version**: latest (v5.0.3)
- **Homebridge Config UI X Plugin Version**: latest (v4.41.1)
- **Operating System**: Debian v10.7 on Raspberry PI 4

**Comment by SemoTech** [comment]
Additional info: I reached out to Meross Support and they said that this may be due to how the plugin is identifying the MSS510 chipset. This likely means there should be a way to fix this in the plugin, as it's working just fine with the MSS550  models.

**Comment by ShaunRoberts543** [comment]
I am seeing the same issue on the 510 switch as well.

**Comment by SemoTech** [comment]
> I am seeing the same issue on the 510 switch as well.

I believe you meant to say the 550.  

There is definitely a bug as the plugin is sending erroneous info to HomeKit.  
Is there a fix???

**Comment by donavanbecker** [comment]
check out [v6 Beta](https://github.com/bwp91/homebridge-meross/issues/300)!

**Comment by bwp91** [comment]
It would be useful to know if this bug(?) still exists in the new beta of the plugin (v6).

If you do try the beta, please review the change log as some things have changed with regards to local connection mode and the configuration.

Thanks

**Comment by SemoTech** [comment]
Currently having a hardware issues with my Pi that the Homebridge runs on, so it's been offline.  As soon as I get a replacement I will try the v6 Beta.  Does one just uninstall the v5.x version and manually install v6 beta or is there another process?

**Comment by bwp91** [comment]
Due to the configuration changes it’s easiest to uninstall and install new version and use the homebridge ui to fill out the config. Your accessories will automatically be readded in the new needed format.

**Comment by yonigold1** [comment]
On v6 my MSS110 plugs are showing there is a firmware update available however there isn't actually one. Any fix yet?

**Comment by bwp91** [comment]
> On v6 my MSS110 plugs are showing there is a firmware update available however there isn't actually one. Any fix yet?

Can you try using the plugin settings to add a device entry for your device and use the firmware box to override the firmware to a number bigger?

It'll probably take a couple of plugin restarts for the firmware version to update in homekit... but i'm hoping the available update message will go away

**Comment by yonigold1** [comment]
Changed the firmware versions on both plugs to 999.9 and ive restarted homebridge and no luck im gonna try restarting my pi

**Comment by yonigold1** [comment]
Restarting my Pi did the trick thanks so much for your help! :)

**Comment by SemoTech** [comment]
@bwp91 Do we know in the case where we use the Meross login to load the Meross devices automatically, if the firmware update erroneous notice in HK goes away?   I ask since the solution outlined above involved manually overriding the firmware version in the plugin's configuration for that particular device. However if using the Meross login option you do not have that ability, unless you also manually add that particular device, which kind of defeats the purpose and simplicity of the main login method.

**Comment by bwp91** [comment]
The incorrect firmware update notification is fixed and does not appear for new accessories that are added to Homebridge.

For existing accessories that still display this error then it will be required as a one off to remove the accessory from the cache so it is re-added.

I removed the firmware override option for cloud devices as it’s purpose was to remove this incorrect notification, but now as it is fixed, there is no need for it.

It remains there for local accessories simply as a way of specifying a firmware version in the home app.

**Comment by SemoTech** [comment]
Awesome sauce @bwp91 Thank you!
