### ISSUE TITLE
MSG-100 status not working properly on Homekit

### ISSUE THREAD

**Issue by Lui5Jacint0** [donavanbecker/homebridge-meross#307]
### What issue do you have? Please be as thorough and explicit as possible.

I have a Meross MSG-100 door opener that pushes the notifications “door closed” and “door open” but in HomeKit the status freezes at “closing” and “opening” cards.
On homebridge log states “Door closed”

### Details of your setup.
*Homebridge UI-X

* Which version of Homebridge do you have?
* homebridge-config-ui-x 4.41.1

* Which platform do you run Homebridge/HOOBS on 
* Raspberry Pi 
*  Node.js v14.15.5.

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
5.0.3 I had this issue in every version

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSG-100

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @Lui5Jacint0 

Please consider trying the beta version of the plugin, I have recently made some improvements to the garage to hopefully avoid this freezing on opening/closing state.

Be aware the beta version contains some configuration changes, especially if you have devices configured for local control. Please check the changelog.

**Comment by theplanekid** [comment]
I believe I’m facing a similar issue on the MSG-100:

> Homebridge version: homebridge-config-ui-x v4.41.1

> node.js version: v14.17.3

> Plug-in version: homebridge-meross v6.0.0-beta.19

Homekit reports opening, open, and closing, but not closed. 
Homebridge log does the same. 

Also getting
`[27/07/2021, 16:05:14] [(Meross] [Garage Door L] failed to refresh status as Canno
tread property
"digest
of undefined at deviceGarage.externalUpdate(/usr/local/
lib/node modules/homebridge-meross/lib/device/garage.js:381:33). `
after every opening and closing state change.

**Comment by bwp91** [comment]
@theplanekid can you try beta.20?

**Comment by theplanekid** [comment]
on beta.20, log reports;
```
[27/07/2021
16:11:371 (Meross]
[Garage Door L] current target [open].
[27/07/2021, 16:11:371 [Meross] [Garage Door L] current state [opening].
[27/07/2021.
16:11:571
[Meross] [Garage Door L]
current state [open].
[27/07/2021
16:12:02] [Meross] [Garage Door L] current target [closed]
[27/07/2021,
16:12:021
[Meross] [Garage Door L]
current
state (closing].
[27/07/2021, 16:12:14] (Meross] [Garage Door L] current state [open]
```

**Comment by bwp91** [comment]
and beta 22?

**Comment by bwp91** [comment]
getting there i think 🤣

**Comment by theplanekid** [comment]
works great, tried it 3 times with no issues so far
i think it’s fixed!

**Comment by mike43** [comment]
Agreed! I've come late to the thread tired of HAP dropouts for a pair of MSG100's I've been trying to stabilise for months. Only just installed and configured in local mode. Both working well so far.

I'm running HOOBS 4.0.96 (RPI 4B) and plugin v6.0.0-beta.22 | Node v14.17.2 | HB v1.3.4.

I've had issues with false positives for "obstruction detection" in the past so keen to see if this resolves (along with availability in home.app and associated automations)... will post if any issues.

Cheers, and big thank you to @bwp91 👏

**Comment by bwp91** [comment]
This _should_ be fixed in the newest beta (22).
I’ll copy what I wrote in the other issue thread:

when opened from homekit, if after the operation time the state is still opening then it will be updated to open

when closed from homekit, the plugin will mark as closing then wait for a “closed” notification from meross before marking as closed. due to security i think this is important. if after the operation time plus an extra 15 seconds the garage is still “closing” then the garage will then be marked as **open** again.

the cloud control statuses are in real time, and local polling is every 5 seconds (unless configured higher), so the garage should mark as closed when it, or just after, it has physically closed

**Comment by bwp91** [comment]
Also to note, if the garage is controlled via meross app or a physical button, the plugin will no longer use opening/closed status, will simply mark as open or closed.

Also, obstruction detection is now unused as it is impossible for the plugin to truly determine this. 

The beta is there for anyone to try!

**Comment by Lui5Jacint0** [comment]
Working great thanks!

**Comment by bwp91** [comment]
Could you just check garage is still working on beta 28? Thanks

**Comment by theplanekid** [comment]
beta.28, tested 3 times seems to be working fine
