### ISSUE TITLE
MSL120 not supported 

### ISSUE THREAD

**Issue by Ghoster177** [donavanbecker/homebridge-meross#308]
[Meross] [Lampe 1] is currently not supported, do create a github issue https://git.io/JtfVC with info:
```json
{"uuid":"2009104110567190829048e1e931c4a4","onlineStatus":1,"devName":"Lampe 1","devIconId":"device036","bindTime":1627666088,"deviceType":"msl120d","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.1.8","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.8","hbDeviceId":"2009104110567190829048e1e931c4a4","model":"MSL120D"}
```

**Comment by bwp91** [comment]
Hi @Ghoster177 
Can you update to beta version of the plugin - v6.1.2-beta.7 - to see if this now works for this model?
Thanks

**Comment by apptl** [comment]
MSL120D works with the beta version!

**Comment by Ghoster177** [comment]
Yes works but not when i'm leaving home, it works only on my wifi and when i disconnect home kit show me not responding and when reconnect show me the same error. 
This error shows in homebridge...
[Meross] [Lampe 1] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2009104110567190829048e1e931c4a4","onlineStatus":1,"devName":"Lampe 1","devIconId":"device036","bindTime":1627666088,"deviceType":"msl120d","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.1.8","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.8","hbDeviceId":"2009104110567190829048e1e931c4a4","model":"MSL120D"}

**Comment by bwp91** [comment]
Accessories not working when you disconnect off your wifi is not normally a plugin issue. You need a homehub, see

https://github.com/homebridge/homebridge/wiki/Remote-Access

**Comment by Ghoster177** [comment]
And if i open the ports of my box ? 
Because hum hum apple's products are a bit expensive hum hum

**Comment by bwp91** [comment]
i’m happy the device implementation in the plugin is working.

with regards to home app working off wifi, that’s a different topic(!) but yes you need a home hub.
