### ISSUE TITLE
Home app indicates updates available while there are none

### ISSUE THREAD

**Issue by amrishraje** [donavanbecker/homebridge-meross#309]
### What issue do you have? Please be as thorough and explicit as possible.

After the Meross plug-in upgrade to v6, I reconfigured my devices by enabling cloud mode instead of local mode. Home app is now showing that updates are available for my devices (5) and upon clicking the update link, home app opens the Meross app. However, there are no firmware updates available in Meross. I simply can’t get the updates available message to go away. The home all also displays a badge with 5 in it. 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Hoobs 

* Which version of Homebridge/HOOBS do you have?

4.0.98

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

6.1.1

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
Mss110 x 5 all on firmware v 2.1.21

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @amrishraje 

You can use the plugin settings to specify a firmware version to 'override' the version that home app shows.

For each of your devices, add entry in the 'Device Settings' section of the settings, filled out the required info, and one of the last options is the firmware override. 

Put in a value that is higher than the real version, so if they are at 2.1.21 then try 2.2.21.

You will need to restart homebridge a couple of times for it to refresh in the home app, but once it's updated there then the firmware update messages should go away.

**Comment by bwp91** [comment]
Restarting HOOBS may also help, see https://github.com/bwp91/homebridge-meross/issues/293#issuecomment-889497304

**Comment by amrishraje** [comment]
Thanks for the quick response. I kept the config as cloud, but added in the devices locally. Had to key in both device ip and UUID from logs for it to pickup the local config. Did an override of the firmware. The updated firmware was reflected in home app after a couple of hoops restarts. However, even with a higher firmware number in home, the home app still thinks that an upgrade is available. I set the firmware to 2.2.25, 4.0, 4.0.1 and in all cases - it still thinks a firmware update is available!

**Comment by bwp91** [comment]
Try firmware as `999.9` this seemed to work for other user

**Comment by amrishraje** [comment]
Thanks. I changed it from cloud to local and set the version to 6.1.1. That fixed it for me. Local setup with key is awesome. So glad to not have to deal with http catcher anymore. 

Regards,
Amrish

On Aug 1, 2021, at 11:04 AM, Ben ***@***.***> wrote:

﻿
Try firmware as 999.9 this seemed to work for other user

**Comment by amrishraje** [comment]
What I did was a workaround. I believe the issue still persists. Perhaps it a minor annoyance that could be put in backlog. 

Regards,
Amrish

On Aug 1, 2021, at 1:21 PM, github-actions[bot] ***@***.***> wrote:

﻿
This issue has been marked as complete as I believe the original query has been fixed/answered or will not be actioned. The issue will be closed in three days. If you feel the issue requires further attention then please let me know. Thanks!

**Comment by bwp91** [comment]
This is home app behaviour, I think it’s trying to match accessories with their equivalent HomeKit enabled versions, but for some reason is showing a firmware update available when in fact the firmware is already up to date.

So whatever I can try will effectively be a workaround.

I think this is why the firmware override was originally added to the plugin in the first place.

I could try adding 'MEROSS' to the front of the model that is saved by HomeKit, to try and disrupt this link, but again, anything would be a workaround.

**Comment by amrishraje** [comment]
Yeah,I understand. I must mention that I appreciate all the great work you are doing making this available for the public. 

On a side note - separate issue that you may be able to fix. I also use the Alexa plugin to expose my HomeKit devices to my Alexa echo. When the Meross switches show up in Alexa app, they all show up as HOOBS. This is irrespective of whether I override the name of each device via config or just use cloud. Let me know if you want me to report this as a separate issue for tracking purposes. Thanks again. 

Regards,
Amrish

On Aug 1, 2021, at 3:44 PM, Ben ***@***.***> wrote:

﻿
This is home app behaviour, I think it’s trying to match accessories with their equivalent HomeKit enabled versions, but for some reason is showing a firmware update available when in fact the firmware is already up to date.

So whatever I can try will effectively be a workaround.

I think this is why the firmware override was originally added to the plugin in the first place.

I could try adding 'MEROSS' to the front of the model that is saved by HomeKit, to try and disrupt this link, but again, anything would be a workaround.

**Comment by donavanbecker** [comment]
@amrishraje have you tried switching to homebridge?

I would recommend[ moving to homebridge](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge).

And see if that makes a difference.

**Comment by amrishraje** [comment]
@donavanbecker I have played around both homebridge and Hoobs and finally settled on Hoobs. They are pretty much the same at their core but I prefer Hoobs v4. Anyways - I am ok with the workaround I mentioned above. Works for now.

**Comment by bwp91** [comment]
@amrishraje 

I have just released a beta version of the plugin which changes the manufacturer label, which seems to have broken this 'link' with Meross HomeKit official stuff.

You can install the beta, but you will need to remove your accessories from the cache so they are re-added (also remove the firmware override from the config **before**, so they are re-added with the real firmware version).

My meross outlet doesn't have a homekit equivalent version, so I can't be certain this has fixed/removed the incorrect firmware update alert.

But I think it will work!
