### ISSUE TITLE
MSL430 real-time light cloud updates not supported

### ISSUE THREAD

**Issue by ColinScattergood** [donavanbecker/homebridge-meross#310]
### What issue do you have? Please be as thorough and explicit as possible.
In the new update, more of my Meross devices showed up than ever which is great! That said, my ambient light (MSL430) is throwing the following error in the logs:

10:12:27 AMMeross BridgeMeross[Smart Ambient Light] current state [off].
10:12:27 AMMeross BridgeMerossWARNING[Smart Ambient Light] real-time light cloud updates not supported.
10:12:27 AMMeross BridgeMerossWARNING[Smart Ambient Light] please post the below message in a github issue.
10:12:27 AMMeross BridgeMerossWARNING[Smart Ambient Light] {"togglex":[{"onoff":0,"lmTime":1627827147,"channel":0}]}.
10:12:55 AMMeross BridgeMerossWARNING[Smart Ambient Light] failed to request status as this.colourUtils.mr2hk is not a function or its return value is not iterable at deviceLightRGB.applyUpdate (/var/lib/hoobs/meross/node_modules/homebridge-meross/lib/device/light-rgb.js:497:44).

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
* - HOOBS

* Which version of Homebridge/HOOBS do you have?
HOOBS 4.0.98

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
RPI 3 / NPM 6.14.14

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
Started w/ the most recent update to 6.2.0 (though its still a big improvement over last version)

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
The MSL430 is throwing the error.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Can you update to the beta version of the plugin I have just published? v6.2.1-beta.0

Instructions for HOOBS4:

----

HOOBS 4

Go to the plugin page in the HOOBS UI and click on the 'Versions' tab
In the 'Tags' section, click on the download icon next to the version with beta on the right hand side
The version number will not be correct but this will still download the latest beta version
The UI will prompt you to select a bridge for the installation, choose your existing Meross bridge
The bridge will automatically restart and you can verify the plugin version in the startup logs

**Comment by ColinScattergood** [comment]
Worked like a charm!

**Comment by bwp91** [comment]
also thanks for the star boosting on hoobs 😆

**Comment by ColinScattergood** [comment]
> also thanks for the star boosting on hoobs 😆

Of course. I kept wondering why it was so low and then realized there were 2 (old) reviews! Thanks for your work on this you're crushing it.
