### ISSUE TITLE
MSS425E outlets show as switches

### ISSUE THREAD

**Issue by ColinScattergood** [donavanbecker/homebridge-meross#311]
### What issue do you have? Please be as thorough and explicit as possible.
I use the Meross MSS425E power strip, and the outlets show as switches.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
HOOBS 4.0.98

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
RPI 3 / NPM 6.14.14

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
Started w/ the most recent update to 6.2.0 (though its still a big improvement over last version)

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSS425E Smart Wifi Surge Protector

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
you can use the config to expose as outlets, add an entry for your device in the 'Device Settings' and use the Show As option...

<img width="421" alt="Screenshot 2021-08-01 at 15 31 33" src="https://user-images.githubusercontent.com/43026681/127774681-ebae18d3-46d9-4d42-9f91-eb3b22a55e75.png">

looking into the other light issue now :)

**Comment by ColinScattergood** [comment]
> you can use the config to expose as outlets, add an entry for your device in the 'Device Settings' and use the Show As option...
> 
> <img alt="Screenshot 2021-08-01 at 15 31 33" width="421" src="https://user-images.githubusercontent.com/43026681/127774681-ebae18d3-46d9-4d42-9f91-eb3b22a55e75.png">
> 
> looking into the other light issue now :)

Ah duh, thanks!
