### ISSUE TITLE
MPD100 went from (correctly) being a dimmer to being an on/off outlet. I think this is my last "issue" with the new update! :)

### ISSUE THREAD

**Issue by ColinScattergood** [donavanbecker/homebridge-meross#312]
### What issue do you have? Please be as thorough and explicit as possible.
I use an MPD100 Smart Plug-In Dimmer for lights on my patio. With the auto detection in the latest update, it is an on/off instead of a dimmer...Maybe this is a quick fix on my end? Hopefully :)

Oh one other relevant note - I don't think MPD100 has been officially supported, but I had it set up as an MSL100 Dimmable Bulb and that did the trick in the past.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
HOOBS 4.0.98

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
RPI 3 / NPM 6.14.14

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
6.2.1 beta

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MPD100

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Can you try another beta, 6.2.1-beta.2? have added this model to the configuration and then the plugin should recognise it as a dimmer

**Comment by ColinScattergood** [comment]
Honestly how do I give this plugin more than 5 stars? You are the man thank you so much for the ridiculous turnaround!
