### ISSUE TITLE
MSS550/L Not Supported

### ISSUE THREAD

**Issue by bkarakashev** [donavanbecker/homebridge-meross#314]
[Meross] [MSS550/L] is currently not supported:
{
  "uuid": "1903116567336739080834298f1c9af8",
  "onlineStatus": 1,
  "devName": "Hallway",
  "devIconId": "device048_eu",
  "bindTime": 1623349266,
  "deviceType": "mss550l",
  "subType": "eu",
  "channels": [{}],
  "region": "eu",
  "fmwareVersion": "2.1.6",
  "hdwareVersion": "2.0.0",
  "userDevIcon": "",
  "iconType": 1,
  "skillNumber": "",
  "cluster": 1,
  "domain": "mqtt-eu.meross.com",
  "reservedDomain": "mqtt-eu.meross.com",
  "firmware": "2.1.6",
  "hbDeviceId": "1903116567336739080834298f1c9af8",
  "model": "MSS550L"
}

**Comment by bwp91** [comment]
duplicate of #313
