### ISSUE TITLE
MSS510H not supported

### ISSUE THREAD

**Issue by Perilax-De** [donavanbecker/homebridge-meross#315]
Hello,

the MSS510H is currently not supported.

{"uuid":"1902210180309639080234298f1c3827","onlineStatus":1,"devName":"Steckdose Terrasse","devIconId":"device028_eu","bindTime":1556197028,"deviceType":"mss510h","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"3.1.3","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"3.1.3","hbDeviceId":"1902210180309639080234298f1c3827","model":"MSS510H"}

**Comment by bwp91** [comment]
Hi, please install beta version 6.3.1-beta.0 of the plugin.
Should enable this device to work!

**Comment by Perilax-De** [comment]
Hello,

with beta version 6.3.1-beta.0 it works perfect.

Thank you !

**Comment by bwp91** [comment]
good to hear!
