### ISSUE TITLE
MSS110r switch is currently not supported - After Upgrade to 6.3

### ISSUE THREAD

**Issue by atlienk** [donavanbecker/homebridge-meross#316]
### What issue do you have? Please be as thorough and explicit as possible.

HomeKit enabled switch (MSS110R) throwing warning message after plugin upgrade indicating that it is not supported. Switch continues to appear in Home App and functions as expected.

### Details of your setup.

HomeBridge UI Version: homebridge-config-ui-x v4.41.2 

Node Version: Node.js v14.17.4

Meross Plugin Version: homebridge-meross v6.3.0 

Product Version: MSS110R

### Please paste any relevant logs below.

[Switch Name] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2101209938144951854048e1e947a3c2","onlineStatus":1,"devName":"Meross Apple TV","devIconId":"device001","bindTime":1622034212,"deviceType":"mss110r","subType":"us","channels":[{}],"region":"us","fmwareVersion":"4.1.21","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.1.21","hbDeviceId":"2101209938144951854048e1e947a3c2","model":"MSS110R"}

```

```

**Comment by bwp91** [comment]
Hi, please install beta version 6.3.1-beta.1 of the plugin.
Should stop this warning showing!
