### ISSUE TITLE
🚨 Inaccurate Firmware Update Alert

### ISSUE THREAD

**Issue by aeropink** [donavanbecker/homebridge-meross#317]
### What issue do you have? Please be as thorough and explicit as possible.
Homekit says update is available but there is no update in the Meross app.  Firmware match in HomeKit and Meross app.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

v4.41.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Windows

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

6.3.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSS110 plugs

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @aeropink 

Please see https://github.com/bwp91/homebridge-meross/issues/293#issuecomment-889490094 and comments going forward.

This is a known problem, the only current way around this is to manually increase the firmware value via the plugin settings.

Thanks!

**Comment by aeropink** [comment]
My firmware in HomeKit and Meross match and it still says update is available.

**Comment by donavanbecker** [comment]
> My firmware in HomeKit and Meross match and it still says update is available.

This is a Home app issue, use the settings to override.

**Comment by aeropink** [comment]
I have looked in the plugin but can not see where I can override it.  Can you please assist?

**Comment by bwp91** [comment]
Type in a name, then a serial number, then a model, and the rest of the options will appear:
(see the bottom of the image for firmware override box)
You'll need the serial number (uuid) of the device which can be seen in the logs when the plugin starts
then set the firmware to like 999.9.9 and restart homebridge **twice**.

<img width="361" alt="Screenshot 2021-08-03 at 14 44 54" src="https://user-images.githubusercontent.com/43026681/128026235-0dc94ba4-06da-4795-bb6f-e78cb8d36426.png">

**Comment by bwp91** [comment]
The home app is showing this message in error, even when devices' firmware is up to date.

unfortunately in the plugin's current state there is no other option but to override the firmware.

**Comment by aeropink** [comment]
Thank you.  That worked.

**Comment by bwp91** [comment]
In the new version of the plugin, I have changed the manufacturer that home app gets, so the firmware update incorrect alert should be fixed.

However it will require the accessory to be removed from the homebridge cache so it is re-added.

And if you try this, don’t forget to remove the override firmware version from the config, so then it should display the correct firmware version without the update alert!

**Comment by aeropink** [comment]
Thanks.  I will check it out.
