### ISSUE TITLE
New Device: MSS560X

### ISSUE THREAD

**Issue by Ponyboy47** [donavanbecker/homebridge-meross#318]
** What I'm looking for **
Homebridge support for dimmable light switches (model MSS560X)

** Info to help accomplish it **
I have 4 of these switches. They used to be supported, but in the 6.0 upgrade support was removed. Here is a JSON blobs for one of those switches:

```json
{
  "uuid": "2005097733469125581748e1e91ba2ea",
  "onlineStatus": 1,
  "devName": "Guest Bedroom Light",
  "devIconId": "device057_us",
  "bindTime": 1603398396,
  "deviceType": "mss560x",
  "subType": "us",
  "channels": [{}],
  "region": "us",
  "fmwareVersion": "3.1.9",
  "hdwareVersion": "3.0.0",
  "userDevIcon": "",
  "iconType": 1,
  "skillNumber": "",
  "cluster": 1,
  "domain": "mqtt-us.meross.com",
  "reservedDomain": "mqtt-us.meross.com",
  "firmware": "3.1.9",
  "hbDeviceId": "2005097733469125581748e1e91ba2ea",
  "model": "MSS560X"
}
```

**Comment by bwp91** [comment]
Hi,

Can you install beta version 6.4.1-beta.0 and this model should start working again!

Removing some models was never the intention, I'm just being a bit stricter about parsing the models and relating to an appropriate homekit accessory type :)

**Comment by Ponyboy47** [comment]
The dimmable lights are now functioning with version 6.5.0. Thanks for quickly resolving the issue! I understand not intending to remove support and I must say I've been very happy since the 6.0 update. It is so much easier to set everything up now :)
