### ISSUE TITLE
MSG200 - usage of all channels

### ISSUE THREAD

**Issue by acascone** [donavanbecker/homebridge-meross#320]
* MSG200 should support multiple channels, ie doors. After trying the latest 6.5.1 beta 1, it appears that the MSG200 support hard codes channel 0, which doesn't support individual doors. Further, only one opener device appears as an accessory, thus there is no way to control individual doors.

* Problem: Multiple door support worked fine as of 5.0.3, but it appears the support for multiple doors was dropped (not carried forward).

* This specifically affects the MSG200.

* This appears to be related to #245, but it seems at that time the advice was just to run the old version. For me, I also have a MSG100 and mistakenly updated the firmware. So I need the cloud support for that device. Per #307, a number of users seem to suggest downgrading for the moment, but that seems to be stalling the inevitable. I'd like the get the MSG200 properly supported on the cloud interface for future compatibility. I'm not listing this as a bug as there exist work arounds, but this should be developed for future support.

FWIW, I have an MSG200, and helped add support for the multiple doors to the earlier version of this plugin. I would be willing to help test/prototype a working solution.

**Comment by bwp91** [comment]
Hi,

MSG100 should work both cloud and locally, with the latest firmware. The previous issues of newest firmware not working are fixed in v6 of the plugin (plugin uses the user key to generate the messageId, timestamp and key rather than using fixed values from http catcher).

MSG200, i realised that multiple channels existed from seeing logs, but never realised it could control more than one door. I assumed the other channels were never used. So wasn’t intentional to remove this aspect and should be simple to add it back. I’ll see what i can do!

**Comment by acascone** [comment]
Thanks for getting back to me! Perhaps the MSG100 issue I was having with v5.0.3 was because the salt, etc., changed with the firmware flash, and I was being lazy to not recapture the values. Sounds like user error on my end, but thanks for letting me know it should be working.

Regarding the MSG200, yes, it supports up to 3 doors. I only use 2, but nevertheless, let me know if I can help you with testing when you get a chance to look at it.

**Comment by bwp91** [comment]
@acascone could you do me a favour, update to v6.5.1-beta.3, and get me the yellow text device info output for the msg200 when the plugin loads, as well as the first poll data, the `incoming poll` log message.

Be useful to see what this data looks like...

**Comment by acascone** [comment]
While you are at it, might we easy to sneak support for the MSS550K in there. Works like the others. I tried to omit things that didn't seem necessary. Let me know if you need anything else.

Yellow Text

```
[Meross] [porch light] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"<omitted>","onlineStatus":1,"devName":"porch light","devIconId":"device042_us","bindTime":1599269352,"deviceType":"mss550k","subType":"us","channels":[{}],"region":"us","fmwareVersion":"3.1.4","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"3.1.4","hbDeviceId":"<omitted>","model":"MSS550K"}

> [8/11/2021, 6:42:55 AM] [Meross] {"uuid":"<omitted>","onlineStatus":1,"devName":"Smart Garage Door Opener","devIconId":"device061_un","bindTime":1597883592,"deviceType":"msg200","subType":"un","channels":[{},{"type":"GarageDoor","devName":"Left Garage","devIconId":"device061_un"},{"type":"GarageDoor","devName":"Right Garage","devIconId":"device061_un"},{"type":"GarageDoor","devName":"Garage Door 3","devIconId":"device061_un"}],"region":"eu","fmwareVersion":"2.1.3","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"2.1.3","hbDeviceId":"<omitted>","model":"MSG200"}
```

Incoming Poll

```
> [8/11/2021, 6:42:56 AM] [Meross] [Smart Garage Door Opener] incoming poll: {"header":{"messageId":"<omitted>","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/<omitted>/publish","timestamp":1628628177,"timestampMs":713,"sign":"<omitted>"},"payload":{"all":{"system":{"hardware":{"type":"msg200","subType":"us","version":"2.0.0","chipType":"mt7682","uuid":"<omitted>","macAddress":"<omitted>"},"firmware":{"version":"2.1.3","compileTime":"2020/04/17 11:58:10 GMT +08:00","wifiMac":"<omitted>","innerIp":"<omitted>","server":"mqtt.meross.com","port":443,"userId":<omitted>},"time":{"timestamp":1628628177,"timezone":"America/New_York","timeRule":[[1583650800,-14400,1],[1604210400,-18000,0],[1615705200,-14400,1],[1636264800,-18000,0],[1647154800,-14400,1],[1667714400,-18000,0],[1678604400,-14400,1],[1699164000,-18000,0],[1710054000,-14400,1],[1730613600,-18000,0],[1741503600,-14400,1],[1762063200,-18000,0],[1772953200,-14400,1],[1793512800,-18000,0],[1805007600,-14400,1],[1825567200,-18000,0],[1836457200,-14400,1],[1857016800,-18000,0],[1867906800,-14400,1],[1888466400,-18000,0]]},"online":{"status":1}},"digest":{"triggerx":[{"channel":1,"id":"2222222222222222","count":2},{"channel":2,"id":"3333333333333333","count":2},{"channel":3,"id":"4444444444444444","count":1}],"timerx":[{"channel":1,"id":"2222222222222222","count":1},{"channel":2,"id":"3333333333333333","count":1}],"garageDoor":[{"channel":1,"doorEnable":1,"open":0,"lmTime":1628623166},{"channel":2,"doorEnable":1,"open":0,"lmTime":1628623154},{"channel":3,"doorEnable":0,"open":1,"lmTime":0}]}}}}.
```

**Comment by bwp91** [comment]
Thanks, MSS550K should show as supported in the latest beta, 6.5.1-beta.4

Will look into the MSG200 next :)

**Comment by bwp91** [comment]
I wonder whether to base the separate garage door accessories on the `"doorEnable"` property there, seems to be `1` if the channel is used or `0` if not

**Comment by acascone** [comment]
I saw that as well. It matches my current configuration in the app, so it looks correct to me.

**Comment by bwp91** [comment]
There was another user recently who mentioned the alarm going off when the controlled via homebridge even if the setting for the alarm is off in the meross app.
have you any idea about the alarm? it doesn’t seem to appear in any of the data given to the plugin

**Comment by acascone** [comment]
I read that as well, but didn't have any personal experience since I leave the closing alarm enabled.

That said, I just tested it with my MSG100 (firmware 3.2.3), using v6.5.1-beta.4 and found that the homebridge-meross plugin appears to honoring the config from the app. ie if I turn off the alarm, and close it from Homebridge, it's silent. I re-enabled, and closed it with Homebridge and it sounds.

**Comment by bwp91** [comment]
The only thing I thought was, perhaps, with the MSG200 if channel 0 is controlled (which as you know the plugin currently does) then the alarm sounds regardless of any meross setting.

**Comment by bwp91** [comment]
@acascone dont suppose you are on the homebridge discord channel? to message in a bit more real time way.

**Comment by bwp91** [comment]
I've just pushed a new beta working towards a better solution for the MSG200. It's completely untested (I actually have a meross multi-outlet arriving today that I plan to use to somewhat test the multiple channel approach). But I thought I would push the beta already in case you wanted to have a try yourself.

**Comment by bwp91** [comment]
Plugin v6.6.0 released:

Channels for MSG200 now show as separate garage door openers in Homebridge/HomeKit. Unused/unwanted channels can be hidden via the 'Hide Channels' option in the config.
