### ISSUE TITLE
MSS120B not supported

### ISSUE THREAD

**Issue by Kartxila** [donavanbecker/homebridge-meross#322]
Smart Wifi Plug MSS120B (EU), with 2 channels, not supported

Homebridge v1.3.4 on virtual machine (VmWare)
Plugin: homebridge-meross v6.5.0

Model: Smart Wifi Plug (EU) - MSS120B

Logs:
> [Meross] [Prises bureau] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2009144178231490830448e1e933a8ec","onlineStatus":1,"devName":"Prises bureau","devIconId":"device064_eu","bindTime":1610639105,"deviceType":"mss120b","subType":"eu","channels":[{},{"type":"Switch","devName":"Guirlande","devIconId":"device001"},{"type":"Switch","devName":"Radiateur","devIconId":"device001"}],"region":"eu","fmwareVersion":"4.1.4","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.4","hbDeviceId":"2009144178231490830448e1e933a8ec","model":"MSS120B"}

**Comment by bwp91** [comment]
Hi,

Can you update to beta version 6.5.1-beta.2? This device should then show up in homekit as 3 switches, an 'all on/off' switch and other two switches to control each channel.

I have also made a change so the plugin uses the channel names configured from meross app... so... hopefully... the 'all on/off' switch's name is `Prises bureau` and the two channel accessories should be called `Guirlande` and `Radiateur` in HomeKit. Would you be able to confirm that this is how they are named?

Thanks

**Comment by Kartxila** [comment]
Hi,

I've just updated to 6.5.1-beta.3 (you're working hard I guess) and all is fine, the accessories names are well set in Homebridge. 

Besides, the names defined in Meross app for device MSS425F are not set in homebridge, it's just SW1 to SW5, it would be great on future version ;)

Thanks for your work

**Comment by bwp91** [comment]
do you have the MSS425F setup as cloud or local device?

**Comment by Kartxila** [comment]
Only on cloud, nothing in local

**Comment by bwp91** [comment]
Did the plugin get the channel names correct for the MSS120B?

**Comment by Kartxila** [comment]
Yes, that's why I told you about MSS425F, because it's really pleasant the names configured in native Meross app propagate to Home ;)

**Comment by bwp91** [comment]
Can you turn on plugin debug logging, or indeed debug logging just for your MSS425.

Also update to beta version 6.5.1-beta.8.

Restart the plugin, then in the homebridge log when the accessory initialises you'll see a message like:

```
[11/08/2021, 17:27:34] [Meross] [Device Name] json debug info: {"uuid":"2012%%%","onlineStatus":1,"devName":"Device Name","devIconId":"device032_uk","bindTime":1628680397,"deviceType":"mss420f","subType":"uk","channels":[{},{"type":"Switch","devName":"TV","devIconId":" device001"},{"type":"Switch","devName":"Apple TV","devIconId":" device001"},{"type":"Switch","devName":"Switch 3","devIconId":" device001"},{"type":"Switch","devName":"Switch 4","devIconId":" device001"}],"region":"eu","fmwareVersion":"3.1.1","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"3.1.1","hbDeviceId":"2012%%%%","model":"MSS420F"}.
```

remove some characters from the uuid if you want.

could you get me this line from yours? It will help to determine why for this model it doesn't seem to be picking up the channel names

**Comment by Kartxila** [comment]
Here is the log, you can see the names in it (USB, Température, Brumisateur, etc.)

>[11/08/2021, 18:41:17] [Meross] [Terrarium] json debug info: {"uuid":"<UUID>","onlineStatus":1,"devName":"USB","devIconId":"device020_fr","bindTime":1613842399,"deviceType":"mss425f","subType":"fr","channels":[{},{"type":"Switch","devName":"Lumière","devIconId":"device001"},{"type":"Switch","devName":"Température","devIconId":"device001"},{"type":"Switch","devName":"Brumisateur","devIconId":"device001"},{"type":"Switch","devName":"Switch 4","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"eu","fmwareVersion":"3.1.2","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"3.1.2","hbDeviceId":"20102021823471290d0648e1e9364d135","model":"MSS425F"}.

**Comment by Kartxila** [comment]
I can't find out how to insert some text as you did with your log example :/

**Comment by bwp91** [comment]
> I can't find out how to insert some text as you did with your log example :/

Three backticks \`\`\` on a line before the code and then three \`\`\` again on the line after :)

**Comment by Kartxila** [comment]
Thanks :D

```
Yeah !
```

**Comment by bwp91** [comment]
I realise what has happened. The accessory was added to Homebridge before I made the change to the plugin to pull the channel names from the meross info.

You will need to use the 'Hide from Homekit' option to remove the accessories from homebridge (see https://github.com/bwp91/homebridge-meross/issues/323#issuecomment-896606573)

Restart the plugin so all the accessories are removed, then untick the box again, restart, and the accessories will be re-added to homebridge with the correct names.

The plugin only takes the channel names at the point of being added to Homebridge.

**Comment by Kartxila** [comment]
Ok, it's not important enough to do that. Removing this kind of device is quite anoying in Homekit, I've to reassign each device to the room, change the fav and state (not sure for the english word) config, for 6 switches by device (i got three of them), so... I'll do it another day, but thank you for your time ;)
