### ISSUE TITLE
How to hide a device already showing in Home app as native HomeKit

### ISSUE THREAD

**Issue by Fookes74** [donavanbecker/homebridge-meross#323]
Hi

3 of my 4 devices need to use this plugin. The other device is native HomeKit. As a result this device is discovered by this plugin also and is shown twice in the Home app. 

Am I missing a setting somewhere in the plugin which hides individual devices? I tried the trash can symbol when I'd selected the device under the Devices tab but that deleted all of them. Sure I'm missing something obvious but I'm not seeing it at the moment! 
Thanks

**Comment by bwp91** [comment]
Hi,

You can put the serial number into one of the config sections appropriate to the device, then a 'Hide from HomeKit' option will appear, tick this, restart, and the device will be removed and ignored in the future:

<img width="504" alt="Screenshot 2021-08-11 at 09 10 39" src="https://user-images.githubusercontent.com/43026681/128994071-d812f8c2-21dd-422c-8d58-7c025b44e3f5.png">

**Comment by Fookes74** [comment]
Thank you. Very kind.

I have noticed though that one of my non-homekit plugs is offline if I set it to local rather than cloud. Tried it twice inc uninstalling plugin and reinstalling. It still does it. It’s an identical plug to the other two which work fine set to local. It just appears as offline. 

Any thoughts on potential reasons for that? All are configured identically. 

Thanks

Chris

**Comment by bwp91** [comment]
Are there any clues in the logs as to why it shows as offline? Which model is it?

**Comment by Fookes74** [comment]
Hi, apologies for delay in replying. In the logs it’s saying this:

192.168.1.66:80 failed to request status as connect ECONNREFUSED 192.168.1.66:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16).

Make any sense?

**Comment by bwp91** [comment]
This is definitely the IP for the device you have configured as local in the plugin? You haven't mistaken the IP for one of the other meross outlets?

**Comment by bwp91** [comment]
which meross model is this?

**Comment by Fookes74** [comment]
Yes, definitely the correct IP (which is static, btw). 
All of the non-HomeKit plugs are MS310 - the others are working fine so I know it’s not the plug. The problem one works fine when set to cloud - it’d just local control where it doesn’t work at all.

**Comment by bwp91** [comment]
So the others work correctly in local mode?

Also, they are all linked to the same meross account? `ECONNREFUSED` could be from using the wrong meross credentials for a device linked to a different account.

I'm just trying to discount any possible scenarios!

**Comment by Fookes74** [comment]
Yep, the other two worked in local mode. I’ve temporarily taken all three out to cloud mode. All Meross are under the same account, under the same app.

**Comment by Fookes74** [comment]
Just an update. I have no idea why but uninstalling the plugin, re-adding and then adding the problem plug has got it working again. No idea why. I've configured it exactly as before. Will update if any other issues but solid so far. Thanks for all of your help.

**Comment by bwp91** [comment]
Strange! but good! I don’t know what could have happened, but glad it’s sorted!
