### ISSUE TITLE
Switching to cloud access: timeout

### ISSUE THREAD

**Issue by ituri** [donavanbecker/homebridge-meross#324]
Hi,

I'm running the latest Homebridge ui-x (1.3.4) together with the latest version of homebeirdge-meross (6.5.0). In my config, I've added a MSG100 which I can access without any problems as long as I access it via its IP address. 
I would however like to switch from accessing it locally to accessing it via the cloud. I have added the (correct 😉 ) user credentials as described [here](https://github.com/bwp91/homebridge-meross/wiki/Configuration), but I keep seeing these errors in my homebridge log:

```
[8/11/2021, 2:15:58 PM] [Meross] [Garagentor] failed to request status as timeout of 4000ms exceeded at createError (/usr/lib/node_modules/homebridge-meross/node_modules/axios/lib/core/createError.js:16:15).
[8/11/2021, 2:15:58 PM] [Meross] [Garagentor] has been reported [offline].
[8/11/2021, 2:15:59 PM] [Meross] [Garagentor] failed to request status as socket hang up at connResetException (internal/errors.js:628:14).
```

Any ideas what might be causing these issues?

ituri

**Comment by bwp91** [comment]
Hi, are you removing the IP for the device from the configuration? The plugin will use local mode for a device if the IP is there, even if credentials are configured.

**Comment by bwp91** [comment]
The warnings in the log suggest the plugin is still trying to use local mode for the device

**Comment by ituri** [comment]
That's it! I left the old (local) configuration in my homebridge config, since I wanted to try it out first. Once I removed it, I got rid of the error messages and my garage door is working as expected.

Maybe there should be a note in the wiki that clarifies that you can only have one of the two configuration types in your config?

**Comment by bwp91** [comment]
> Maybe there should be a note in the wiki that clarifies that you can only have one of the two configuration types in your config?

Do you mean like per device can either be cloud or local?

I eventually plan to find a way of making them work together. When the plugin has access to the cloud, it provides the IP of the device, so local control would be possible. In one of my other plugins I have it where any command will try to be sent locally first, and if that fails it will revert to cloud.

This way you can get the best of both worlds, like, the real time updates from the cloud but if the cloud then goes down then the device will still work being controlled locally.

**Comment by ituri** [comment]
I originally meant that you should warn users that they shouldn't add both local and cloud devices as it will result in the errors I experienced.
But now that I read your response I think that finding a way to make them both work together seems even better. 😊  

Thanks again for the continuous development of this plugin! It's great to see that I can now install official updates on the MSG100 and still be able to use it with homebridge!

**Comment by bwp91** [comment]
If two entries are placed into the config with the same serial number, the plugin should just use the first, and a warning should appear in the log when the plugin is initialised that there is a duplicate entry

**Comment by bwp91** [comment]
You can install the new beta 6.5.1-beta.9, and try out the 'Hybrid Mode' (Optional Settings)

With this on, a cloud device will be controlled locally by the plugin when meross provides the plugin with the local IP address
