### ISSUE TITLE
MSL120J is not supported

### ISSUE THREAD

**Issue by larsmehrtensef21** [donavanbecker/homebridge-meross#326]
Smart Bulb Not Supported

Setup: Homebridge running on Raspbian

Homebridge v.1.3.4

HB-Meross v 6.6.0

Model: MSL120J Meross Smart Bulb

Logs:
{"uuid":"20101916129750290d0448e1e9361068","onlineStatus":1,"devName":"Balkon Lampe","devIconId":"device036","bindTime":1625593356,"deviceType":"msl120j","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"3.1.4","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"3.1.4","hbDeviceId":"20101916129750290d0448e1e9361068","model":"MSL120J"}

**Comment by bwp91** [comment]
Hi @larsmehrtensef21 

Please update to beta version 6.6.1-beta.1 that I have just published.

This should get this model to work :)

**Comment by larsmehrtensef21** [comment]
@bwp91 great job, you enabled me to turn off my balcony light again so I can go to bed now... and it works even better than it did with version 5.x. Cheers! :-)
