### ISSUE TITLE
Hoobs Issue Cannot read "LastActivation"

### ISSUE THREAD

**Issue by nickm104** [donavanbecker/homebridge-meross#329]
### What issue do you have? Please be as thorough and explicit as possible.
I am trying to install and setup MSG100 on Hoobs and I keep getting the following error:
Meross BridgeMerossWARNING[Gate] could not be initialised as Cannot read property 'LastActivation' of undefined at new deviceGarageSingle (/var/lib/hoobs/merossbridge/node_modules/homebridge-meross/lib/device/garage-single.js:48:55).

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Running HOOBS

* Which version of Homebridge/HOOBS do you have?
HOOBS v 4.0.100

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
6.7.0.

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSG100

### Please paste any relevant logs below.

```
8/16/2021, 10:13:32 PMMeross Bridge starting
8/16/2021, 10:13:33 PMMeross BridgeInitializing HAP-NodeJS v0.9.4...
8/16/2021, 10:13:34 PMMeross BridgeLoaded plugin 'homebridge-meross'
8/16/2021, 10:13:34 PMMeross BridgeRegistering platform 'homebridge-meross.Meross'
8/16/2021, 10:13:34 PMMeross BridgeLoading 1 platforms...
8/16/2021, 10:13:34 PMMeross BridgeMerossInitialising plugin v6.7.0 | Node v14.17.5 | HB v1.3.4 | HOOBS v4...
8/16/2021, 10:13:34 PMMeross BridgeMerossWARNINGConfig entry [cloudRefreshRate] is set too low so increasing to 30.
8/16/2021, 10:13:34 PMMeross BridgeMerossPlugin initialised. Setting up accessories....
8/16/2021, 10:13:34 PMMeross BridgePreparing Advertiser for 'Meross Bridge 5FA2' using bonjour-hap backend!
8/16/2021, 10:13:34 PMMeross BridgeStarting to advertise 'Meross Bridge 5FA2' using bonjour-hap backend!
8/16/2021, 10:13:34 PMMeross BridgeBridge is running on port 51846.
8/16/2021, 10:13:35 PMMeross BridgeMerossWARNING[Gate] could not be initialised as Cannot read property 'LastActivation' of undefined at new deviceGarageSingle (/var/lib/hoobs/merossbridge/node_modules/homebridge-meross/lib/device/garage-single.js:48:55).
8/16/2021, 10:13:35 PMMeross BridgeMeross✓ Setup complete.
```

**Comment by nickm104** [comment]
UPDATE...
I installed an earlier version (6.6.0) and was able to get the opener to add, however I keep getting this error on 6.6.0

```
8/16/2021, 11:19:59 PMMeross BridgeMerossWARNING[Gate] mqtt connection closed.
8/16/2021, 11:20:04 PMMeross BridgeMerossWARNING[Gate] mqtt connection reconnecting.
```

**Comment by bwp91** [comment]
Hi @nickmeche 
Can you update to v6.7.1 when it appears available in HOOBS? This should fix the original error you were receiving.

With regards to

```
8/16/2021, 11:19:59 PMMeross BridgeMerossWARNING[Gate] mqtt connection closed.
8/16/2021, 11:20:04 PMMeross BridgeMerossWARNING[Gate] mqtt connection reconnecting.
```

This can sometimes happen when (even accidentally) running the plugin in two places with the same meross credentials... could this be what's happening in your case?

**Comment by nickm104** [comment]
> Can you update to v6.7.1 when it appears available in HOOBS? This should fix the original error you were receiving.

Yes. This fixed the issue. Thank you!

> With regards to
> 
> ```
> 8/16/2021, 11:19:59 PMMeross BridgeMerossWARNING[Gate] mqtt connection closed.
> 8/16/2021, 11:20:04 PMMeross BridgeMerossWARNING[Gate] mqtt connection reconnecting.
> ```
> 
> This can sometimes happen when (even accidentally) running the plugin in two places with the same meross credentials... could this be what's happening in your case?

Yep. That's exactly what happened. I was transitioning from one installation to another, but setup everything manually. I forgot to turn off the old install. Turned it off waited a few mins and that error went away. 

Thanks for the help!

**Comment by bwp91** [comment]
Fab. I almost didn’t mention the running the plugin in two places case because i thought it was so specific and the chances were minimal 🤣 so i’m glad i did.

I don’t suppose you use the Eve homekit app?

**Comment by nickm104** [comment]
Haha. I'm glad you did too, I'm not sure I would have ever figured that one out. 

I just started with homekit and homebride about a month or so ago, so I've just been using the homekit app.
