### ISSUE TITLE
Meross plug mss210rtl problem

### ISSUE THREAD

**Issue by imeSven** [donavanbecker/homebridge-meross#333]
### What issue do you have? Please be as thorough and explicit as possible.

meross plug not wqorking

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

use homebridge ui-x

* Which version of Homebridge/HOOBS do you have?

lastest

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

docker /synology

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

lastest

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

smart plug

### Please paste any relevant logs below.

[8/24/2021, 2:53:36 PM] [Meross] [Smart Plug] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2103175540653051855148e1e963c317","onlineStatus":1,"devName":"Smart Plug","devIconId":"device024","bindTime":1629805992,"deviceType":"mss210rtl","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.1.12","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.12","hbDeviceId":"2103175540653051855148e1e963c317","model":"MSS210RTL"}
[8/24/2021, 2:53:36 PM] [Meross] ✓ Setup complete.

**Comment by bwp91** [comment]
Hi @imeSven 

Can you install beta version of the plugin, 6.8.1-beta.2. Instructions here:
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Once installed and plugin restarted, this device should appear in your Homebridge!

**Comment by bwp91** [comment]
Should be working in v6.9.0!

**Comment by imeSven** [comment]
Yep. Works now! Tyou so much 

One more thing
..How can I make it appear as a plug not a switch?

**Comment by bwp91** [comment]
> Yep. Works now! Tyou so much
> 
> One more thing
> ..How can I make it appear as a plug not a switch?

In the plugin settings, create an entry for the device in "Single Channel Devices" section. Use the "Show As" option to change from switch to outlet, then restart the plugin.

It will then appear as an outlet in homekit!
