### ISSUE TITLE
Fails to update (MacOS 11.4)

### ISSUE THREAD

**Issue by kornfeldavid** [donavanbecker/homebridge-meross#335]
### What issue do you have? Please be as thorough and explicit as possible.
Hi there! I tried to update to your most recent version and received this error message:

USER: David
DIR: /usr/local
CMD: npm install -g homebridge-meross@latest

execvp(3) failed.: No such file or directory

Command failed. Please review log for details.

### Details of your setup.
I use the latest version of Homebridge UI-X (v1.3.4) on a Mac running MacOS 11.4. Meross Plugin version is 6.7.2.

I have Debug Logging selected but no further information was shown in the log.

Thank yoU!
David

**Comment by bwp91** [comment]
Hi @kornfeldavid 

This isn’t actually an issue with the plugin, seems more like an issue with node/npm.

One user had the same issue here:

https://www.reddit.com/r/homebridge/comments/pa9610/cannot_update_plugins_cannot_install_new_plugins

I would recommend reinstalling node, which version of node do you currently have? Do you routinely update your node using `hb-service`?

**Comment by kornfeldavid** [comment]
Thanks for the speedy reply!

I just updated node to the latest version but maybe it didn't work properly? Will check out this other case, thanks!

**Comment by bwp91** [comment]
Hey did you get this sorted?
