### ISSUE TITLE
Smart surge protector mss425e is HomeKit native but still shows up when homekit native devices are being ignored

### ISSUE THREAD

**Issue by ColinScattergood** [donavanbecker/homebridge-meross#337]
### What issue do you have? Please be as thorough and explicit as possible.

MSS425 shows up regardless of setting to ignore the HomeKit native devices.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?

HOOBS 4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 3b+

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
6.9.1 

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSS425e, hardware version 4.0.0, firmware version 4.1.6

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @ColinScattergood 

This feature is a work-in-progress, and I am adding new models with their homekit-native hardware versions as they are reported just like this!

Please use the HOOBS UI to install beta version 6.9.2-beta.0, HOOBS will restart the bridge and you should find your MSS425E is then removed from HOOBS.

Thanks!

**Comment by ColinScattergood** [comment]
> Hi @ColinScattergood
> 
> This feature is a work-in-progress, and I am adding new models with their homekit-native hardware versions as they are reported just like this!
> 
> Please use the HOOBS UI to install beta version 6.9.2-beta.0, HOOBS will restart the bridge and you should find your MSS425E is then removed from HOOBS.
> 
> Thanks!

Awesome, thanks! Knew it was a WIP based on that other thread, but didn't want to reopen that one...Seemed like this was how you wanted to devices reported. Updating now!

**Comment by ColinScattergood** [comment]
Worked like a charm!! Thanks as always!
