### ISSUE TITLE
MSG200 Garage door opener

### ISSUE THREAD

**Issue by xsaito** [donavanbecker/homebridge-meross#338]
### What issue do you have? Please be as thorough and explicit as possible.
Hoobs crashing each time I'm closing the doors.

I'm using (3) HOOBS on Raspberry PI connected via local wifi to my MSG200
Hoobs: 4.0.100, Node 14.17.5
Local setup, no user/password, just the key)
Plugin version 6.9.1 (didn't use previous versions)

Checked the logs no errors, it's just crashes and the bridge restarting.

**Comment by bwp91** [comment]
Hi @xsaito 

Please can you use the plugin settings to turn debug mode on, then close the garage door to make the bridge crash, and obtain all the logs that appear and paste them here? This will help me see at which point it is crashing even though there are no errors.

Thanks

**Comment by alexc-checkmarx** [comment]
8/30/2021, 10:59:40 AMMeross BridgeMeross[Garage Door Opener SW1] has been reported [online].
8/30/2021, 10:59:40 AMMeross BridgeMeross[Garage Door Opener] has been reported [online].
8/30/2021, 10:59:45 AMMeross BridgeMeross[Garage Door Opener] sending update: {"header":{"from":"http://192.168.0.59/config","messageId":"7am73wzzjm2rrbl3","method"{hidden}
8/30/2021, 10:59:45 AMMeross BridgeMeross[Garage Door Opener] incoming poll: {"header":{"messageId":"7am73wzzjm2rrbl3","namespace":"Appliance.System.All","triggerSrc":{hidden}
8/30/2021, 10:59:49 AMMeross BridgeMeross[Garage Door Opener] sending update: {"header":{"from":"http://192.168.0.59/config","messageId":"iwye2anmmu82ce2m","method":"SET",{hidden}
8/30/2021, 10:59:49 AMMeross BridgeMeross[Garage Door Opener SW1] current target [closed].
8/30/2021, 10:59:49 AMMeross BridgeMeross[Garage Door Opener SW1] current state [closing].
8/30/2021, 10:59:49 AMMeross BridgeMeross[Garage Door Opener] sending update: {"header":{"from":"http://192.168.0.59/config","messageId":"b89cwxymvkhnb86r","method":"SET",{hidden}
8/30/2021, 10:59:49 AMMeross BridgeMeross[Garage Door Opener SW1] current target [open].
8/30/2021, 10:59:49 AMMeross BridgeMeross[Garage Door Opener SW1] current state [opening].
8/30/2021, 10:59:50 AMMeross BridgeMeross[Garage Door Opener] sending update: {"header":{"from":"http://192.168.0.59/config","messageId":"nzr6luh31ynb4e9e","method":"GET",{hidden}
8/30/2021, 10:59:50 AMMeross BridgeMeross[Garage Door Opener] incoming poll: {"header":{"messageId":"nzr6luh31ynb4e9e","namespace":"Appliance.System.All","triggerSrc":"iOSLocal","method":"GETACK",{hidden}
8/30/2021, 11:00:01 AMMeross Bridge starting
8/30/2021, 11:00:07 AMMeross BridgeLoaded plugin 'homebridge-meross'
8/30/2021, 11:00:07 AMMeross BridgeLoading 1 platforms...
8/30/2021, 11:00:07 AMMeross BridgeMerossInitialising plugin v6.9.1-beta.1 | Node v14.17.5 | HB v1.3.4 | HOOBS v4...
8/30/2021, 11:00:07 AMMeross BridgeMerossPlugin initialised. Setting up accessories....
8/30/2021, 11:00:07 AMMeross BridgeMerossWARNINGDisabling cloud client as username and password not supplied in config.
8/30/2021, 11:00:07 AMMeross BridgeMeross[Garage Door Opener SW1] FS storage: addWriter().
8/30/2021, 11:00:07 AMMeross BridgeMerossFG history: loading.
8/30/2021, 11:00:07 AMMeross BridgeMerossFG storage: read file [/var/lib/hoobs/merossbridge/persist/hoobs_meross_Garage Door Opener SW1_persist.json].
8/30/2021, 11:00:07 AMMeross BridgeMeross[Garage Door Opener SW1] FG timer: new subscription.
8/30/2021, 11:00:07 AMMeross BridgeMeross[Garage Door Opener SW1] FG history: registering events.
8/30/2021, 11:00:07 AMMeross BridgeMeross[Garage Door Opener SW1] initialising with options {"connection":"local","garageDoorOpeningTime":5,"hideChannels":"2,3","logging":"debug"}.
8/30/2021, 11:00:07 AMMeross BridgeMeross[Garage Door Opener] initialised with id [{hidden}].
8/30/2021, 11:00:07 AMMeross BridgeMeross[Garage Door Opener] json debug info: {"name":"Garage Door Opener","serialNumber":"{hidden}","deviceUrl":"192.168.0.59","model":"MSG200","hideChannels":"2,3","garageDoorOpeningTime":5,"overrideLogging":"default","firmwareRevision":"2.1.3","uuid":"{hidden}","deviceType":"MSG200","devName":"Garage Door Opener SW3","channels":[{},{},{},{}],"firmware":"2.1.3","hbDeviceId":"{hidden}"}.
8/30/2021, 11:00:07 AMMeross BridgeMeross✓ Setup complete.
8/30/2021, 11:00:07 AMMeross BridgeBridge is running on port 51826.

**Comment by alexc-checkmarx** [comment]
btw, I've tried all latest versions, including beta, even put my login info for cloud service, still fails

**Comment by bwp91** [comment]
Can you try 6.9.2-beta.1?

The lack of errors in the log doesn't help! I've re-looked at the code and managed to spot a potential issue - can you update to this beta to see if it has fixed anything?

**Comment by alexc-checkmarx** [comment]
Fixed!

**Comment by xsaito** [comment]
Fixed! It was a great spot, great job! :)

**Comment by bwp91** [comment]
That’s a relief! Just released v6.9.2 which includes the fix!
