### ISSUE TITLE
MSS110RTL not supported

### ISSUE THREAD

**Issue by Kannebecker** [donavanbecker/homebridge-meross#339]
[8/31/2021, 3:35:34 PM] [Meross] [Windows RDP] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2103293980508651855348e1e96809a6","onlineStatus":1,"devName":"Windows RDP","devIconId":"device001_eu","bindTime":1623418705,"deviceType":"mss110rtl","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"4.1.14","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.14","hbDeviceId":"2103293980508651855348e1e96809a6","model":"MSS110RTL"}

**Comment by bwp91** [comment]
Hi @Kannebecker 

If you install the beta version of the plugin, currently v6.9.3-beta.0, this device should start working!

Thanks

**Comment by Kannebecker** [comment]
Thank you,
I have no idea how to install the beta package :)
have homebridge running in docker.

**Comment by bwp91** [comment]
You can update through the UI or there’s also specific commands for docker, see

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

let me know how you get on!

**Comment by Kannebecker** [comment]
Yes it works !!!

Thank You !
