### ISSUE TITLE
Works Great - Doesn't Hide HomeKit Native

### ISSUE THREAD

**Issue by patrickoleary1977** [donavanbecker/homebridge-meross#340]
Using HomeKit on macOS.

I have a variety of Meross devices.  All HomeKit native.  I added one device that is not, and want to use Homebridge to show it.  The problem is that Homebridge is showing all devices, even HomeKit native.  I have the Ignore box checked.  Outside of that, is there anything I can do?

**Comment by bwp91** [comment]
Hi @patrickoleary1977 

The ignore homekit native feature is still a work in progress. 

Could you provide me with a list of models that you own along with their hardware versions?

This info is available to see in the homebridge-ui, in the “My Devices” tab.

Thanks

**Comment by patrickoleary1977** [comment]
Thanks for the response.

I have:
- A number of plugs MSS110 that are Hardware version 7.00
- A few MSS120B with hardware version 4.00
- An outdoor plug MSS620 with hardware version 4.00
- A MSL430 night light with hardware version 4.00
- I also have a desk lamp but it doesnt show up in the plugin at all.

Thanks,
Patrick

**Comment by bwp91** [comment]
Are all these homekit native model versions?

With regards to the desk lamp, there should be a log message when the plugin starts explaining why it isn’t being added - most likely a model that I haven’t added to the plugin yet.

**Comment by patrickoleary1977** [comment]
Yes, everything is HomeKit native.  I have the Meross Diffuser as well, which is not HomeKit native and the reason for me using my Homebridge.  

I get these warnings:
The plugin "homebridge-meross" requires Node.js version of ^14.17.5 || ^16.8.0 which does not satisfy the current Node.js version of v14.17.4. You may need to upgrade your installation of Node.js - see https://git.io/JTKEF

This is the lamp log:
[Smart Desk Lamp] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2103197631390390846648e1e96609b7","onlineStatus":1,"devName":"Smart Desk Lamp","devIconId":"device_mdl110m_un","bindTime":1630544493,"deviceType":"mdl110m","subType":"un","channels":[{}],"region":"us","fmwareVersion":"4.2.1","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.2.1","hbDeviceId":"2103197631390390846648e1e96609b7","model":"MDL110M"}

I also just tried to update my node.js.  It went from 14.17.4 to 14.17.6.  It won't update to 16.

**Comment by bwp91** [comment]
Node 14.17.6 is perfect. You don't need node 16 (not supported by homebridge yet).

Can you use these instructions to update the plugin to beta version 6.9.3-beta.1?
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version#homebridge-ui

This should remove all the homekit native devices from homebridge.

I have also added support for the MDL110M device, it will appear in homebridge now but may or may not work depending on whether I have the data structures right for what it expects. This appears to be a lamp that supports colour temperature? Not a diffuser like you mentioned?

Thanks

**Comment by patrickoleary1977** [comment]
I will test it now.  

I might not have been clear.  The diffuser works perfectly.  My only issues were that HomeKit native devices were not being ignored, and the desk lamp not being added.

**Comment by bwp91** [comment]
Ah I misunderstood!

The desk lamp will now appear, let me know what it shows for the hardware version and I can then get the plugin to ignore this device too!

**Comment by patrickoleary1977** [comment]
I installed the beta.  

- The Diffuser is being picked up correctly.
- No native HomeKit devices are being shown in My Devices
- The native HomeKit devices are not showing in HomeKit (yay)
- The Smart Desk Lamp is showing in Homebridge -- however it should not as it is a HomeKit native device

**Comment by patrickoleary1977** [comment]
The lamp is MDL110M and hardware version 4.0.0.

**Comment by bwp91** [comment]
If you update again to beta version 6.9.3-beta.2, then this should hide the desk lamp too :)

**Comment by patrickoleary1977** [comment]
Yep, works perfect!  Thank you!  This plugin is awesome.  Nice work!
