### ISSUE TITLE
MTS100 Implementation

### ISSUE THREAD

**Issue by bwp91** [donavanbecker/homebridge-meross#342]
@cossyg @Tongo91

Will move discussion of implementing the MTS100 to this issue.

It would help me initially to see a couple of screenshots from the meross app to see how this device is controlled and what options are available... is one of you able to do this?

Thanks

**Comment by Tongo91** [comment]
![image](https://user-images.githubusercontent.com/90055492/132235485-4daecd51-e98a-4980-9eb8-a59148575c8f.png)

**Comment by Tongo91** [comment]
Hey thank you for the fast response and your work! I will help you as good as possible and can provide you every screenshot you need.

It's possible to set the temperature directly to a static value or set some pre-settings. It's also possible via the "automatic" mode to let it use a configured schedule 


EDIT: The most important functions should be: 
- changing temperature
- switch between manual and automatic mode
- turn on/off 

I personally do not use the presets very often but they could be helpful as well to switch fast between those three configured temperatures (like for automations in Homekit if everyone leaves the house to set it to a lower temperature)

![image](https://user-images.githubusercontent.com/90055492/132235687-2a60c272-efb7-49fa-a7ee-f04f1082fcef.png)
![image](https://user-images.githubusercontent.com/90055492/132235718-f27058c4-afa1-4c7a-bec8-de4508ffa200.png)

**Comment by bwp91** [comment]
@Tongo91 are you on the homebridge discord server? could we message on there? the invite link is on the “new issue” page on here
