### ISSUE TITLE
Meross Devices "incorrectly" Reported Offline

### ISSUE THREAD

**Issue by SemoTech** [donavanbecker/homebridge-meross#343]
### What issue do you have? Please be as thorough and explicit as possible.
Upon initializing homebridge and loading the Meross plugin, several (non-homekit hardware 3.0.0) Meross 1Way and 3Way wall switches are flagged as off-line by the plugin.  
Even tho they are NOT showing as "no response", attempting to use them in Homekit fails (they appear to turn on for a sec, there is a small spinning circle, and then they show as off again). However, they can be controlled just fine ON/OFF from the Meross App!  See logs...

Why is the Meross App not having any issues and is able to communicate with them, but the Meross Plugin cannot?

Thank you.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge:  v1.3.4
NPM:  v7.22.0
Node.Js:  v14.17.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi - Raspbian GNU/Linux Buster (10)

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
homebridge-meross: v6.10.0
Unsure if this started with this version or before.

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSS510x   &   MSS550x
Both Hardware v3.0.0
All show as "controllable" in both HomeKit and the Meross App, but only the Meross App can control them...

### Please paste any relevant logs below.

```
[06/09/2021, 09:02:10] [Meross] [Office Sconces Switch] has been reported [offline].
[06/09/2021, 09:02:10] [Meross] [MBR Sconce Switch] has been reported [offline].
[06/09/2021, 09:02:11] [Meross] [Downstairs Hallway Light] has been reported [offline].
[06/09/2021, 09:02:11] [Meross] [Entrance Ceiling Lights] has been reported [offline].
[06/09/2021, 09:02:12] [Meross] [Backyard Right Sconce Switch] has been reported [offline].
[06/09/2021, 09:02:12] [Meross] [MBA Exhaust Vent Switch] has been reported [offline].

[06/09/2021, 09:03:29] [Meross] [Office Sconces Switch] current state [on].  <<= Activated OK in Meross App
[06/09/2021, 09:03:30] [Meross] [Office Sconces Switch] current state [off]. <<= Deactivated OK in Meross App

[06/09/2021, 09:03:50] [Meross] [Office Sconces Switch] sending update failed as the request timed out.   <<= Homekit control failed
[06/09/2021, 09:04:02] [Meross] [Office Sconces Switch] sending update failed as the request timed out.   <<= Homekit control failed
```

**Comment by bwp91** [comment]
In the plugin settings screen in "my devices" you can see the IP reported for each device. Is it reporting the correct IP? In your network, does your homebridge instance have "network access" to the devices?

**Comment by SemoTech** [comment]
Hi Ben, 

1 - Yes, both the IP addresses and MAC addresses match both in the router and in the Meross App. 
2 - Yes, the Homebridge has the same direct access to ALL devices its plugins control.

The "offline" report is not consistent either.  Some days some of them show online and some days offline, some days all show online and some only 1 or 2 show offline, but they are all always controllable and reachable in the Meross App.  

Seems there is some inconsistency with how the cloud info is read/reported and passed on to HomeKit.

**Comment by bwp91** [comment]
Are these switches setup for cloud control or local control?

and is your hybrid mode setting enabled?

does controlling these devices normally work from the home app?

The plugin bases the online/offline status on the data received from polling. It will also mark as offline if the polling fails with a timeout error (this is usually due to an accessory being disconnected from network). it would be useful to see the polling debug logs for a device in the moment that it is marked as offline by the plugin to find the exact reason why it's marking as offline.

**Comment by SemoTech** [comment]
Hi Ben,  by default the "Hybrid Mode" was not enabled, but I have enabled it now and am re-testing... 
After the 1st HB restart following enabling "Hybrid Mode" all devices are showing as [online].  I'll keep monitoring...
For reference, the "Cloud Refresh Rate" is set to 0 and "Local Refresh Rate" is set to 5. If that should be changed, please advise.

**Comment by bwp91** [comment]
Hybrid mode will use the IP address of the device provided by meross to control the device locally. But also allows for instant notifications via the cloud if the device is controlled externally. Kinda the best of both worlds between cloud and local control.

Your refresh rates are fine. With hybrid mode, the plugin will use the 'cloud refresh rate'... in your case as you have this set to 0, the plugin will poll every 5 minutes basically to make sure the IP has stayed the same, and to make sure if any instant notifications haven't arrived then the homekit status still stays updated.

**Comment by SemoTech** [comment]
Sounds great Ben, good to know, and for now "hybrid mode" seems to be working nicely, with all Meross devices showing [online] and controllable from both the Meross App and HomeKit. Thank you.  
Should "hybrid mode" not be turned on by default?

**Comment by bwp91** [comment]
I eventually plan to make this the default. But it would be a breaking change, so would need to be part of v7 of the plugin. And i’m not ready to bump to v7 yet as it’s so soon after v6!

This mode would not work for users who have devices in a remote location not on the same network as the homebridge instance. So at the moment it’s there for testing for a little while!

**Comment by SemoTech** [comment]
Got it Ben, so if you plan to manage LAN devices and the HomeBridge is on the LAN or a VLAN where it has access to it works best with "hybrid mode" enabled.  Thanks.

**Comment by bwp91** [comment]
Yes, i think this is would be the situation for most people.

But it’s still a potentially breaking change for users who control remote devices, hence the need for a major version bump!

It’s my first plan for v7 of the plugin!

**Comment by SemoTech** [comment]
Sounds great Ben, looking forward to it, keep up the awesome work!
