### ISSUE TITLE
MSS620BR not showing from cloud account

### ISSUE THREAD

**Issue by ddasal** [donavanbecker/homebridge-meross#344]
### What issue do you have? Please be as thorough and explicit as possible.

I have linked my cloud account and only one device is being found. My mss620br isn’t showing up I side hoobs, but I can see and control it in the Meross iOS app just fine.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

4.0.100

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi
14.17.6

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

The issue has been on every version I’ve tried. 
currently on the latest 6.10.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSS620BR 

### Please paste any relevant logs below.

```
9/6/2021, 1:23:43 PMHOOBSMerossPlugin initialised. Setting up accessories....
9/6/2021, 1:23:43 PMHOOBSBridge is running on port 51826.
9/6/2021, 1:23:43 PMHOOBSMeross[Rachel’s Curling Iron] FS storage: addWriter().
9/6/2021, 1:23:43 PMHOOBSMerossFG history: loading.
9/6/2021, 1:23:43 PMHOOBSMerossFG storage: read file [/var/lib/hoobs/hoobs/persist/hoobs_meross_Rachel’s Curling Iron_persist.json].
9/6/2021, 1:23:43 PMHOOBSMeross[Rachel’s Curling Iron] FG timer: new subscription.
9/6/2021, 1:23:43 PMHOOBSMeross[Rachel’s Curling Iron] FG history: registering events.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] reverting to cloud control as hybrid mode is not turned on.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] initialising with options {"connection":"cloud","inUsePowerThreshold":0,"logging":"debug","showAs":"switch"}.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] initialised with id [2012100003049651853248e1e93eea25].
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] json debug info: {"uuid":"2012100003049651853248e1e93eea25","onlineStatus":1,"devName":"Vanity Smart Plug","devIconId":"device001","bindTime":1629469415,"deviceType":"mss110","subType":"us","channels":[{}],"region":"us","fmwareVersion":"4.2.7","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.2.7","hbDeviceId":"2012100003049651853248e1e93eea25","model":"MSS110"}.
9/6/2021, 1:23:44 PMHOOBSMeross✓ Setup complete.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] sending mqtt: {"header":{"from":"/app/1521906-1e97f99fa981e4f662e60321fcc848d3/subscribe","messageId":"2144c6fbe1c4ec3cd91d7afd97e71c2c","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"7d34df0be83bdcf37e672b578f9e8f7b","timestamp":1630952625},"payload":{}}.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] mqtt subscribe complete.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] incoming poll: {"header":{"messageId":"2144c6fbe1c4ec3cd91d7afd97e71c2c","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/2012100003049651853248e1e93eea25/publish","timestamp":1630952624,"timestampMs":953,"sign":"f536a4843897e1408554f7fdb1609452"},"payload":{"all":{"system":{"hardware":{"type":"mss110","subType":"us","version":"4.0.0","chipType":"MT7686","uuid":"2012100003049651853248e1e93eea25","macAddress":"48:e1:e9:3e:ea:25"},"firmware":{"version":"4.2.7","homekitVersion":"2.0.1","compileTime":"Aug 20 2021 15:15:07","encrypt":1,"wifiMac":"3c:28:6d:a5:6d:e6","innerIp":"192.168.86.24","server":"mqtt-us.meross.com","port":443,"userId":1521906},"time":{"timestamp":1630952624,"timezone":"America/Chicago","timeRule":[[1615708800,-18000,1],[1636268400,-21600,0],[1647158400,-18000,1],[1667718000,-21600,0],[1678608000,-18000,1],[1699167600,-21600,0],[1710057600,-18000,1],[1730617200,-21600,0],[1741507200,-18000,1],[1762066800,-21600,0],[1772956800,-18000,1],[1793516400,-21600,0],[1805011200,-18000,1],[1825570800,-21600,0],[1836460800,-18000,1],[1857020400,-21600,0],[1867910400,-18000,1],[1888470000,-21600,0],[1899360000,-18000,1],[1919919600,-21600,0]]},"online":{"status":1,"bindId":"G9pKNBd4CzY9pC95","who":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":1630855549}],"triggerx":[],"timerx":[]}}}}.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] has been reported [online].
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] reverting to cloud control as hybrid mode is not turned on.
9/6/2021, 1:23:44 PMHOOBSMeross[Rachel’s Curling Iron] sending mqtt: {"header":{"from":"/app/1521906-1e97f99fa981e4f662e60321fcc848d3/subscribe","messageId":"b512628e3717022583be7689ec509f06","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"1a5f23c32998fd54f05241963deaa93c","timestamp":1630952625},"payload":{}}.
```

**Comment by bwp91** [comment]
Hi @ddasal 

Can you show a screenshot of your meross app with the `Rachel’s Curling Iron` device and the second device together that isn't being shown in HOOBS?

**Comment by ddasal** [comment]
I had just renamed curling iron to vanity plug, but here is the screen shot
![image](https://user-images.githubusercontent.com/67334654/132335350-45c4d183-0bd9-46c4-bb3b-384998e616aa.png)

**Comment by bwp91** [comment]
This is strange indeed!
Can you post your meross config? You can get this from HOOBS UI - the settings icon, then click 'Advanced', then the meross bridge, and copy and paste what's in the box.
Just replace your username and password with something like [removed], so I know if they are there or not.

**Comment by ddasal** [comment]
It is fairly vanilla. Just my cloud credentials 
![image](https://user-images.githubusercontent.com/67334654/132341213-08b26b47-fe9f-45cb-b192-268d5a709066.jpeg)

**Comment by bwp91** [comment]
Can you try deleting it from your account and re-adding it?

**Comment by ddasal** [comment]
I can when I return home today.

**Comment by bwp91** [comment]
The plugin pulls a list of devices from your meross account.

If it's an unsupported model then there will be a message in the log.

For some reason it seems that this second device isn't being included in the device list received... not really sure why...

This is why I suggest deleting and repairing... this may somehow 'refresh' your device list, so it's included and given to the plugin.

Let me know how you get on!

**Comment by ddasal** [comment]
No such luck after deleting and reading the missing smart outlet... here are the logs

9/7/2021, 8:12:20 PMHOOBSMerossPlugin initialised. Setting up accessories....
9/7/2021, 8:12:21 PMHOOBSBridge is running on port 51826.
9/7/2021, 8:12:21 PMHOOBSMerossWARNINGMeross Key: 664afe28e1db227b9fbacc2f8233062c
9/7/2021, 8:12:21 PMHOOBSMeross[Vanity Smart Plug] FS storage: addWriter().
9/7/2021, 8:12:21 PMHOOBSMerossFG history: loading.
9/7/2021, 8:12:21 PMHOOBSMerossFG storage: read file [/var/lib/hoobs/hoobs/persist/hoobs_meross_Vanity Smart Plug_persist.json].
9/7/2021, 8:12:21 PMHOOBSMeross[Vanity Smart Plug] FG timer: new subscription.
9/7/2021, 8:12:21 PMHOOBSMeross[Vanity Smart Plug] FG history: registering events.
9/7/2021, 8:12:21 PMHOOBSMeross[Vanity Smart Plug] reverting to cloud control as hybrid mode is not turned on.
9/7/2021, 8:12:21 PMHOOBSMeross[Vanity Smart Plug] initialising with options {"connection":"cloud","inUsePowerThreshold":0,"logging":"debug","showAs":"switch"}.
9/7/2021, 8:12:21 PMHOOBSMeross[Vanity Smart Plug] initialised with id [2012100003049651853248e1e93eea25].
9/7/2021, 8:12:21 PMHOOBSMeross[Vanity Smart Plug] json debug info: {"uuid":"2012100003049651853248e1e93eea25","onlineStatus":1,"devName":"Vanity Smart Plug","devIconId":"device001","bindTime":1629469415,"deviceType":"mss110","subType":"us","channels":[{}],"region":"us","fmwareVersion":"4.2.7","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.2.7","hbDeviceId":"2012100003049651853248e1e93eea25","model":"MSS110"}.
9/7/2021, 8:12:21 PMHOOBSMeross✓ Setup complete.
9/7/2021, 8:12:22 PMHOOBSMeross[Vanity Smart Plug] sending mqtt: {"header":{"from":"/app/1521906-1e97f99fa981e4f662e60321fcc848d3/subscribe","messageId":"bc8646066ae103a90efb5742cbdbb99b","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"6d37c72ae2dad7118474dd461b78a262","timestamp":1631063542},"payload":{}}.
9/7/2021, 8:12:22 PMHOOBSMeross[Vanity Smart Plug] mqtt subscribe complete.
9/7/2021, 8:12:22 PMHOOBSMeross[Vanity Smart Plug] incoming poll: {"header":{"messageId":"bc8646066ae103a90efb5742cbdbb99b","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/2012100003049651853248e1e93eea25/publish","timestamp":1631063554,"timestampMs":142,"sign":"632b41c20f6808705f16457fa04b04fc"},"payload":{"all":{"system":{"hardware":{"type":"mss110","subType":"us","version":"4.0.0","chipType":"MT7686","uuid":"2012100003049651853248e1e93eea25","macAddress":"48:e1:e9:3e:ea:25"},"firmware":{"version":"4.2.7","homekitVersion":"2.0.1","compileTime":"Aug 20 2021 15:15:07","encrypt":1,"wifiMac":"3c:28:6d:a5:6d:e6","innerIp":"192.168.86.24","server":"mqtt-us.meross.com","port":443,"userId":1521906},"time":{"timestamp":1631063554,"timezone":"America/Chicago","timeRule":[[1615708800,-18000,1],[1636268400,-21600,0],[1647158400,-18000,1],[1667718000,-21600,0],[1678608000,-18000,1],[1699167600,-21600,0],[1710057600,-18000,1],[1730617200,-21600,0],[1741507200,-18000,1],[1762066800,-21600,0],[1772956800,-18000,1],[1793516400,-21600,0],[1805011200,-18000,1],[1825570800,-21600,0],[1836460800,-18000,1],[1857020400,-21600,0],[1867910400,-18000,1],[1888470000,-21600,0],[1899360000,-18000,1],[1919919600,-21600,0]]},"online":{"status":1,"bindId":"G9pKNBd4CzY9pC95","who":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":1631062972}],"triggerx":[],"timerx":[]}}}}.
9/7/2021, 8:12:22 PMHOOBSMeross[Vanity Smart Plug] has been reported [online].
9/7/2021, 8:12:22 PMHOOBSMeross[Vanity Smart Plug] reverting to cloud control as hybrid mode is not turned on.
9/7/2021, 8:12:22 PMHOOBSMeross[Vanity Smart Plug] sending mqtt: {"header":{"from":"/app/1521906-1e97f99fa981e4f662e60321fcc848d3/subscribe","messageId":"962e4818348d1647b508c06f9669b819","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"58a27c0429dd77815ab33d9c8e324248","timestamp":1631063542},"payload":{}}.

**Comment by bwp91** [comment]
Could I message you on the homebridge discord server?
https://discord.gg/bHjKNkN
