### ISSUE TITLE
Smart Switch Support

### ISSUE THREAD

**Issue by ellwoodb** [donavanbecker/homebridge-meross#346]
* **Please explain your feature request in a one or two sentences.**
I wanted to add my Meross Smart Switches to homebrige with this plugin but they didn't show up. In the log it said:
```
[Smart Switch] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2105109139581890850948e1e970e0d5","onlineStatus":1,"devName":"Smart Switch","devIconId":"device027_un","bindTime":1631345651,"deviceType":"mss710r","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.2.3","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.2.3","hbDeviceId":"2105109139581890850948e1e970e0d5","model":"MSS710R"}
```
...and for the second one:
```
[Smart Switch] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2105109694958990850948e1e970f78a","onlineStatus":1,"devName":"Smart Switch","devIconId":"device027_un","bindTime":1631345649,"deviceType":"mss710r","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.2.3","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.2.3","hbDeviceId":"2105109694958990850948e1e970f78a","model":"MSS710R"}
```

The product number is `MSS710HKIT`. I read that there is support for the regular MSS710 but aparently not the HomeKit version.
The Github link is dead but I thought I should post here.

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Meross devices that this relates to?**
The Meross Smart Wi-Fi Switch with HomeKit support

* **Anything else?**
Thanks for making this plugin!

**Comment by bwp91** [comment]
Hi @ellwoodb 

Can you update to the beta version of the plugin:
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Your switches should now work with this version :)

**Comment by ellwoodb** [comment]
It's working! I had to use my username and password though. With only the key it didn't work but that could also be my fault.

Thanks for the quick fix! :)

**Comment by bwp91** [comment]
The key is used for local control, and you need to configure the device in the plugin settings for local control too.

Using just the key on its own will not work, this may be of help:

https://github.com/bwp91/homebridge-meross/wiki/Local-Control#device-setup

**Comment by ellwoodb** [comment]
Thanks it's working now! :D

Should I close the issue?

**Comment by bwp91** [comment]
Closed!
