### ISSUE TITLE
Ignore HomeKit native MSG200

### ISSUE THREAD

**Issue by Perilax-De** [donavanbecker/homebridge-meross#348]
* **Please explain your feature request in a one or two sentences.**

Hello Ben, I want to ignore my HomeKit native MSG200.

* **Is your feature request related to a problem? Please describe.**

The MSG200 work´s direct with HomeKit but I also want it in the Meross app with my other devices.
If I hook in your plugin "ignore HomeKit nativ devices" the MSG is already shown.
So I have this device in HomeKit double.

Do you have any solution for this issue ?

* **Any particular Meross devices that this relates to?**

???

* **Anything else?**

Thanks for this great plugin !!!

**Comment by bwp91** [comment]
Hi, can you tell me the hardware version it shows for your MSG200?
This can be seen in the plugin ui in the “my devices” tab and also within the meross app.

**Comment by Perilax-De** [comment]
![image](https://user-images.githubusercontent.com/75173766/133844124-6c266868-6671-4d3b-a2ad-5c111650c4c6.jpeg)

**Comment by Perilax-De** [comment]
![image](https://user-images.githubusercontent.com/75173766/133844281-897e14d9-02bd-4d8e-8bff-a91a79372b52.jpeg)

**Comment by bwp91** [comment]
Can you update to the beta version I have just pushed, v6.12.1-beta.0.

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Once updated and restarted, this should remove your MSG200 from Homebridge and HomeKit :)

**Comment by Perilax-De** [comment]
It works. 

You are great !!!

Thank you.
