### ISSUE TITLE
MSS210 plug stopped working after firmware update

### ISSUE THREAD

**Issue by hectorkd** [donavanbecker/homebridge-meross#349]
### What issue do you have? Please be as thorough and explicit as possible.

After updating my firmware for my MSS210 non native homkit plug within the Meross app, it now wont work in homekit. I've checked all the details within HOOBS and they are correct.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

Version: 4.0.100

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

6.12.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSS210 non native homekit plug

### Please paste any relevant logs below.

```
Meross Bridge Meross WARNING[Fan] failed to request status as socket hang up at connResetException (internal/errors.js:628:14).

```
My set up with my ip address replaced with zeros
```
"singleDevices": [
        {
            "name": "Fan",
            "serialNumber": "251h22191003978",
            "deviceUrl": "000.000.0.000",
            "model": "MSS210",
            "showAs": "outlet",
            "firmwareRevision": "2.2.2"
        }
    ]
```

**Comment by bwp91** [comment]
Hi @hectorkd 

I assume you also have either your meross credentials or your user key in the config? Have you also tried power cycling the device?

The `failed to request status as socket hang up` message seems like a problem with the polling. Does controlling it from the home app work ie turning it on and off? If you use the meross app to turn the device on/off, does the updated status show in the home app?

**Comment by hectorkd** [comment]
Hi @bwp91 

Yes, I am using my Meross Key and have tried power cycling the devices.

No, neither of those work. I can't turn the devices on/off in the home app, it tries then I get a no response. When I turn the devices on/off in the Meross app, nothing happens in the home app at all.

**Comment by bwp91** [comment]
I also wanted to ask if you are using the correct serial number. The serial
number in the config needs to be the 32 character uiid for the device. 
This is shown in the log when initialising cloud device (ie with your meross username and password configured) and also can be obtained with apps like http catcher

**Comment by hectorkd** [comment]
Ah that seems to have been the issue. I was putting in the devices serial number not the uuid number. 

Thanks for the help

**Comment by bwp91** [comment]
Excellent. I’ll close this issue!
