### ISSUE TITLE
Add support Smart WiFi Humidifier MSXH0

### ISSUE THREAD

**Issue by dragonjo84** [donavanbecker/homebridge-meross#35]
Hello
Can you tell me if you work on adds of Smart WiFi Humidifier MSXH0 ?

Thanks a lot !
Have a nice day 

**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensative information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here. 
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge GSH Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by dragonjo84** [comment]
there's no log for the MSXHO.
I will integrate this to my Homebridge please
https://www.meross.com/product/47/article/


Homebridge Config: 
{
            "name": "Humidificateur",
            "deviceUrl": "192.168.5.66",
            "channel": 0,
            "timestamp": 0,
            "accessory": "Meross"
        }

Environment:

Node.js Version:v12.16.3
NPM Version:6.14.4
Homebridge Version:1.1.1
Homebridge GSH Plugin Version: no
Homebridge Config UI X Plugin Version: v4.23.0
Operating System:mac os catalina v10.15.5

Thanks for your help

**Comment by donavanbecker** [comment]
@dragonjo84 Can you post what you get from HTTP Catcher or Charlie’s Proxy?

**Comment by donavanbecker** [comment]
@dragonjo84 have you used http catcher to get the data that is being set to the plug? if not see [Getting-Credentials](https://github.com/donavanbecker/homebridge-meross/wiki/Getting-Credentials) wiki.

**Comment by donavanbecker** [comment]
See #151

**Comment by dragonjo84** [comment]
Sorry for the long time with a y response 
Si what do you do with http catcher please ?
