### ISSUE TITLE
Meross Smart Plug mss620r - Device not Supported -

### ISSUE THREAD

**Issue by finkuja** [donavanbecker/homebridge-meross#351]
### What issue do you have? Please be as thorough and explicit as possible.

Device will not load in accesories error message [DeviceName] is not supported,

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HomeBridge UI-X

* Which version of Homebridge/HOOBS do you have?

v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 4 B 

Raspbian GNU/Linux Buster (10)

Node v14.17.4
npm v7.20.3

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

Homebridge Meross
homebridge-meross v6.13.2

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

Smart Plug mss620r

### Please paste any relevant logs below.

```
{"uuid":"2102237966900990842448e1e94d73d1","onlineStatus":1,"devName":"Garage","devIconId":"device026_eu","bindTime":1631908352,"deviceType":"mss620r","subType":"eu","channels":[{},{"type":"Switch","devName":"Prusa MK3S Plus","devIconId":"device001"},{"type":"Switch","devName":"Led","devIconId":"device001"}],"region":"ap","fmwareVersion":"4.1.32","hdwareVersion":"4.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/1537243/2102237966900990842448e1e94d73d1/1631912092211.jpg","iconType":2,"skillNumber":"","cluster":2,"domain":"mqtt-ap-2.meross.com","reservedDomain":"mqtt-ap-2.meross.com","firmware":"4.1.32","hbDeviceId":"2102237966900990842448e1e94d73d1","model":"MSS620R"}

```

**Comment by bwp91** [comment]
Hi @finkuja 

If you install the beta version of the plugin, this device should start working!

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

**Comment by finkuja** [comment]
> Hi @finkuja
> 
> If you install the beta version of the plugin, this device should start working!
> 
> https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Yes it does work now Thank You @bwp91
