### ISSUE TITLE
enable/ disable devices

### ISSUE THREAD

**Issue by Stromberg73** [donavanbecker/homebridge-meross#352]
* **Please explain your feature request in a one or two sentences.**
Ability to choose what meross devices we want to enable through HB. Otherwise I still have my Meross Homekit devices two times on homekit.

* **Is your feature request related to a problem? Please describe.**
no

* **Any particular Meross devices that this relates to?**
I have one MSS510X, one MSG100, three MSS210 and four MSS310. I just needed HB for the MSS310's, because all of the others were already configured through apple homekit (and now are duplicated in apple homekit)

 **Anything else?**
no

**Comment by bwp91** [comment]
Hi @Stromberg73 can you get me a list all the homekit native devices you, specifically with their model number and the hardware version as shown in the homebridge ui? (in the my devices tab of plugin settings).

Thanks!

**Comment by Stromberg73** [comment]
Hi @bwp91, I have:
- One MSS510X hardware 4.0.0 Firmware 4.2.3
- Three MSS210 hardware 4.0.0 Firmware 4.2.5
- One MSG100  hardware 4.0.0 Firmware 4.2.1
- Four MSS310  hardware 2.0.0 Firmware 2.1.16

**Comment by bwp91** [comment]
Thanks.

If you update to the beta version of the plugin, 7.0.0-beta.8, and also use the plugin settings to tick the "Ignore HomeKit Native Devices" option, then the above homekit native devices should be removed from homebridge.

**Comment by bwp91** [comment]
I've just realised that my outlet is an MSS310 on hardware 2.0.0, firmware 2.1.16, but it isn't homekit native? Is yours definitely homekit native? This potentially causes a big flaw in my logic...

**Comment by Stromberg73** [comment]
@bwp91 solve it by installing beta version and check the "ignore homekit native devices". Only the four MSS310, aren't homekit native. Those were the ones i needed to work with homebridge. the others were all homekit Native. Thanks a lot @bwp91

**Comment by bwp91** [comment]
Closing as I believe this is resolved now!
