### ISSUE TITLE
Meross devName":"Smart Wi-Fi Light Strip"

### ISSUE THREAD

**Issue by JuanjoMB98** [donavanbecker/homebridge-meross#353]
* **Please explain your feature request in a one or two sentences.**
Support for deviceType":"msl320cpr"

* **Is your feature request related to a problem? Please describe.**

Not supported

* **Any particular Meross devices that this relates to?**
msl320cpr

* **Anything else?**

**Comment by JuanjoMB98** [comment]
works in local adding the ip adress, getting with arp -a

**Comment by bwp91** [comment]
Hi @JuanjoMB98 

This device should start working in cloud mode with the beta version of the plugin v7.0.0-beta.7!
