### ISSUE TITLE
Prevent HomeKit enabled Meross devices from being bridged

### ISSUE THREAD

**Issue by Conanap** [donavanbecker/homebridge-meross#354]
* **Please explain your feature request in a one or two sentences.**

I have a mix of Meross devices such that some came with HomeKit support and some don't. When using the plugin via Meross cloud, all devices are bridged by Homebridge, even those already with HomeKit support, causing duplicates to show up. 

* **Is your feature request related to a problem? Please describe.**

Yes. I was hoping that I would not see duplicate devices.  

* **Any particular Meross devices that this relates to?**
The Meross 3 way switches have a version that works with HomeKit, specifically MSS550X. A list in configs of serials to not bridge would be appreciated, or an automated form of detecting whether or not a device supports HomeKit already would work too. 

* **Anything else?**

Thanks for the hard work!

**Comment by bwp91** [comment]
Hi @Conanap can you get me a list all the homekit native devices you, specifically with their model number and the hardware version as shown in the homebridge ui? (in the my devices tab of plugin settings).

Thanks!

**Comment by Conanap** [comment]
For sure! I only have 1 item that I use for now.
Model Number: mss550x
hardware version: 4.0.0 

Let me know if you need other information, thanks!

**Comment by bwp91** [comment]
If you update to the beta version of the plugin, v7.0.0-beta.10, and then use the plugin settings to "Ignore HomeKit Native Devices", you should find that the MSS500X disappears from Homebridge.

**Comment by Conanap** [comment]
works perfectly, thank you!
