### ISSUE TITLE
Smart Temperature and Humidity Sensor (MS100) is not found (and other devices)

### ISSUE THREAD

**Issue by iceweasel1** [donavanbecker/homebridge-meross#356]
Hey @bwp91 ,

I have the following devices in use from Meross:

- Smart Wi-Fi Ambient Light (Model MSL 430) (HomeKit version).
- Smart Wi-Fi Hub (model MSH300) (HomeKit version)
- Smart Thermostat Valve (Model: MTS150) (HomeKit version)
- Smart Wi-Fi LED Bulb (Model: MSL120) (HomeKit version)
- Smart Temperature and Humidity Sensor (Model: MS100) (Non HomeKit version)

Except for the last product, the Smart Temperature and Humidity Sensor (Model: MS100), it shows me all the other devices in HomeKit and the Meross app. So even before I haven't installed Homebridge yet.

Among other things, because of the Smart Temperature and Humidity Sensor (model: MS100), which are not HomeKit-enabled, I have now installed Homebridge and your plugin to it, so I can get them into HomeKit. Unfortunately, so far I can't get your plugin to show me the Smart Temperature and Humidity Sensor (Model: MS100) in Homebridge. It does not find them.

Your plugin only finds 2 products so far. The Ambient Light and the Wi-Fi LED Bulb. The other products, are not found either. I have my Meross cloud credentials stored in your plugin.

I have activated the debug mode in your plugin to display more information. In the log I find the following information:

```
[10/10/2021, 12:35:22 AM] [Meross] [Smart Hub] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2102082982188426280948e1e94c5f9e","onlineStatus":1,"devName":"Smart Hub","devIconId":"device040_un","bindTime":1630336036,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.27","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.27","hbDeviceId":"2102082982188426280948e1e94c5f9e","model":"MSH300HK"}
```

Here they talk about MSH300HK Hub, which makes me wonder. In come from the EU, Germany. I did not know that there may be different models depending on the country and continent. Or I am wrong.

Is there a solution to this, how I could specifically include the Smart Temperature and Humidity Sensor (Model: MS100) in your plugin? Also maybe the other devices that have HomeKit but I would still like to have them in HomeKit.

Regards
ice

**Comment by bwp91** [comment]
Hi @iceweasel1 

Thanks for your issue. Can you update to the beta version of the plugin?

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

This should get the MSH300HK to start working with the plugin, along with the MS100 devices.

You will probably then find more 'unsupported device' notices in the logs, these will refer to the MTS150 devices. Could you copy and paste one of the messages it shows?

Once all your device types have been _added_ to Homebridge then it will be a lot easier to work on what needs _removing_ with regards to HomeKit native support.

Thanks

**Comment by iceweasel1** [comment]
Hey Ben,

big thanks for your quick reply and a temporary solution!

I updated it to the latest beta and the Temperature and Humidity Sensor MS100 and the Hub MSH300HK are immediately recognized and displayed correctly. Awesome how fast that went.

You're right. In the log, all the Thermostat Valve (MTS150) are listed as not yet supported.

These are displayed in the order of my rooms:

- Office
- Livin groom
- Bedroom
- Bathroom
- Kitchen

Attached is the protocol for this:

`[10/10/2021, 8:08:29 PM] [Meross] [Büro] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2102082982188426280948e1e94c5f9e","onlineStatus":1,"devName":"Büro","devIconId":"device040_un","bindTime":1630336036,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.27","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.27","hbDeviceId":"2102082982188426280948e1e94c5f9e03002CFD","model":"MTS150"}
[10/10/2021, 8:08:29 PM] [Meross] [Wohnzimmer] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2102082982188426280948e1e94c5f9e","onlineStatus":1,"devName":"Wohnzimmer","devIconId":"device040_un","bindTime":1630336036,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.27","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.27","hbDeviceId":"2102082982188426280948e1e94c5f9e03004FE2","model":"MTS150"}
[10/10/2021, 8:08:29 PM] [Meross] [Schlafzimmer] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2102082982188426280948e1e94c5f9e","onlineStatus":1,"devName":"Schlafzimmer","devIconId":"device040_un","bindTime":1630336036,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.27","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.27","hbDeviceId":"2102082982188426280948e1e94c5f9e030064A8","model":"MTS150"}
[10/10/2021, 8:08:29 PM] [Meross] [Bad] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2102082982188426280948e1e94c5f9e","onlineStatus":1,"devName":"Bad","devIconId":"device040_un","bindTime":1630336036,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.27","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.27","hbDeviceId":"2102082982188426280948e1e94c5f9e0300B365","model":"MTS150"}
[10/10/2021, 8:08:29 PM] [Meross] [Küche] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2102082982188426280948e1e94c5f9e","onlineStatus":1,"devName":"Küche","devIconId":"device040_un","bindTime":1630336036,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.27","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.1.27","hbDeviceId":"2102082982188426280948e1e94c5f9e0300ECAF","model":"MTS150"}`

Thank you for your work!

Greetings
ice

**Comment by bwp91** [comment]
Thanks for this.

If you update to the newer beta, 7.0.0-beta.13, you should find these MTS150 start working.

Now for the HomeKit native devices you want to hide... there is an option in the "optional settings" part of the config to ignore homekit native devices. If you check this option and restart the plugin, you should find *most* of your native models are removed. If there are any remaining, please let me know the model and the hardware version as shown in the homebridge UI in the "My Devices" section of the plugin settings.

**Comment by iceweasel1** [comment]
I just did the beta update. Damn, very cool!

Thanks again so much Ben!

![Bildschirmfoto 2021-10-10 um 21 41 36](https://user-images.githubusercontent.com/49625256/136710926-c2688d32-8584-440e-a28f-8a38f607b670.png)
![Bildschirmfoto 2021-10-10 um 21 41 58](https://user-images.githubusercontent.com/49625256/136710929-2dd9b27c-7975-496b-9d64-f5ab96667f84.png)
![Bildschirmfoto 2021-10-10 um 21 42 53](https://user-images.githubusercontent.com/49625256/136710930-4e1c6f90-2ae5-4b77-931e-e10fc57b2bf1.png)
![Bildschirmfoto 2021-10-10 um 21 43 15](https://user-images.githubusercontent.com/49625256/136710931-91a9e3ed-9958-4d73-b783-89979c850aef.png)

**Comment by bwp91** [comment]
Is your MSL120 still appearing in homebridge?

**Comment by iceweasel1** [comment]
Forgive me. I had forgotten to report that. 

So, I have now enabled the option, restarted Homebridge. The Smart Bull, which I currently do not have connected (powered), continues to show up in Homebridge and HomeKit after a restart and the option enabled.

![Bildschirmfoto 2021-10-10 um 21 56 00](https://user-images.githubusercontent.com/49625256/136711244-af5e059a-bff6-4f7d-b411-693806bd7073.png)
![Bildschirmfoto 2021-10-10 um 21 56 46](https://user-images.githubusercontent.com/49625256/136711284-a59f9be7-8d1d-4ceb-b9aa-dd7aa41e9994.png)
![Bildschirmfoto 2021-10-10 um 21 53 38](https://user-images.githubusercontent.com/49625256/136711245-ef951abf-0741-4ea9-8322-80a168266235.png)

**Comment by bwp91** [comment]
In the "My devices" tab, can you get me the model and hardware revision as shown?

**Comment by iceweasel1** [comment]
Yes.
![Bildschirmfoto 2021-10-10 um 22 02 09](https://user-images.githubusercontent.com/49625256/136711405-923b2826-e02b-46c5-9a6a-c4425b88e2da.png)

**Comment by bwp91** [comment]
Can you update to the newer beta 7.0.0-beta.14? 

- just to check the temperature/humidity sensors are still working properly? I have changed some code
- the MSL120DR unfortunately won't be removed until the plugin can access the device to retrieve the hardware version and compare it to the native list (if you want to remove it immediately, you can create an item in the 'light devices section' of the settings with a label and the serial number, and check the "Hide From Homekit" option

**Comment by bwp91** [comment]
Also, for your info, if you use the Eve HomeKit app, you will have extra options to put the valves into modes available in the Meross app like "Heat", "Cool", "Auto" and "Economy".

You can use the Eve app to setup scenes for these modes that will appear in the Home app.

**Comment by iceweasel1** [comment]
I just did the update to beta 7.0.0 14. I had not unchecked the "Ignore HomeKit Native Devices" and left it in.

After restarting Homebridge, the Smart Bulb disappeared immediately. On the Homebridge device overview, the HB log and in HomeKit. Nice!

The temperature/humidity sensors continues to display correctly as well. Also the thermostats show the correct values and work as soon as I change the settings or values.

I do not use the Eve app so far. I have often heard of it, but have not yet dealt with it. "Heat", "Cool", "Auto" and "Economy" it even shows me in Homebridge on the devices. :)

Quick question. In your readme I saw your Discord. As soon as I click on it, I get a message from Discord that you can't access it. I am new to Discord. Thought therefore, that it might be faster there with the communicate than here. ;-)

**Comment by bwp91** [comment]
Can you try the discord link on the "create new issue" page on this repo? maybe that one will work

**Comment by buzzub** [comment]
I have a native HomeKit LED light strip that is showing up even with the ignore homekit native devices option checked. The model is MSL320CPR and the hardware version is 4.0.0.

**Comment by bwp91** [comment]
> I have a native HomeKit LED light strip that is showing up even with the ignore homekit native devices option checked. The model is MSL320CPR and the hardware version is 4.0.0.

Hi @buzzub, thanks.

This device will be removed with the next version of the plugin. You can update to the beta version already and this device will be removed from homebridge/homekit!

**Comment by buzzub** [comment]
Cool. I will just wait for the next release.
