### ISSUE TITLE
Problems at updating to 6.13.2

### ISSUE THREAD

**Issue by Gandalf8266** [donavanbecker/homebridge-meross#358]
### What issue do you have? Please be as thorough and explicit as possible.

Error in updating to 6.13.2

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

v1.3.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
* 
6.13.1

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

Garage Door Opener

### Please paste any relevant logs below.

![Ohne Titel 2](https://user-images.githubusercontent.com/38372908/137278153-a4a694aa-19af-4558-862a-3df8c473a5f8.png)

**Comment by bwp91** [comment]
Hi @Gandalf8266, three things to do.

First is to change your node version to one that Homebridge officially supports, your current version v15.2.1 is not. Run this in the terminal to change go v14:

```
sudo hb-service update-node 14.18.1
```

Secondly, you will need to manually delete the plugin folder before updating again, run this in the terminal,

```
sudo rm -rf /usr/local/lib/node_modules/homebridge-meross
```

Finally install the latest version of the plugin manually,

```
sudo npm i -g homebridge-meross
```

Then restart Homebridge and everything should be good to go!

**Comment by Gandalf8266** [comment]
thx, it has worked
