### ISSUE TITLE
MSS560M Dimmer Light Switch is not supported

### ISSUE THREAD

**Issue by jpflouret** [donavanbecker/homebridge-meross#359]
* **Please explain your feature request in a one or two sentences.**
Add support for MSS560M light switch

* **Is your feature request related to a problem? Please describe.**
Device is detected but not supported.

* **Any particular Meross devices that this relates to?**
[Meross] [Bedroom light] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"1902224702100039080434298f1c4e6f","onlineStatus":1,"devName":"Bedroom light","devIconId":"device041_us","bindTime":1624779614,"deviceType":"mss560m","subType":"us","channels":[{}],"region":"us","fmwareVersion":"3.1.6","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"3.1.6","hbDeviceId":"1902224702100039080434298f1c4e6f","model":"MSS560M"}

* **Anything else?**

**Comment by bwp91** [comment]
Hi @jpflouret 

Please install the beta version of the plugin, v7.0.1-beta.0.

This device type should then appear in Homebridge as a dimmer.

Thanks!
