### ISSUE TITLE
MEross plugins starts and stops and so on

### ISSUE THREAD

**Issue by MasterofKungfu9999** [donavanbecker/homebridge-meross#361]
### What issue do you have? Please be as thorough and explicit as possible.

The Meross bridge with Hoobs starts and stops and starts and stops

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Hoobs

* Which version of Homebridge/HOOBS do you have?

4.1.9

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

71.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

msg100

### Please paste any relevant logs below.

```
I can't paste any logs because there is no bug report. It only starts and stops after prompting user and passwort
```

**Comment by bwp91** [comment]
But there must be logs showing that the bridge is stopping and starting?

**Comment by MasterofKungfu9999** [comment]
No, i just enabled debug. But there is nothing shown

**Comment by bwp91** [comment]
So if there are no logs at all then how do you know it is starting and stopping over again?

**Comment by MasterofKungfu9999** [comment]
With a popup of hoobs and i can the the logs that there are alwasy the same messages

**Comment by MasterofKungfu9999** [comment]
also i can see at in the section "bridges" one bridge is starting and stopping again and again

**Comment by bwp91** [comment]
It would be helpful to see a section of the logs, even if there aren't any visible errors... otherwise it is impossible to start figuring out what's going on

**Comment by MasterofKungfu9999** [comment]
21.10.2021, 16:27:38Meross BridgeMerossInitialising plugin v7.1.0 | Node v14.18.1 | HB v1.3.5 | HOOBS v4...
21.10.2021, 16:27:38Meross BridgeMerossPlugin initialised. Setting up accessories....
21.10.2021, 16:27:38Meross BridgeMerossWarnungDisabling cloud client as username and password not supplied in config.
21.10.2021, 16:27:38Meross BridgeMeross[Smart Garage Door Opener] sending update: {"header":{"from":"http://192.168.13.71/config","messageId":"xe119t2dvz7631q3","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"0","timestamp":1634826458,"triggerSrc":"iOSLocal","uuid":""},"payload":{}}.
21.10.2021, 16:27:39Meross BridgeMeross[Smart Garage Door Opener] initialising with options {"connection":"local","garageDoorOpeningTime":20,"logging":"debug"}.
21.10.2021, 16:27:39Meross BridgeMeross[Smart Garage Door Opener] initialised with id [].
21.10.2021, 16:27:39Meross BridgeMeross[Smart Garage Door Opener] json debug info: {"name":"Garage","serialNumber":"","connection":"hybrid","deviceUrl":"192.168.13.71","model":"MSG100","uuid":"","deviceType":"MSG100","devName":"Garage","channels":[],"hbDeviceId":""}.
21.10.2021, 16:27:39Meross BridgeMeross[Smart Garage Door Opener] incoming poll: {"header":{"messageId":"xe119t2dvz7631q3","namespace":"Appliance.System.All","triggerSrc":"iOSLocal","method":"GETACK","payloadVersion":1,"from":"/appliance/2009117184449836100648e1e932cef0/publish","timestamp":1634826458,"timestampMs":690,"sign":"4b29d16ee3003ca418d7e790eaf28d90755"},"payload":{"all":{"system":{"hardware":{"type":"msg100","subType":"us","version":"4.0.0","chipType":"MT7686","uuid":"0","macAddress":""},"firmware":{"version":"4.2.1","homekitVersion":"2.0.1","compileTime":"Sep 15 2021 10:21:01","encrypt":1,"wifiMac":"","innerIp":"192.168.13.71","server":"mqtt-eu-2.meross.com","port":443,"userId":},"time":{"timestamp":1634826458,"timezone":"Europe/Berlin","timeRule":[[1603587600,3600,0],[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1]]},"online":{"status":1,"bindId":"PTiHeoHVgKiyohuX","who":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":0}],"triggerx":[{"channel":0,"id":"1111111111111111","count":1}],"timerx":[],"garageDoor":[{"channel":0,"open":0,"lmTime":0}]}}}}.
21.10.2021, 16:27:39Meross BridgeMeross[Smart Garage Door Opener] has been reported [online].rtrtrt
21.10.2021, 16:27:41Meross BridgeMeross✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91

**Comment by bwp91** [comment]
Does it restart over and over again if you restart hoobs? restart the whole server?

**Comment by MasterofKungfu9999** [comment]
yes

**Comment by bwp91** [comment]
Are you still having this issue?

**Comment by MasterofKungfu9999** [comment]
yes

**Comment by bwp91** [comment]
Can you try deleting the bridge and starting again with reinstalling the plugin?

**Comment by MasterofKungfu9999** [comment]
Yes it's the same

**Comment by bwp91** [comment]
In the hoobs ui can you go to the bridge settings and go to "Export Bridge" and download the file... and send this file to info@hoobs.com and it will be directed to me...

**Comment by MasterofKungfu9999** [comment]
I will do!

**Comment by MasterofKungfu9999** [comment]
@bwp91 
Can you tell if  the passwort and username will be shown when im going to export the bridge?

**Comment by bwp91** [comment]
Please update to v7.1.1 and let me know if the issue seems fixed :)

**Comment by MasterofKungfu9999** [comment]
I've upated and it seems to be fixed. Thanks for your support!

**Comment by mike43** [comment]
Followed this thread with the same issue reported above on 7.1.0 (Hoobs 4.1.11) and 7.1.1 fixes the endless restart. 
Thanks Ben!

**Comment by bwp91** [comment]
anyone here with an MSG100 device? would you have any insight into this issue?
https://github.com/bwp91/homebridge-meross/issues/512
