### ISSUE TITLE
Homebridge version issue

### ISSUE THREAD

**Issue by ColinScattergood** [donavanbecker/homebridge-meross#363]
### What issue do you have? Please be as thorough and explicit as possible.
When the Meross bridge launches, I get the following error:

`12:54:05 PM Meross BridgeERROR[31mThe plugin "homebridge-meross" requires a Homebridge version of ^1.3.5 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
4.0.104

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 3b+

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
7.1.1

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
Uncertain, doesn't seem related to a specific device.

### Please paste any relevant logs below.

```
10/27/2021, 12:53:29 PMWARNINGdevice reboot command received
10/27/2021, 12:53:29 PMMeross BridgeMerossWARNING[Smart Plug-In Dimmer] mqtt connection closed.
10/27/2021, 12:53:29 PMCanary Bridge stopping
10/27/2021, 12:53:29 PMCamera FFmpeg Bridge stopping
10/27/2021, 12:53:29 PMWeather Plus Bridge stopping
10/27/2021, 12:53:29 PMCarrier Infinity Bridge stopping
10/27/2021, 12:53:29 PMMeross Bridge stopping
10/27/2021, 12:53:29 PMRoomba2 Bridge stopping
10/27/2021, 12:53:29 PMBroadlink Rm Pro Bridge stopping
10/27/2021, 12:53:29 PMUnifi Protect Bridge stopping
10/27/2021, 12:53:53 PMhub is running on port 80
10/27/2021, 12:53:54 PMCanary Bridge starting
10/27/2021, 12:53:54 PMCamera FFmpeg Bridge starting
10/27/2021, 12:53:54 PMWeather Plus Bridge starting
10/27/2021, 12:53:55 PMMeross Bridge starting
10/27/2021, 12:53:55 PMCarrier Infinity Bridge starting
10/27/2021, 12:53:56 PMRoomba2 Bridge starting
10/27/2021, 12:53:56 PMUnifi Protect Bridge starting
10/27/2021, 12:53:57 PMBroadlink Rm Pro Bridge starting
10/27/2021, 12:54:04 PMCanary BridgeLoaded plugin 'homebridge-canary'
10/27/2021, 12:54:04 PMCanary BridgeLoading 1 accessories...
10/27/2021, 12:54:05 PMCanary BridgeCanaryAdding Canary AllInOne (C100K1615631)
10/27/2021, 12:54:05 PMMeross BridgeERROR[31mThe plugin "homebridge-meross" requires a Homebridge version of ^1.3.5 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
10/27/2021, 12:54:06 PMMeross BridgeLoaded plugin 'homebridge-meross'
10/27/2021, 12:54:06 PMMeross BridgeLoading 1 platforms...
10/27/2021, 12:54:06 PMMeross BridgeMerossInitialising plugin v7.1.1 | Node v14.18.1 | HB v1.3.4 | HOOBS v4...
10/27/2021, 12:54:06 PMMeross BridgeMerossPlugin initialised. Setting up accessories....
10/27/2021, 12:54:06 PMCanary BridgeBridge is running on port 52826.
10/27/2021, 12:54:07 PMMeross BridgeBridge is running on port 55826.
```

**Comment by bwp91** [comment]
There is in fact an update for HOOBS - v4.1.11 - but it doesn't seem to appear for some users.

You can run these terminal commands here:
https://github.com/hoobs-org/HOOBS/issues/1607#issuecomment-949827952

But I would advise not to use the terminal within the HOOBS UI, instead use another ssh client to ssh in.

**Comment by ColinScattergood** [comment]
> There is in fact an update for HOOBS - v4.1.11 - but it doesn't seem to appear for some users.
> 
> You can run these terminal commands here: [hoobs-org/HOOBS#1607 (comment)](https://github.com/hoobs-org/HOOBS/issues/1607#issuecomment-949827952)
> 
> But I would advise not to use the terminal within the HOOBS UI, instead use another ssh client to ssh in.

AH HA. Thank you. I'll give this a go. Interesting......

**Comment by ColinScattergood** [comment]
> There is in fact an update for HOOBS - v4.1.11 - but it doesn't seem to appear for some users.
> 
> You can run these terminal commands here: [hoobs-org/HOOBS#1607 (comment)](https://github.com/hoobs-org/HOOBS/issues/1607#issuecomment-949827952)
> 
> But I would advise not to use the terminal within the HOOBS UI, instead use another ssh client to ssh in.

This fixed it. Thanks for the help as always!
