### ISSUE TITLE
Meross Smart Plug Mini

### ISSUE THREAD

**Issue by SimonLawson70** [donavanbecker/homebridge-meross#364]
Getting an information error from the Meross Smart Plug Mini (UK version) as an unrecognised device. This is a Homekit-native device and needs to be added to the Ignore list. The model ID is MSS110NR

[smart plug mini] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
`{"uuid":"2102253396294990842848e1e94e5618","onlineStatus":2,"devName":"smart plug mini","devIconId":"device065_uk","bindTime":1635159293,"deviceType":"mss110nr","subType":"uk","channels":[{}],"region":"eu","fmwareVersion":"4.1.23","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"4.1.23","hbDeviceId":"2102253396294990842848e1e94e5618","model":"MSS110NR"}`

**Comment by bwp91** [comment]
You can update to beta version 7.1.3-beta.1 and hopefully this device will be ignored by the plugin :)

**Comment by SimonLawson70** [comment]
Wow, that was fast. Any yes, both devices are correctly ignored. Thanks

Simon
