### ISSUE TITLE
Meross Smart Desk Lamp

### ISSUE THREAD

**Issue by SimonLawson70** [donavanbecker/homebridge-meross#365]
Getting an information error from the Meross Smart Desk Lamp (UK version) as an unrecognised device. This is a Homekit-native device and needs to be added to the Ignore list. The model ID is MDL110

[Office Desk Lamp] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
`{"uuid":"2103027379102890843548e1e94f1c77","onlineStatus":1,"devName":"Office Desk Lamp","devIconId":"device_mdl110_un","bindTime":1631977278,"deviceType":"mdl110","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.1.9","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"4.1.9","hbDeviceId":"2103027379102890843548e1e94f1c77","model":"MDL110"}`

**Comment by bwp91** [comment]
You can update to beta version 7.1.3-beta.1 and hopefully this device will be ignored by the plugin :)
