### ISSUE TITLE
Device disappear in homekit

### ISSUE THREAD

**Issue by Stetocasa** [donavanbecker/homebridge-meross#366]
Hi Ben,
some days ago my unique device managed disappear from Homekit.
I'm using the plugin and the config since several months without any issue. 
Now I cannot understand what happen

this is my config

{
    "platform": "Meross",
    "name": "Meross",
    "devices": [
        {
            "name": "Neon",
            "model": "MSS710",
            "deviceUrl": "192.168.178.115",
            "messageId": "4213758c15xxxxxxxx3485f1b3bd3cecbc",
            "timestamp": 1635xxxxx849,
            "sign": "bd705bec6caeaxxxxxd916b2eaea08",
            "serialNumber": "001",
            "showAs": "default"
        }
    ],
    "debug": false,
    "userkey": "f51d4ecd4bcf967f5f3d4db2609e511f",
    "ignoreHKNative": false,
    "debugFakegato": false
}

In the log no error appears

**Comment by bwp91** [comment]
You will find that when you start the plugin, it will show warnings in the logs about your configuration. They are there for a reason, to let you know the config is incorrect.

You should update your config to this:

```json
{
   "platform": "Meross",
   "name": "Meross",
   "userkey": "f51d4ecd4bcf967f5f3d4db2609e511f",
   "singleDevices": [
      {
         "name": "Neon",
         "serialNumber": "XXXXXXXXXXX",
         "connection": "local",
         "deviceUrl": "192.168.178.115",
         "model": "MSS710"
      }
   ]
}
```

The `serialNumber` is 32 digits long and can be found by entering your meross username and password into the configuration and it will appear in the hoobs log when the plugin starts.

**Comment by Stetocasa** [comment]
> You will find that when you start the plugin, it will show warnings in the logs about your configuration. They are there for a reason, to let you know the config is incorrect.
> 
> 
> 
> You should update your config to this:
> 
> 
> 
> ```json
> 
> {
> 
>    "platform": "Meross",
> 
>    "name": "Meross",
> 
>    "userkey": "f51d4ecd4bcf967f5f3d4db2609e511f",
> 
>    "singleDevices": [
> 
>       {
> 
>          "name": "Neon",
> 
>          "serialNumber": "XXXXXXXXXXX",
> 
>          "connection": "local",
> 
>          "deviceUrl": "192.168.178.115",
> 
>          "model": "MSS710"
> 
>       }
> 
>    ]
> 
> }
> 
> ```
> 
> 
> 
> The `serialNumber` is 32 digits long and can be found by entering your meross username and password into the configuration and it will appear in the hoobs log when the plugin starts.

You are the top !!!!
