### ISSUE TITLE
MSL120DBR lights not being recognized.

### ISSUE THREAD

**Issue by guitarguy0124** [donavanbecker/homebridge-meross#367]
### What issue do you have? Please be as thorough and explicit as possible.

Meross App and HomeKit recognizing my new Meross MSL120 BR-30 bulbs, but unlike my new MSL120DR A19 bulbs (all are HomeKit versions), only the A19 bulbs are showing up in Homebridge. 

 The reason I am trying to use HomeBridge, is the fact that you figured out how to enable the adaptive lighting (you are a genius) which isn't available natively, but I can't do it with the BR-30s.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge on my MacBook Pro. homebridge-config-ui-x v4.41.2

* Which version of Homebridge/HOOBS do you have?

v1.3.5

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

homebridge-meross v7.1.2 The latest updates enabled my new A19 MSL120DR (Firmware 4.2.5 Hardware 4.0.0) bulbs to be recognized in Homebridge, but not the BR-30s. A previous update enabled my older Meross A19 MSL120D (Firmware 2.1.4 Hardware 2.0.0) to  use the adaptive lighting.

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSL120DBR
Firmware Version 4.2.1
Hardware Version 4.0.0

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @guitarguy0124 

If you update to the beta version of the plugin:

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Then the MSL120DBR devices should be added to Homebridge/HomeKit :)

**Comment by guitarguy0124** [comment]
I did it and it worked. Thank you so much!

I have two quick other questions if it's not too much trouble.

1. Is the adaptive lighting actually working as is when I enable it, or is there another sensor or something that needs to provide ambient light temp readings? Wasn't sure if it was based on time of day or something else.

2. In your personal setup, how do you handle the duplicate items? Assuming that the adaptive lighting is actually working, that would make the HomeBridge instance of the accessory the superior choice, as that option isn't available natively. In that case, am I better off to remove all the native instances from HomeKit, or just stashing them in a 'holding' room I don't use?

**Comment by bwp91** [comment]
1. The adaptive lighting just works off (a) time of day (warmer colours in the morning/evening and cooler colours at midday) and (b) the current brightness (warmer colours for lower brightness)

2. In fact I don't own any meross native homekit devices, so I've never had to think about this situation. I guess it would be a question of personal preference whether you'd be happy to have the "native" accessories stashed in a homekit room you don't use, or for the more OCD-inclined user they might want to remove it completely!

**Comment by guitarguy0124** [comment]
I just wasn’t sure if you knew how the devices were kept in sync when there are multiple instances. How conflicts were handled and such. Thanks so much!

Creating without compromise,

Justin Stempel

Facebook.com/justin.stempel
Twitter.com/mobilejustin
LinkedIn.com/in/justindesign

**Comment by bwp91** [comment]
The “native” homekit accessory and the “homebridge” accessory have nothing to do with each other at all, completely separate entities, just as if they were controlling separate devices.
