### ISSUE TITLE
Meross msg100

### ISSUE THREAD

**Issue by ForzaSGE** [donavanbecker/homebridge-meross#368]
Hey guys,

I tried to put my msg100 garage door opener into the meross plugin. I would like to do this without entering my meross username and password! Doing so I entered a name and the uuid. As connection type I entered „force local control“. Now there is no way to enter the ip. When I enter username and password there comes up the option to add the ip and the type of garage opener (msg100). But as I already said I do not want to do that (because doing so I get problems with carplay). Do you have an idea what I can do? What do you need for helping me?

setup:
Homebridge 1.3.5
Raspberry pi
Raspbian os 
Node.js Version v14.18.1
Npm Version v6.14.15
Homebridge meross plugin v7.2.0
Msg100
Firmware 4.2.1

The issue started after updating my meross devices, homebride in general and the plugin. 

Before it worked fine. 

Thanks for your help.

**Comment by bwp91** [comment]
You should use the plugin configuration to turn on debug logging, and enter your username and password too. restart the plugin and in the logs you should see your “user key” appear. Copy this key, and enter it in the “meross user key” setting, and then remove your meross username and password.

This will then let you use the garage door in local mode, and the IP field will appear

**Comment by ForzaSGE** [comment]
Thanks a lot! This worked perfect for me!!
