### ISSUE TITLE
Garagedoor state not correct

### ISSUE THREAD

**Issue by EIBHomeControl** [donavanbecker/homebridge-meross#369]
### What issue do you have? Please be as thorough and explicit as possible.
When I close the garage door with the external switch the state is indicating first open and than close.
Also I get 2 push notification from Homekit. First is opening and closed when the door is really closed.
So the opening push notification is not correct.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?

latest

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

raspberry

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

latest

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSG100

### Please paste any relevant logs below.

external push button pressed

[11/11/2021, 08:27:37] [Meross] [Garagentor Cupra] target state [open].
[11/11/2021, 08:27:37] [Meross] [Garagentor Cupra] current state [open].

door is really  closed
[11/11/2021, 08:27:46] [Meross] [Garagentor Cupra] target state [closed].
[11/11/2021, 08:27:46] [Meross] [Garagentor Cupra] current state [closed].

Also i see that in the eve history the open state is added.

**Comment by bwp91** [comment]
Hi, do you have this setup as a local device? or a cloud device?

With plugin debug logging on, can you get me all the logs that appear from a (initially) closed->open->closed cycle?

**Comment by EIBHomeControl** [comment]
Hi, 

Tested several times. At the moment it's working.
So i close the issue for now.

Thanks
