### ISSUE TITLE
Ignore HK Changed Recently

### ISSUE THREAD

**Issue by patrickoleary1977** [donavanbecker/homebridge-meross#370]
Ignoring HK devices was working up until recently.  Now, my devices are showing as HK and also being added by this plugin.  I should only have 2 devices, but they are all showing up.

**Comment by bwp91** [comment]
Hi @patrickoleary1977 

Do you ignore devices by the device id? or with the ignore native devices checkbox?

**Comment by patrickoleary1977** [comment]
The ignore devices check box is what I use.

**Comment by bwp91** [comment]
Nothing has changed with regards to the ignore list so it's strange why your devices have reappeared? Can you provide a list of full model numbers and their hardware versions? - for the models that *shouldn't* be appearing.

Which version of the plugin are you using?

**Comment by patrickoleary1977** [comment]
Ah, I see.  I must have just realized they were there in the Default Room.  The model number is MSL320CPR - the LED Strip lights.  All the others are fine.  

I'm on the latest version of the plugin.

**Comment by bwp91** [comment]
Can you tell me the hardware version of your MSL320CPR? Thanks

**Comment by patrickoleary1977** [comment]
4.0.0

**Comment by bwp91** [comment]
Thanks, this model should be removed automatically if you update to beta version 7.2.1-beta.0

**Comment by patrickoleary1977** [comment]
Yep, that did the trick!

**Comment by bwp91** [comment]
Fab. I will close this now, then the plugin is officially issue-free 🎉🤣
