### ISSUE TITLE
How to find UUID

### ISSUE THREAD

**Issue by Banjo85** [donavanbecker/homebridge-meross#373]
I have a simple and maybe stupid question, how do I find the UUID of my Meross device?

I'm trying to connect the light switch to Homebridge so I can have it in Homekit, and I cant find a 32 digit serial number anywhere on the product?

Ben

**Comment by bwp91** [comment]
If you have your username and password in the plugin config, the uuids of your devices will be shown in the homebridge log when the plugin loads!

**Comment by Banjo85** [comment]
Got it. Thanks
