### ISSUE TITLE
Support for MSS630 3 plug outlet

### ISSUE THREAD

**Issue by tbmorrison** [donavanbecker/homebridge-meross#375]
I was able to connect this plug to my meross app but unable to connect to homebridge.  I have several other vendor smart plugs that are working well.  The issue is with the plugs login attempts to meross, I suppose it's connecting to get the userkey. Here's the error from the log:
[Meross] Disabling cloud client as Username is not exist or password is wrong at connectionHTTP.login (/usr/local/lib/node_modules/homebridge-meross/lib/connection/http.js:65:19).

 I've reinstalled plugin several times and made sure my user/PW were correct.

**Comment by bwp91** [comment]
```
Username is not exist or password is wrong
```

This is the error code that the meross server is providing when trying to log in with the username and password you have entered in the plugin config.

I know you stated your username and password are correct, but maybe worth a double triple check as otherwise meross would not provide this particular error back.

You could also try changing your meross password in the meross app then trying the plugin again with the new credentials

**Comment by tbmorrison** [comment]
I reset PW to [A-Za-z] characters only and it worked. Thank you for the feedback. 
Tom

**Comment by bwp91** [comment]
The MSS630 device is working properly too?

**Comment by tbmorrison** [comment]
Homebridge was working for a short time, but not now. The meross app is able to turn plug off/on but homebridge is only able to detect the off/on state and is unable to change plug state.

**Comment by bwp91** [comment]
Are there any errors in the homebridge log when you try to control the device?

Also, do you still have your meross username and password in the plugin config? or the user key?

**Comment by tbmorrison** [comment]
I'm using: Username and Password. 

Here's the error message. I attempted to use homebridge to turn on plug, it failed, then I turned on plug with meross app and homebridge detected this state.


[05/12/2021, 07:41:24] [Meross] [Smart Outdoor Plug] sending update failed as the request timed out.
[05/12/2021, 07:41:35] [Meross] [Switch 3] sending update failed as the request timed out.
[05/12/2021, 07:44:50] [Meross] [Switch 3] current state [off].
[05/12/2021, 07:44:50] [Meross] [Smart Outdoor Plug] current state [off].
[05/12/2021, 07:50:10] [Meross] [Smart Outdoor Plug] sending update failed as the request timed out.
[05/12/2021, 07:50:16] [Meross] [Switch 3] current state [on].
[05/12/2021, 07:50:16] [Meross] [Smart Outdoor Plug] current state [on].

**Comment by bwp91** [comment]
Can you post your whole meross config json here? Remember to remove your meross username and password.

**Comment by tbmorrison** [comment]
Below is the json for meross{    "name": "Meross",    "username": "xxxxxx",    "password": "xxxxxx",    "userkey": "your-meross-userkey",    "platform": "Meross"}On Dec 5, 2021, at 7:50 AM, Ben ***@***.***> wrote:Are there any errors in the homebridge log when you try to control the device?Also, do you still have your meross username and password in the plugin config? or the user key?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bwp91** [comment]
Please try removing the user key line and restarting to see if this works

**Comment by bwp91** [comment]
I think the plugin is trying to literally use your user key as `your-meross-userkey`.

You don’t need it there if your user and password are present

**Comment by tbmorrison** [comment]
Hi Ben, I deleted the user/PW in the json and replaced with the meross key I grabbed from the debug homebridge restart.  I could not connect to the plug via homebridge.  Do I still need the user/pw field, but leave empty?On Dec 5, 2021, at 8:14 AM, Ben ***@***.***> wrote:I think the plugin is trying to literally use your user key as your-meross-userkey.You don’t need it there if your user and password are present—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bwp91** [comment]
When the user key is configured, the plugin does not have access to your cloud account so cannot download a device list - you need to add them manually into the config, with the device uuid (you may need to enter your username and password just once more so you can obtain the device uuids from the log).

It’s easier to use the homebridge ui to enter the devices in the config manually. enter a label and the device id (uuid) and the relevant options will appear to configure the device. When the user key is set, the connection field must be set to force local control and the IP set in the box that will appear below called device url.

**Comment by bwp91** [comment]
The username and password config options don’t need to exist in the json.
