### ISSUE TITLE
Not Working Device

### ISSUE THREAD

**Issue by bsousa6381** [donavanbecker/homebridge-meross#377]
### What issue do you have? Please be as thorough and explicit as possible.
See below
Joshua's Light] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"1902219817102339080334298f1c3d7e","onlineStatus":1,"devName":"Joshua's Light","devIconId":"device022","bindTime":1625525586,"deviceType":"mss510k","subType":"us","channels":[{}],"region":"us","fmwareVersion":"2.1.7","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"2.1.7","hbDeviceId":"1902219817102339080334298f1c3d7e","model":"MSS510K"}

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

 Homebridge UI

* Which version of Homebridge/HOOBS do you have?

Homebridge 1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

v16.13.1

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

7.3.1

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSS510K - Firmware 2.1.7
MSS510S - Firmware 2.1.6

### Please paste any relevant logs below.

[12/9/2021, 4:40:06 PM] [Meross] [Jacob’s Fan] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"1902217918572639080334298f1c411c","onlineStatus":1,"devName":"Jacob’s Fan","devIconId":"device022","bindTime":1637447309,"deviceType":"mss510k","subType":"us","channels":[{}],"region":"us","fmwareVersion":"2.1.7","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"2.1.7","hbDeviceId":"1902217918572639080334298f1c411c","model":"MSS510K"}
[12/9/2021, 4:40:06 PM] [Meross] [Jacob Closet] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"1902219358763039080334298f1c3bbe","onlineStatus":1,"devName":"Jacob Closet","devIconId":"device022","bindTime":1630873481,"deviceType":"mss510k","subType":"us","channels":[{}],"region":"us","fmwareVersion":"2.1.7","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"2.1.7","hbDeviceId":"1902219358763039080334298f1c3bbe","model":"MSS510K"}

**Comment by bwp91** [comment]
Hi @bsousa6381 

Please update to the beta version 7.3.2-beta.0 of the plugin. These devices should start working :)

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

**Comment by bsousa6381** [comment]
It works - Thank you very much.

I also noticed one other thing.

Model MSS560M - Firmware 3.1.6  - shows up but the dimmer feature does not work.

I try to move from 100% to 50% or more and nothing happens.  I can shut it off and on.

Thank you.
Brian

**Comment by bwp91** [comment]
I might need some extra help from you to be able to debug this properly. Could we message on discord?

https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
Closing this as the original issue is resolved in the beta version and will be available in the next release.

Will fix the brightness issue via discord :)
