### ISSUE TITLE
Old configurations after IP address changes

### ISSUE THREAD

**Issue by dakotaduff** [donavanbecker/homebridge-meross#381]
Hi! Love the plugin. I am running it in hybrid mode. I recently swapped in a new WiFi router and devices are connected just fine, but some of them have new LAN addresses now and some automations and switches from the HomeKit app are triggering the wrong devices. I think this happened when the devices all auto-connected to the new WiFi before I had configured DHCP address reservations. Their current addresses are correct in the Meross iOS app, but they're incorrect in the plugin's "My Devices" section.

Here's an example:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/792309/145840475-aec8341d-8f54-4ba4-9d83-3157ebecbd8c.png">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/792309/145841333-26113355-63e2-41f0-98ec-c0576c4cdd74.png">

As shown here, the IP addresses and MAC addresses are duplicated on these two devices, even though serial numbers differ. The shown IP and MAC do belong to the Desk Light switch, but if I control either switch from HomeKit I am really _only_ controlling the Desk Light. I can control the Master Bath Vanity switch from the Meross iOS app, though.

I do know that clearing the Homebridge cache for the incorrect device does correct this problem, but it comes with the unfortunate side effect of also clearing out any settings from HomeKit. Is there a way to just update the IP & Mac that the plugin has cached?

**Comment by bwp91** [comment]
Hi @dakotaduff can you show your current meross config json?

Just remove your username and password first!

**Comment by dakotaduff** [comment]
Here it is:

{
    "name": "Meross",
    "username": ***@***.***",
    "password": "XXXXXXXX",
    "refreshRate": 20,
    "ignoreHKNative": true,
    "disableDeviceLogging": true,
    "platform": "Meross"
}

**Comment by bwp91** [comment]
Can you try restarting homebridge/the plugin?

Sometimes this can help adjust the accessory info.

The plugin obtains the device info from the meross cloud.

I don't know why in your screenshots, both devices have the same UUID. Are you using an up-to-date browser?

**Comment by dakotaduff** [comment]
Another restart of Homebridge and same result (I'd restarted a few times
previously, as well.)

By "same UUID" do you mean their MAC addresses? I am not sure why. I'm
using what I believe is latest Safari. (Version 15.1 (17612.2.9.1.20)). MAC
address values and IP address values change when selecting any other device.

**Comment by bwp91** [comment]
My mistake, i quickly scanned both UUIDs in the screenshot and somehow decided they were the same!

Can you put the plugin into debug mode and show me all the logs from the plugin restarting, including the first `incoming poll…` messages for your devices which should appear shortly after the plugin finished setting up

**Comment by bwp91** [comment]
Also, can you try updating to the beta version of the plugin…

And in the plugin settings, in the optional settings part, choose force cloud control in the Connection option.

Then restart. Then go back and change the setting back to none. Then restart again.

**Comment by dakotaduff** [comment]
Here are the grepped logs with debug after restart.

**Comment by dakotaduff** [comment]
Switching to beta version with forced cloud and back to stable version did
resolve the issue. Thank you.

**Comment by bwp91** [comment]
On a different note, are you able to confirm that brightness control works from the home app? And the device changes accordingly?

**Comment by bwp91** [comment]
…for the MSS560X

**Comment by dakotaduff** [comment]
Yes. Changes in the Home app are reflected in the Meross app and in the
real world brightness of the lights.

**Comment by bwp91** [comment]
Thanks. It’s only because a few days ago I had to make a manual fix for the MSS560M model, so was just interested if your model worked without the fix.

So, the original issue, in your case it’s fixed but need to find a way to stop this happening again…

It’s such an edge case that a meross device would change ip to that of an other meross device. It’s a case I hadn’t actually thought about…

**Comment by bwp91** [comment]
I've made a fix in the latest beta which should stop this happening again.

The plugin will now compare the accessory uuid with the uuid received from a response. If they are different then the plugin will revert to cloud mode, which in turn should update the accessory with the (new) correct IP of the device.

**Comment by dakotaduff** [comment]
Awesome, thanks!
