### ISSUE TITLE
Device request for `mss310x`, labeled on the box as MSS310R

### ISSUE THREAD

**Issue by aldur** [donavanbecker/homebridge-meross#382]
* **Please explain your feature request in a one or two sentences.**

I am trying to add a `MSS310R` Smart Wi-Fi Plug to Homebridge. The plugin is able to detect the device but unfortunately marks it as not supported, e.g.:

```json
{"uuid":"2011164588807351803848e1e93beebb","onlineStatus":1,"devName":"Bedroom lamp","devIconId":"device045_it","bindTime":1635877462,"deviceType":"mss310x","subType":"it","channels":[{}],"region":"eu","fmwareVersion":"2.1.1","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"2.1.1","hbDeviceId":"2011164588807351803848e1e93beebb","model":"MSS310X"}
```

Could you please point me in the right direction to add support for this device? Thank you!

* **Is your feature request related to a problem? Please describe.**

```txt
[Bedroom lamp] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info [see above]/
```

* **Any particular Meross devices that this relates to?**

The device is labeled on the box as MSS310R, but the logs report `mss3100x`.

**Comment by bwp91** [comment]
Hi @aldur 

Can you update to the beta version of the plugin? This should enable this device to start working.

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by aldur** [comment]
Thank you for the prompt response and fix, it works! 🥳
