### ISSUE TITLE
support for msl320 pro

### ISSUE THREAD

**Issue by enderman3367** [donavanbecker/homebridge-meross#383]
* **Please explain your feature request in a one or two sentences.**

support for meross led light strip  (MSL320 PRO)

* **Is your feature request related to a problem? Please describe.**
no

* **Any particular Meross devices that this relates to?**

no

* **Anything else?**

no

**Comment by enderman3367** [comment]
im new

**Comment by bwp91** [comment]
Hi @enderman3367 

Can you copy and paste the device information that is shown in the homebridge log? 

There should be a log entry saying a device model is unsupported, I need this info.

Thanks!

**Comment by bwp91** [comment]
Do you own this device @enderman3367 ?

**Comment by PanzerSID** [comment]
hallo, ich habe auch das gleiche Problem, mein LED streifen MSL320 (firmware 4.3.3) wird nicht unterstützt:

[3.1.2022, 16:22:26] [Meross] [Decke] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2104163495962490849848e1e96c9e02","onlineStatus":1,"devName":"Decke","devIconId":"device021_un","bindTime":1629380358,"deviceType":"msl320cr","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.3.3","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-

**Comment by bwp91** [comment]
> hallo, ich habe auch das gleiche Problem, mein LED streifen MSL320 (firmware 4.3.3) wird nicht unterstützt:
> 
> [3.1.2022, 16:22:26] [Meross] [Decke] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info: {"uuid":"2104163495962490849848e1e96c9e02","onlineStatus":1,"devName":"Decke","devIconId":"device021_un","bindTime":1629380358,"deviceType":"msl320cr","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.3.3","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-

Hi @PanzerSID 

Please update to the beta version of the plugin:
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

This device should be added to Homebridge :)

**Comment by PanzerSID** [comment]
hallo, das habe ich schon probiert, selbst ein downgrade bis 6.13 hatte keinen erfolg :( 

......ok - jetzt beim zweiten mal hat es geklappt - danke 👍🏻

**Comment by bwp91** [comment]
> hallo, das habe ich schon probiert, selbst ein downgrade bis 6.13 hatte keinen erfolg :(
> 
> ......ok - jetzt beim zweiten mal hat es geklappt - danke 👍🏻

Yes I have literally just updated the beta to support this model!

**Comment by PanzerSID** [comment]
suuuuper - danke 😊 👍🏻

**Comment by enderman3367** [comment]
I am so sorry! I got locked out of my account for a few days so i couldnt respond to your message.
Thank you so much for adding this to the plugin beta!

**Comment by bwp91** [comment]
> I am so sorry! I got locked out of my account for a few days so i couldnt respond to your message.
> Thank you so much for adding this to the plugin beta!

Is your device working? I didn’t realise yours and the other persons model were the same
