### ISSUE TITLE
Can't change brightness (dim) of MSL100R light bulb

### ISSUE THREAD

**Issue by SvenFackert** [donavanbecker/homebridge-meross#384]
### What issue do you have? Please be as thorough and explicit as possible.
I can't change the brightness of MSL100R light bulbs. Apparently the plugin can read the correct brightness, but changing it does only work in the meross app and not in homebridge. I couldn't find any issues regarding this problem. Do you have any idea why it could not be working or any suggestions on how I can debug it?

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge with config-ui

* Which version of Homebridge/HOOBS do you have?
Latest homebridge v1.3.8

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
Latest homebridge-meross v7.4.1

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSL100R light bulbs

**Comment by bwp91** [comment]
Hi @SvenFackert 

I've made a guess fix based off a similar issue with another dimmer model recently.

Can you update to the beta version of the plugin and see if the brightness works through the home app?
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by SvenFackert** [comment]
Hey @bwp91,

I tried the beta and it actually works now. Awesome! Thanks so much - and sorry that I did not find the mentioned issue/ticket before. Have a good one!

Sven

**Comment by bwp91** [comment]
Ah this is good news, thanks for reporting this.

There are obviously some dimmer models that need one extra piece of info sent with the command. Unless it's reported to me, I don't know which models do and which models don't need it!
