### ISSUE TITLE
Please support model MSS426F

### ISSUE THREAD

**Issue by penguinsam** [donavanbecker/homebridge-meross#386]
* **Please explain your feature request in a one or two sentences.**
Please support model MSS426F

{"uuid":"1912052404583290806248e1e9126e6b","onlineStatus":1,"devName":"Bedroom","devIconId":"device033_uk","bindTime":1639317102,"deviceType":"mss426f","subType":"uk","channels":[{},{"type":"Switch","devName":"防潮箱","devIconId":"device001"},{"type":"Switch","devName":"Printer","devIconId":"device001"},{"type":"Switch","devName":"Switch 3","devIconId":"device001"},{"type":"Switch","devName":"Switch 4","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"ap","fmwareVersion":"3.1.1","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-ap.meross.com","reservedDomain":"mqtt-ap.meross.com","firmware":"3.1.1","hbDeviceId":"1912052404583290806248e1e9126e6b","model":"MSS426F"}

* **Is your feature request related to a problem? Please describe.**

* **Any particular Meross devices that this relates to?**
MSS426F

* **Anything else?**

**Comment by bwp91** [comment]
Hi @penguinsam 

Support for MSS426F was included with plugin version 7.4.0.

You should be able to update and get this device working right away!

**Comment by penguinsam** [comment]
> Hi @penguinsam
> 
> Support for MSS426F was included with plugin version 7.4.0.
> 
> You should be able to update and get this device working right away!

Oh good, I just updated and restart homebridge and it works right out of the box now~ brilliant!
