### ISSUE TITLE
Request for support - mss565x

### ISSUE THREAD

**Issue by cbp68** [donavanbecker/homebridge-meross#388]
Was looking to request support for model mss565x.

I did try to use the existing plugin, but got (expected) error:
[12/28/2021, 9:31:12 AM] [Meross] [downstairs hallway] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2102056383821825584448e1e94b15dd","onlineStatus":1,"devName":"downstairs hallway","devIconId":"device062_us","bindTime":1625506427,"deviceType":"mss565x","subType":"us","channels":[{}],"region":"us","fmwareVersion":"3.1.3","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"3.1.3","hbDeviceId":"2102056383821825584448e1e94b15dd","model":"MSS565X"}

This relates to MSS565X - meross Smart Dimmer Switch with Remote, Supports Alexa, Hey Google & SmartThings, 2.4 GHz Wi-Fi Light Switches Dimmable, Remote Control, Schedule, No Hub Needed, Neutral Wire Required

Thanks!
Chris

**Comment by bwp91** [comment]
Hi @cbp68 

Can you update to the beta version of the plugin? This should enable this device to start working.

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by cbp68** [comment]
Thanks, that did the trick!  It is now showing up / supported / working.
