### ISSUE TITLE
Add Exposure of Power Consumption

### ISSUE THREAD

**Issue by TautFlorian** [donavanbecker/homebridge-meross#39]
Hey, i only have a short question.
Will this Plugin expose the power consumption of the outlets to homekit?

**Comment by donavanbecker** [comment]
Currently, I am unaware that this plugin supports that. A pull request is welcome for this.

**Comment by TautFlorian** [comment]
Maybe there could be a reference for the power exposure by looking into homebridge-tuya plugin.
Unfortunately i couldnt try it, but the config seems like there is an option to expose the power consumption.

Reference to: https://github.com/iRayanKhan/homebridge-tuya/blob/master/config-example.MD

**Comment by Marcwa19197** [comment]
Im not sure if Homekit itself can show power consumptions in the UI. (Can someone please clarify this? Maybe with an Screenshot how the UI will look with an official Homekit enabled Power-Meter?)
I did a few requests with HTTP-Catcher to my Meross MSS310 - i can get all the power consumption with following request. Also i was able to get all the data which is saved in on the device.

Request send to device looking at the current consumption via Meross-App:
```
{
  "payload" : {
    "electricity" : {
      "channel" : 0
    }
  },
  "header" : {
    "messageId" : "MSG-ID",
    "method" : "GET",
    "from" : "http:\/\/IP-HERE\/config",
    "payloadVersion" : 1,
    "namespace" : "Appliance.Control.Electricity",
    "sign" : "SIGn-ID-HERE",
    "triggerSrc" : "iOS",
    "timestamp" : TIMESTAMP-HERE
  }
}
```

Response from device:
```
{
    "header": {
        "messageId": "MSG-ID",
        "namespace": "Appliance.Control.Electricity",
        "method": "GETACK",
        "payloadVersion": 1,
        "from": "/appliance/FROM-ID/publish",
        "timestamp": TIMESTAMP,
        "timestampMs": 350,
        "sign": "SIGN-ID"
    },
    "payload": {
        "electricity": {
            "channel": 0,
            "current": 1526,
            "voltage": 2368,
            "power": 253198,
            "config": {
                "voltageRatio": 188,
                "electricityRatio": 100
            }
        }
    }
}
```

**Comment by ChopsKingsland** [comment]
> Im not sure if Homekit itself can show power consumptions in the UI. (Can someone please clarify this? Maybe with an Screenshot how the UI will look with an official Homekit enabled Power-Meter?)
> I did a few requests with HTTP-Catcher to my Meross MSS310 - i can get all the power consumption with following request. Also i was able to get all the data which is saved in on the device.
> 
> Request send to device looking at the current consumption via Meross-App:
> 
> ```
> {
>   "payload" : {
>     "electricity" : {
>       "channel" : 0
>     }
>   },
>   "header" : {
>     "messageId" : "MSG-ID",
>     "method" : "GET",
>     "from" : "http:\/\/IP-HERE\/config",
>     "payloadVersion" : 1,
>     "namespace" : "Appliance.Control.Electricity",
>     "sign" : "SIGn-ID-HERE",
>     "triggerSrc" : "iOS",
>     "timestamp" : TIMESTAMP-HERE
>   }
> }
> ```
> 
> Response from device:
> 
> ```
> {
>     "header": {
>         "messageId": "MSG-ID",
>         "namespace": "Appliance.Control.Electricity",
>         "method": "GETACK",
>         "payloadVersion": 1,
>         "from": "/appliance/FROM-ID/publish",
>         "timestamp": TIMESTAMP,
>         "timestampMs": 350,
>         "sign": "SIGN-ID"
>     },
>     "payload": {
>         "electricity": {
>             "channel": 0,
>             "current": 1526,
>             "voltage": 2368,
>             "power": 253198,
>             "config": {
>                 "voltageRatio": 188,
>                 "electricityRatio": 100
>             }
>         }
>     }
> }
> ```

This is possible with HomeKit, because the HomeKit Eve app can show it and use it for scene triggers. https://images-na.ssl-images-amazon.com/images/I/81kpO5zCKPL._AC_SX425_.jpg

**Comment by lollo18888** [comment]
Hi! Yeah, it is possible and very useful. I have updated the plugin and I have lost all my work.
I had changed the get status request into the request who return also the ampere, volt, and power info and I wrote this info into text files.
With nod-red I called every 5 minutes this and always with nod-red I set the info into an MQTT server.
With another plugin (https://github.com/arachnetech/homebridge-mqttthing#readme) I saw all in the Eve App!!

**Comment by ChopsKingsland** [comment]
so, does that mean it is possible for @donavanbecker to add it to a final release of the Homebridge plugin?

**Comment by donavanbecker** [comment]
See #151

**Comment by chris319** [comment]
I am looking for the same feature, so far I can only see the Smart Plug MSS310 as an "on/off plug" in homekit. I have tried to install this plugin as beta and tried to use force cloud mode, but it can't see the power consumption in homekit or use changes in the consumption for automation scenarios. 
Can anybody point me to the right direction here? Is this at all possible with this plugin and homekit? Or would a total custom implementation be required as shown in the node red example above?

**Comment by bwp91** [comment]
Hi @chris319 

You will need to install the Eve HomeKit app, inside this you should find it shows values for power and voltage.

You can use the config to setup a threshold so the 'outlet in use' value is either on or off depending on whether the power is greater than the value you configured. You can use this to setup automations based on whether the outlet is in use depending on the threshold you configured.

Hope this helps,

**Comment by chris319** [comment]
Thank you very much @bwp91! I am just getting into the whole home automation topic and there is a lot to learn. With your helpful comment I was now able to expose the plugs to home using your plugins and then also utilize the plugs in 3rd party apps like Eve or Home+ which provide the additional power consumption data to be used in automation scenarios. :-)

**Comment by hatty24** [comment]
Hey @bwp91 
The topic is already a bit older but I use Homebridge yust since this year and stumble only now on it.

Unfortunately, the EVE app does not show consumption values of my MSS310. I can see the plugs in the app, control them and include them in automations.
Only the consumption values I can not use.

Has there been any change in the components since last year that the consumption display in EVE no longer works or do I have to activate this function somewhere separately?
If it matters, my Homebridge is running via Docker on Synology NAS. All software and firmware are up to date.

It would be great if you could give me a tip

**Comment by geinzmrk** [comment]
Bump to hatty24's comment - Eve does not show any energy data for meross MSS210P - the meross tool itself on the other hans shows energy consumption properly. Seems like it is a plugin problem
