### ISSUE TITLE
HP110AHK Support

### ISSUE THREAD

**Issue by dwwkelly** [donavanbecker/homebridge-meross#391]
* **Please explain your feature request in a one or two sentences.**
Please add support for HP110AHK, Cherub Baby Machine.

* **Is your feature request related to a problem? Please describe.**
[12/31/2021, 4:48:28 PM] [Meross] [Cherub Baby Machine] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2012163435767790837048e1e941f607","onlineStatus":1,"devName":"Cherub Baby Machine","devIconId":"device054_un","bindTime":1640979155,"deviceType":"hp110ahk","subType":"un","channels":[{}],"region":"us","fmwareVersion":"4.1.11","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.1.11","hbDeviceId":"2012163435767790837048e1e941f607","model":"HP110AHK"}

* **Any particular Meross devices that this relates to?**
HP110AHK

* **Anything else?**

**Comment by bwp91** [comment]
Hi @dwwkelly

I actually have no idea what type of device this is. Could you kinda explain what it is?
Ideally with some screenshots from the meross app of what functionality is available.

Happy to instant message on discord if you prefer.

Thanks and happy new year!

**Comment by dwwkelly** [comment]
@bwp91, thanks for replying so fast.  It's strange, I went to the Meross website and didn't find my device.  I bought it [here](https://www.amazon.com/Sleeping-Compatible-Soothing-Adjustable-Schedule/dp/B084WVW5CG/ref=sr_1_5?crid=3FOTB6S2XT4M3&keywords=meross+noise+machine&qid=1641045890&sprefix=meross+noise+machine%2Caps%2C97&sr=8-5).

The Meross app finds it OK, see screenshot below.

It's a light and noise machine.  The light is exposed in native HK but the noise machine is not.

![IMG_5859](https://user-images.githubusercontent.com/164861/147853026-50520ace-938f-468b-aff4-a19d76e34283.PNG)
.

**Comment by bwp91** [comment]
Thanks.

So if the light is already exposed in homekit natively, it might make sense for the plugin to **just** expose the noise feature?

Could you grab me another screenshot of how the noise functions looks inside the meross app?

**Comment by dwwkelly** [comment]
I think that makes sense.  The only caveat is that once the device is added using the Home app it can't be added in the Meross app.  However, if you add the device in the Meross app then the Home app both apps will work.  I don't think there's any reason that would be a problem though.

Here are some screen caps.  I think the last one is the one you're looking for.

Thanks for looking at this!

![IMG_5872](https://user-images.githubusercontent.com/164861/147860041-43720c27-88d8-4257-9999-4814d8743f75.PNG)

![IMG_5873](https://user-images.githubusercontent.com/164861/147860044-6d9fdb5b-21a2-4fe7-bdce-c3d0f79cf2a0.PNG)

![IMG_5874](https://user-images.githubusercontent.com/164861/147860047-35c789d1-b98a-486d-b5fb-83bc15dcd0d8.PNG)

**Comment by bwp91** [comment]
Would you be happy to message on discord?

To implement this I will need to get some info from you about controlling the device, I find it easier using more instant messaging!

https://discord.gg/cMGhNtZ3tW

**Comment by 2600box** [comment]
Hi, apologies if you would prefer a new issue. I just started to use your plugin for this device. It works great for the audio - though I cannot select any icon except fan?

For the light component, the missing functionality is cycling through RGB. The Meross app has two presets as per the screenshots above.

Is there any way to integrate those with HomeKit? 

Thanks

**Comment by bwp91** [comment]
Hi @2600box 

Have you added the accessory separately to homekit using the "Add Accessory" button?

The device should appear in the home app as a sound system, plus a fan to control the current volume. Unfortunately using a fan is the only "nice" way to implement a volume control.

With regards to the RGB light, I thought this device had HomeKit native capability to control the light?

**Comment by 2600box** [comment]
Yes, I added. So they can be two tiles, or combined as I have them. When combined, the tile shows a speaker, but the fan appears at the top. Am I missing something?

The native HomeKit RGB light configuration allows you to select a colour and temperature, but not an animation. The Meross app allows for animation.

![IMG_402BB1A838D7-1](https://user-images.githubusercontent.com/6595566/148455703-a9a8503f-202c-46c6-9db2-9f00ca9e370b.jpeg)

**Comment by bwp91** [comment]
> So they can be two tiles, or combined as I have them. When combined, the tile shows a speaker, but the fan appears at the top. Am I missing something?

I'm looking at this now, this is Home app behaviour that it shows the status of all the accessories in the room at the top. I thought that if you go to the accessory settings -> Status -> 'Include in Home Status', and turn this off, then the icon goes away, but actually this isn't working in my home app, so maybe I am confusing what this feature does? Could you try this?

**Comment by 2600box** [comment]
I don't think I have "include in Home Status" - mine has "include in Favourites" which doesn't affect the icon at top, but only where the tiles appear below.

**Comment by bwp91** [comment]
It's inside status:

![Screenshot 2022-01-07 at 19 47 05](https://user-images.githubusercontent.com/43026681/148599007-96bcf375-8e86-4125-87f1-0cce68140e5b.png)

**Comment by 2600box** [comment]
I see. That option only appears when they are separate tiles, and as you say, it has no effect on the fan at the top...

Anyway, being able to start the RGB animation from homekit would be really valuable, if at all possible?

**Comment by bwp91** [comment]
> I see. That option only appears when they are separate tiles, and as you say, it has no effect on the fan at the top...
> 
> Anyway, being able to start the RGB animation from homekit would be really valuable, if at all possible?

We could message on discord about the rgb animation? I would need you to do something from your phone and it's easier a bit more real-time convo.

https://discord.gg/cMGhNtZ3tW
