### ISSUE TITLE
Unable to configure local control using plugin WIKI

### ISSUE THREAD

**Issue by miniwi2019** [donavanbecker/homebridge-meross#392]
* **Please explain your feature request in a one or two sentences.**
Try to configure devices locally, no Meross account available since the devices were used with HomeKit so far.

* **Is your feature request related to a problem? Please describe.**
Wiki requires to force local control in connection control - that is not available after installing the plugin. Instead plugin requires username and password. Also there are no "device settings" as described in the WiKi in my homebridge UI plugin settings.

* **Any particular Meross devices that this relates to?**
Meross 210 

* **Anything else?**
IF I try to setup the devices manually, 32 digit UUID is required. No description where to find this number.

**Comment by bwp91** [comment]
Hi @miniwi2019 

Devices needed to added to a meross account to work with this plugin. You can then enter your meross username and password into the config to find both in the homebridge log:

* Your meross userkey which you can use in the config to replace your username and password
* The 32 character device UUID

Then once the userkey is in the config, you can add a config entry for the device in the correct section using the UUID, connection method to force local control and the device IP.
