### ISSUE TITLE
Add MSS210RTL and MSS710 to the list of native HK devices

### ISSUE THREAD

**Issue by Polarium37** [donavanbecker/homebridge-meross#394]
* **Please explain your feature request in a one or two sentences.**
Hello, can you add MSS210RTL and MSS710 to the list of native HK devices ? Thanks 

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular Meross devices that this relates to?**
MSS210RTL
MSS710

* **Anything else?**
Thank you for your time ;-)

**Comment by bwp91** [comment]
Hi @Polarium37 

Are you able to provide me with the hardware versions of both of your devices? This can be found in the meross app or in the homebridge ui under “my devices” tab of the plugin settings

**Comment by Polarium37** [comment]
Hi @bwp91 

Yes, the hardware versions are :
MSS210RTL = 4.0.0
MSS710 = 4.0.0

**Comment by bwp91** [comment]
Thanks, I've just released a new version of the plugin which should remove these devices from your homebridge!

**Comment by Polarium37** [comment]
Wow, what a speed! It works perfectly. Thank you very much
