### ISSUE TITLE
Rename device

### ISSUE THREAD

**Issue by Nissal1983** [donavanbecker/homebridge-meross#395]
I have a question. I changed the name of a socket in the Meross app. In the Homebrigde plugin, however, the old name is still displayed to me, I have already deleted and reinstalled the plugin, the old name of the socket is still displayed to me. How can I change this?

**Comment by bwp91** [comment]
Hi @Nissal1983 

You should try removing this accessory from the homekit cache, you can do this via the homebridge UI in the homebridge settings. 

Accessory names are taken from the meross data only when an accessory is added. After that, they persist the name even if changed in the meross app. This is homekit behaviour and is similar to most other plugins.

If you try this and it still doesn’t work then I can take a closer look!

Thanks

**Comment by Nissal1983** [comment]
it worked.  Thanks for the help
