### ISSUE TITLE
After upgrade from 3.0.0 plugin is not loaded correctly.

### ISSUE THREAD

**Issue by tautf** [donavanbecker/homebridge-meross#396]
### What issue do you have? Please be as thorough and explicit as possible.

I was using old version of this plugin 3.0.0.
Unfortunately after restore of homebridge my setup broke so i decided to install the latest version and switch to the cloud-control feature.

But after uninstalling 3.0.0, rebooting, instaling latest version, im receiving the following error:
```
[15/01/2022, 14:13:06] No plugin was found for the accessory "Meross" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

Config.json:
```
{
            "name": "Meross",
            "username": supersecure",
            "password": "supersecure",
            "connection": "default",
            "debug": true,
            "accessory": "Meross"
        }
```

Plugin is installed correctly.
Complete server reboot did not solve the problem unfortunately

### Details of your setup.
* I use Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.3.9

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Rasperry Pi 1,  Node 16.13.1, npm 8.1.2

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
6.7.1

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
All

**Comment by bwp91** [comment]
hi @TautFlorian 

i believe you need to remove the accessory line from your config, ie,

edit: and add the platform line:

```
{
            "name": "Meross",
            "username": supersecure",
            "password": "supersecure",
            "connection": "default",
            "debug": true,
            "platform": "Meross"
        }
```

**Comment by tautf** [comment]
@bwp91 Thanks for the fast answer, that worked.
All devices have been loaded now, but now im receiving the error: 
`[15/01/2022, 14:31:26] [Meross] [Charger1] failed to request status as the request timed out.`
For every device and im not able to control them.

My settings are forcing cloud control.

**Comment by bwp91** [comment]
Did you sort this out at all?

**Comment by tautf** [comment]
> Did you sort this out at all?

It just worked after some waiting.
