### ISSUE TITLE
Add support for the MSS210R smart plug

### ISSUE THREAD

**Issue by claudio1981** [donavanbecker/homebridge-meross#397]
Please add support for the MSS210R smart plug

This is the info from homebridge log:

`{"uuid":"2005203703919590813348e1e91cba11","onlineStatus":1,"devName":"Lampada scrivania","devIconId":"device045_it","bindTime":1636538365,"deviceType":"mss210r","subType":"it","channels":[{}],"region":"eu","fmwareVersion":"4.1.7","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"4.1.7","hbDeviceId":"2005203703919590813348e1e91cba11","model":"MSS210R"}`

Thanks

**Comment by bwp91** [comment]
Hi @claudio1981 

Please update to the beta version of the plugin. This device should start working for you!

**Comment by claudio1981** [comment]
It works! Thanks a lot!
