### ISSUE TITLE
My devices are not supported ?

### ISSUE THREAD

**Issue by afronob** [donavanbecker/homebridge-meross#403]
Hello :)

### What issue do you have? Please be as thorough and explicit as possible.

My devices are not supported ? or not recognize.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

(1) Homebridge UI-X 

* Which version of Homebridge/HOOBS do you have?

[03/02/2022, 14:52:08] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 1D1E) is running on port ****.

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

OS | Raspbian GNU/Linux Buster (10)
nodejs v14.19.0
nom v6.14.16

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

homebridge-meross v7.7.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

I guess all theses information are in the log below?

### Please paste any relevant logs below.

```
[03/02/2022, 14:52:08] [Meross] [Lumière de notre chambre] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2010190294943490831448e1e9359de4","onlineStatus":1,"devName":"Lumière de notre chambre","devIconId":"device036","bindTime":1642440778,"deviceType":"msl120m","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"2.1.3","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"2.1.3","hbDeviceId":"2010190294943490831448e1e9359de4","model":"MSL120M"}
[03/02/2022, 14:52:08] [Meross] [Lumière de la chambre] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2010196344093490831448e1e93593d9","onlineStatus":1,"devName":"Lumière de la chambre","devIconId":"device036","bindTime":1642418389,"deviceType":"msl120m","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"2.1.3","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"2.1.3","hbDeviceId":"2010196344093490831448e1e93593d9","model":"MSL120M"}
```

**Comment by bwp91** [comment]
Hi @afronob 

If you update to the beta version of the plugin:
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

You should find that they appear and work in Homebridge :)
