### ISSUE TITLE
Unsupported device

### ISSUE THREAD

**Issue by alfredoferrentino** [donavanbecker/homebridge-meross#405]
### What issue do you have? Please be as thorough and explicit as possible.
Device Meross MSS425E not supported 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.4.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
MacOs

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
Homebridge-Meross v7.8.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
Meross MSS425E

### Please paste any relevant logs below.
{"uuid":"2105265982119254800248e1e9719d59","onlineStatus":1,"devName":"Ciabatta","devIconId":"device020_eu","bindTime":1645191067,"deviceType":"mss425ex","subType":"eu","channels":[{},{"type":"Switch","devName":"Switch 1","devIconId":"device001"},{"type":"Switch","devName":"Switch 2","devIconId":"device001"},{"type":"Switch","devName":"Switch 3","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"eu","fmwareVersion":"3.1.1","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"3.1.1","hbDeviceId":"2105265982119254800248e1e9719d59","model":"MSS425EX"}

```

```

**Comment by bwp91** [comment]
Hi @alfredoferrentino 

Please update to new version of the plugin v7.9.0.

You should find this device is added to homebridge and controllable.

Thanks!
