### ISSUE TITLE
Meross Dual Plug MSS120

### ISSUE THREAD

**Issue by LexuSSDriver** [donavanbecker/homebridge-meross#407]
### What issue do you have? Please be as thorough and explicit as possible.

Meross Dual Plugs are not working with Homebridge.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Don't know. Newbie.

* Which version of Homebridge/HOOBS do you have?

HomeBridge v1.4.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Synology 1221+ NAS with DSM 7 Node.js Version | v16.13.2

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

Homebridge UI. homebridge-config-ui-x v4.42.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

Dual Plug Meross Outlet MSS120BR

### Please paste any relevant logs below.
[TV Bridge] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2104290944391890850348e1e96ef7ba","onlineStatus":1,"devName":"TV Bridge","devIconId":"device064_us","bindTime":1646263217,"deviceType":"mss120br","subType":"us","channels":[{},{"type":"Switch","devName":"Light Bridge - OutLet1","devIconId":"device001"},{"type":"Switch","devName":"Party Lights - Outlet2","devIconId":"device001"}],"region":"us","fmwareVersion":"4.2.7","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.2.7","hbDeviceId":"2104290944391890850348e1e96ef7ba","model":"MSS120BR"}

```

```

**Comment by bwp91** [comment]
Hi @LexuSSDriver 

Can you update to the beta version of the plugin and confirm that this device starts working?
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by LexuSSDriver** [comment]
Will do. Will be messing with it again this weekend. Setting up a L3 managed PoE switch in house before I get back on it.

**Comment by LexuSSDriver** [comment]
Installed the Beta of the Meross plugin and the 2 port switches showed up and was able to use the Hide option to show the parts I wanted and not the rest. That seems to work. Thanks for the suggestion!
