### ISSUE TITLE
HomeKit dimmers not excluded

### ISSUE THREAD

**Issue by mozilla33** [donavanbecker/homebridge-meross#408]
Hello. I have 2 Meross dimmers w/ HomeKit already set up, but the plugin does not exclude them like my regular HomeKit-compatible Meross light switches.  The product item numbers are below. Any suggestions?  Thank you 

MSS560X - single pole dimmer
MSS570X - two pole dimmer

**Comment by bwp91** [comment]
Hi @mozilla33 

Would you be able to provide me with the hardware versions for both of these models?

This can be seen on the “my devices” tab of the plugin settings or from the meross app itself.

Thanks!

**Comment by mozilla33** [comment]
Thanks for the reply. Both are hardware version 4.0.0

 

On Mar 8, 2022, at 2:14 AM, Ben ***@***.***> wrote:

﻿
Hi @mozilla33

Would you be able to provide me with the hardware versions for both of these models?

This can be seen on the “my devices” tab of the plugin settings or from the meross app itself.

Thanks!

**Comment by bwp91** [comment]
If you update to the beta version of the plugin
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

You should find that after a restart these devices are removed from your homebridge!

**Comment by mozilla33** [comment]
Works great. Thanks for the help! 

  
Mo Shahsahebi 
***@***.***
(310) 968-1772

On Mar 9, 2022, at 1:51 AM, Ben ***@***.***> wrote:

﻿
If you update to the beta version of the plugin
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

You should find that after a restart these devices are removed from your homebridge!
