### ISSUE TITLE
HomeKit MOD100 not following to "Ignore HomeKit Native Devices" setting

### ISSUE THREAD

**Issue by NateUT99** [donavanbecker/homebridge-meross#410]
* **Please explain your feature request in a one or two sentences.**
I recently purchased the HomeKit-native version of the Meross MOD100 oil diffuser. After adding to the Meross app (so I could get firmware updates), it is also being exposed via this plugin. If there is any information that is necessary to add this as an excluded device, please let me know and I would be more than happy to provide it.

* **Is your feature request related to a problem? Please describe.**

* **Any particular Meross devices that this relates to?**
Meross MOD100HK

* **Anything else?**

**Comment by bwp91** [comment]
Hi @NateUT99 

Yes please if you could get me the hardware version of this device then i can add it to the ignore list. Doing this on a per device reported basis!

Hardware version can be seen from meross app or from the “my devices” tab in the plugin settings.

Thanks!

**Comment by NateUT99** [comment]
Hi @bwp91 - 

Below is the hardware version as reported in the "My Devices" tab. 
Hardware Version | 4.0.0

That said, I've been using the device exposed by this plugin and think I actually prefer how it works versus the "official" one which is exposed as a humidifier. 😂

**Comment by bwp91** [comment]
Do you have other meross devices that are hidden due to the hide homekit native setting?

Obviously if I do add this model to the list then it will be hidden too!

**Comment by NateUT99** [comment]
> Do you have other meross devices that are hidden due to the hide homekit native setting?
> 
> Obviously if I do add this model to the list then it will be hidden too!

Yes, but honestly they are just light strips and I could easily convert them to using this plugin. I think that is what I am going to do... so I guess feel free to add this version for others if you want, but for me I think the answer will be to remove the native integration on the couple light strips and go 100% with this plugin.

Thanks! :)

**Comment by bwp91** [comment]
Hi @NateUT99 
The next version of the plugin will include the MOD100HK in the ignore list for hardware version 4. So if you still have the ignore native devices option enabled then the device will be removed when you update, just to make you aware!

**Comment by NateUT99** [comment]
Apologies for reopening a (old) closed issue, but I wanted to report that the HomeKit variant of the MOD100 is still being advertised by the plugin irrespective of the "Ignore HomeKit Native Devices" option being enabled. Is there any additional information that I can send that can help figure out why?

**Comment by bwp91** [comment]
Hi @NateUT99 
yes this “homekit native” list is being build on a per-case basis as reported on here.
Can you get the hardware version of this model that is homekit native?

**Comment by NateUT99** [comment]
Hi bwp91 - 

I double checked and it looks like it is the version is the same as what I reported originally... I copied the values from the "My Devices" tab in the plugin below.

Model: MOD100
Hardware Version: 4.0.0
Firmware Version: 4.2.17

**Comment by bwp91** [comment]
@NateUT99 
thanks, sorry maybe this one slipped me!

Can you update to 8.2.1-beta.2 beta version to see if this device is ignored now?

**Comment by NateUT99** [comment]
That did the trick... thanks!

```
[06/07/2022, 15:10:14] [Meross] Plugin initialised. Setting up accessories....
[06/07/2022, 15:10:15] [Meross] [Kitchen Accent Lights] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"connection":"hybrid","logging":"standard"}.
[06/07/2022, 15:10:15] [Meross] [Kitchen Accent Lights] initialised with id [2007205049408990821248e1e9261a5f].
[06/07/2022, 15:10:17] [Meross] [Arcade Accent Lights Left] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"connection":"hybrid","logging":"standard"}.
[06/07/2022, 15:10:17] [Meross] [Arcade Accent Lights Left] initialised with id [2007204000789890821248e1e9261a69].
[06/07/2022, 15:10:17] [Meross] [Smart Essential Oil Diffuser] has been removed from Homebridge.
```
