### ISSUE TITLE
HomeKit Power Strip Support for MSS420

### ISSUE THREAD

**Issue by fullphat** [donavanbecker/homebridge-meross#412]
* **Please explain your feature request in a one or two sentences.**

Firstly, thanks for this great plugin!  I have a MSS425F which is HomeKit compatible, but I've just purchased a MSS420 for use outside in a weatherproof box (the HK variants are too big for it) and I knew this plugin would bridge the gap.

The device is presented to HomeKit as 5 switches - is it possible to present it as a HomeKit Power Strip in the same way the 425F appears? 

* **Is your feature request related to a problem? Please describe.**

Problem is cosmetic: it would look better (to me) if it was just one accessory rather than five.

* **Any particular Meross devices that this relates to?**

MSS420 (but suspect related devices as well).

* **Anything else?**

Thanks again for the great plugin!

**Comment by bwp91** [comment]
Thought i'd reply just before it made a year old 😅

do you still use this plugin? if so i'm guessing still a feature request?
