### ISSUE TITLE
Please add support for Meross light switch "MSS510XR"

### ISSUE THREAD

**Issue by jsemroc** [donavanbecker/homebridge-meross#413]
* **Please explain your feature request in a one or two sentences.**
Please add support for Meross light switch "MSS510XR"

* **Is your feature request related to a problem? Please describe.**
After installing the plugin and setting the Meross Username/Password I see the following errors in the Homebridge logs:

[3/25/2022, 9:22:58 AM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 6D3B) is running on port 51435.

[3/25/2022, 9:22:58 AM] [Meross] [Front Porch] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2106237747293255855448e1e9730237","onlineStatus":1,"devName":"Front Porch","devIconId":"device056_us","bindTime":1643656182,"deviceType":"mss510xr","subType":"us","channels":[{}],"region":"us","fmwareVersion":"4.2.2","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.2.2","hbDeviceId":"2106237747293255855448e1e9730237","model":"MSS510XR"}

[3/25/2022, 9:22:58 AM] [Meross] [Garage Light Switch] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2106230536797155855448e1e972fb44","onlineStatus":1,"devName":"Garage Light Switch","devIconId":"device056_us","bindTime":1643480939,"deviceType":"mss510xr","subType":"us","channels":[{}],"region":"us","fmwareVersion":"4.2.2","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.2.2","hbDeviceId":"2106230536797155855448e1e972fb44","model":"MSS510XR"}

[3/25/2022, 9:23:36 AM] [Meross] ✓ Setup complete. This plugin has been made with ♥ by bwp91 from the UK!

* **Any particular Meross devices that this relates to?**
Meross light switch "MSS510XR"

* **Anything else?**

**Comment by bwp91** [comment]
Hi @jsemroc 

Please update to v7.10.0, this device should start working for you!

Thanks

**Comment by jsemroc** [comment]
Excellent! Thank you for the support.
