### ISSUE TITLE
Disabling cloud client as Invalid password at connection

### ISSUE THREAD

**Issue by 45Matches** [donavanbecker/homebridge-meross#416]
What issue do you have? Please be as thorough and explicit as possible.
Just following on from the previous update v7.10.1, all of a sudden I have for the last two days had the connected devices still visible in HomeKit, but not working. See logs below. Seems like a cloud connection issue? I hadn't made any changes or updates for several weeks until today when I updated the plugin to 7.10.1. Error occurred while running 7.10.0 and 1.10.1. Using the recommendation Hybrid Control connection type.

Details of your setup.
Homebridge UI-X

Which version of Homebridge/HOOBS do you have?
Homebridge [v1.4.0]

Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi, Node.js v16.14.2

Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
homebridge-meross v7.10.1

Which Meross devices do you have that are causing issues? Please include product models if applicable.
Garage Door Opener

LOGS
[19/04/2022, 22:00:05] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge C824) is running on port 51950.
[19/04/2022, 22:00:06] [Meross] Disabling cloud client as Invalid password at connectionHTTP.login (/usr/local/lib/node_modules/homebridge-meross/lib/connection/http.js:75:15).
[19/04/2022, 22:00:06] [Meross] ***** Disabling plugin. *****
[19/04/2022, 22:00:06] [Meross] ***** Neither of username and password nor user key has been configured. *****
[19/04/2022, 22:00:06] [homebridge-eufy-security] Launched child bridge with PID 8386
[19/04/2022, 22:00:06] [homebridge-webos-tv] Launched child bridge with PID 8387

**Comment by bwp91** [comment]
Hi @dotandpixel 
This is very strange as the plugin update seemed to fixed this issue for a lot of other users.
Would you be happy to hop onto discord to try and sort this out if i gave you a link?

**Comment by 45Matches** [comment]
Absolutely, happy to help.

**Comment by bwp91** [comment]
https://discord.gg/cMGhNtZ3tW

**Comment by 45Matches** [comment]
- I installed the beta, and got the same credentials error. 
- I then reset my password, and found an issue that resolved my issue.
- My original Meross password was 40 characters, but now there is a limit of 6 - 32. 
- There is no character limit on the password field in the homebridge plugin that matches the Meross app account. 
- Sorry for the run around, it was a simpler issue.
- My Garage Door Opener is now working perfectly again with v7.10.1

**Comment by 45Matches** [comment]
Hi Ben,

Of course
