### ISSUE TITLE
New MRS100 version is Homekit capable

### ISSUE THREAD

**Issue by penalte** [donavanbecker/homebridge-meross#420]
Hi thank you for this plugin, i got the new version of MRS100 and is already homekit capable, the plugin is not hiding it.

MRS100

Smart Roller Shutter Timer

Firmware Revision    7.6.6

Thank you.

**Comment by bwp91** [comment]
Hi @penalte 
Thanks for this.
For my personal knowledge, does this device work with the plugin?
Also are you able to get me the 'Hardware Revision' for this model that is displayed in the meross app or the homebridge ui?
This is the data point I use to hide homekit-compatible devices.
Thanks!

**Comment by penalte** [comment]
Hi, yes this is working with the plugin just like the original MRS100, the board is diferent though.
Hardware version for the homekit capable is 7.0.0.

NON HOMEKIT
![image](https://user-images.githubusercontent.com/17914893/169151754-0ffa2f8e-90ac-4b0f-999e-b6c5ca40083d.png)

HOMEKIT
![image](https://user-images.githubusercontent.com/17914893/169151689-dc0e1ca6-7344-4594-990a-819e4ce05445.png)

**Comment by bwp91** [comment]
Thanks, latest beta version of the plugin should hide this device for you!

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

**Comment by penalte** [comment]
All good now thanks ;)
