### ISSUE TITLE
MSL 610 not supported

### ISSUE THREAD

**Issue by ghdbwise** [donavanbecker/homebridge-meross#422]
[Meross] [Smart Floor Lamp] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2105318173174290751748e1e971fc91","onlineStatus":1,"devName":"Smart Floor Lamp","devIconId":"device_msl610_un","bindTime":1653499512,"deviceType":"msl610","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.2.2","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"4.2.2","hbDeviceId":"2105318173174290751748e1e971fc91","model":"MSL610"}

**Comment by bwp91** [comment]
Hi @ghdbwise 

I’ve had a quick look online about this model and am I right that you have brightness and colour temperature control?

**Comment by ghdbwise** [comment]
You are right. The control panel has 5 steps for brightness and 5 steps for colour temperature. On the remote control there are two timer functions for 60s and 10m
![IMG_1198](https://user-images.githubusercontent.com/17419068/170866530-8b8e7ab8-955f-4e99-b672-31e933234a09.jpg)
![IMG_1197](https://user-images.githubusercontent.com/17419068/170866532-d677e0b7-5853-4aed-b16b-bb1a236e662b.jpg)
.

**Comment by bwp91** [comment]
Are you able to update to the beta version of the plugin? And check if this device works?

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by ghdbwise** [comment]
Great work. On/Off, brightness control, colour temperature everything is working fine. 
Thank you. Regards from Germany.

**Comment by bwp91** [comment]
Ah this is good news! I’ve just released a new version you can update to.

Thanks!
