### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by mltytskr** [donavanbecker/homebridge-meross#425]
### What issue do you have? Please be as thorough and explicit as possible.

I'm seeing the following error in my Homebridge log: [Arcade] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"1811139849028429086134298f1d4cf9","onlineStatus":1,"devName":"Arcade","devIconId":"device020_us","bindTime":1590873094,"deviceType":"sp425ew","subType":"us","channels":[{},{"type":"Switch","devName":"Switch 1","devIconId":"device001"},{"type":"Switch","devName":"Switch 2","devIconId":"device001"},{"type":"Switch","devName":"Switch 3","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"us","fmwareVersion":"2.1.2","hdwareVersion":"2.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/226907/1811139849028429086134298f1d4cf9/1590873096729.jpg","iconType":2,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"2.1.2","hbDeviceId":"1811139849028429086134298f1d4cf9","model":"SP425EW"}

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

I'm using the Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

v1.4.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

v8.1.1, I just installed the plugin for the first time.

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

Smart surge protector model sp425ew

### Please paste any relevant logs below.

```
{"uuid":"1811139849028429086134298f1d4cf9","onlineStatus":1,"devName":"Arcade","devIconId":"device020_us","bindTime":1590873094,"deviceType":"sp425ew","subType":"us","channels":[{},{"type":"Switch","devName":"Switch 1","devIconId":"device001"},{"type":"Switch","devName":"Switch 2","devIconId":"device001"},{"type":"Switch","devName":"Switch 3","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"us","fmwareVersion":"2.1.2","hdwareVersion":"2.0.0","userDevIcon":"https://s3.aws.com/merossapp-userfiles-mobilehub-2004915005/public/device-icon/226907/1811139849028429086134298f1d4cf9/1590873096729.jpg","iconType":2,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"2.1.2","hbDeviceId":"1811139849028429086134298f1d4cf9","model":"SP425EW"}
```

**Comment by bwp91** [comment]
Hi @mltytskr 

What device is this?

**Comment by bwp91** [comment]
Having said that, can you update to the beta version of the plugin to see if this works?

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by mltytskr** [comment]
Yes, the beta version fixed the unrecognized surge protector.

EDIT: Thank you for all your work on this plugin!!
