### ISSUE TITLE
Meross GS559AH smart smoke detector support

### ISSUE THREAD

**Issue by xoatrash** [donavanbecker/homebridge-meross#428]
Requesting support for Meross GS559AH smart smoke detector.

{"uuid":"2108267380861626281248e1e9746e31","onlineStatus":1,"devName":"Room1","devIconId":"device040_un","bindTime":1655383321,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.5.8","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":3,"domain":"mqtt-eu-3.meross.com","reservedDomain":"mqtt-eu-3.meross.com","firmware":"4.5.8","hbDeviceId":"2108267380861626281248e1e9746e3128000000077C","model":"GS559A"}

{"uuid":"2108267380861626281248e1e9746e31","onlineStatus":1,"devName":"Room2","devIconId":"device040_un","bindTime":1655383321,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"4.5.8","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":3,"domain":"mqtt-eu-3.meross.com","reservedDomain":"mqtt-eu-3.meross.com","firmware":"4.5.8","hbDeviceId":"2108267380861626281248e1e9746e312800BF0A50C8","model":"GS559A"}

**Comment by bwp91** [comment]
Hi @xoatrash 

Definitely happy into looking to support this device type as any new model.

However it is a smoke alarm… which is a new device type for this plugin.

Bit of a disclaimer here but please don’t ever consider homebridge and meross plugin a replacement for the meross app with this device.

If and once this device type is implemented, running the plugin alongside the native meross app with this device would be a wise decision 🤘

**Comment by bwp91** [comment]
Can you update to the beta version of the plugin? This device may appear as an accessory.

I'm more interested in the logging that appears at the moment. 

It may be easier to message on Discord if you are able to join there?

https://discord.gg/cMGhNtZ3tW

Thanks!
