### ISSUE TITLE
All work, but tile not appear in HomeKit

### ISSUE THREAD

**Issue by Stetocasa** [donavanbecker/homebridge-meross#434]
Hello, let's start to say that I have all instances updated to las version (plug-in, HB, node, etc)

As screenshot, all works well but icon not appear in HomeKit 

Already reboot several times...![image](https://user-images.githubusercontent.com/70729310/178571593-5a510e5a-ecb6-4d05-b41d-7db1570fa43c.jpeg)![image](https://user-images.githubusercontent.com/70729310/178571604-019cedc9-7f73-4fea-a402-a95bf5805d24.jpeg)

**Comment by Stetocasa** [comment]
@bwp91

**Comment by laszlotuss** [comment]
Are you sure you set **_Connection Type_** and **_Show As_** values properly and not tick **_Hide From Homekit_** ? 

<img width="262" alt="Képernyőfotó 2022-11-18 - 1 24 39" src="https://user-images.githubusercontent.com/2952613/202588472-7695cf78-77f6-491a-8691-231073f23ba5.png">

_Also you should work on those censoring skills 😅_
