### ISSUE TITLE
MSXH0 showing as fan

### ISSUE THREAD

**Issue by igorxmath** [donavanbecker/homebridge-meross#438]
Hi.
Is there a way to show MSXH0 as a humidifer? in my case it is showing as a fan

**Comment by bwp91** [comment]
It shows as a fan because the homekit humidifier accessory also requires a current relative humidity value. And this device does not provide this.

Do you have any meross device that provides a current humidity reading? like a sensor? or indeed a govee or sonoff sensor?

**Comment by igorxmath** [comment]
> It shows as a fan because the homekit humidifier accessory also requires a current relative humidity value. And this device does not provide this.
> 
> Do you have any meross device that provides a current humidity reading? like a sensor? or indeed a govee or sonoff sensor?

Got it, thanks for the reply. I have an aqara temperature and humidity sensor. Is there any way to integrate the sensor into the device?

**Comment by bwp91** [comment]
Unfortunately not, the only reason I mention govee and sonoff is because I maintain these plugins too so can create functionality between my own plugins to do this kind stuff.

**Comment by igorxmath** [comment]
> It shows as a fan because the homekit humidifier accessory also requires a current relative humidity value. And this device does not provide this.
> 
> Do you have any meross device that provides a current humidity reading? like a sensor? or indeed a govee or sonoff sensor?

Would it be possible to provide a fixed relative humidity value?
