### ISSUE TITLE
Smart Floor Lamp showing as native device and through Homebridge

### ISSUE THREAD

**Issue by swampsnake1961** [donavanbecker/homebridge-meross#442]
### What issue do you have? Please be as thorough and explicit as possible.

I have a Meross MSL610 Floor lamp which is native Homekit enabled.  I have the option for native Homekit devices turned off on the plugin, but this lamp still appears.  I have other Homekit mains plugs which don't show through the plugin and are masked as expected

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Ubuntu 20.04.4 
Node.js Version v16.16.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

8.2.0, unknown when the issue first appeared

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSL610 Floor lamp 

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @swampsnake1961 

I’m building this list of homekit native devices on a case by base basis!

Please can you let me know the exact model of this device and the hardware version as shown in the “my devices” tab of the homebridge ui?

**Comment by swampsnake1961** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/50672283/185051201-1b440f5c-a2be-4bf8-91e5-e1719af59033.png">
Hopefully you can get everything you need from this screenshot?

**Comment by bwp91** [comment]
Hi @swampsnake1961 

It's not this screen, it's the tab called "My Devices" in the plugin settings, which should show an entry called 'Hardware Version'

**Comment by maconmatt** [comment]
I have the same problem with a Homekit-certified Meross Outdoor Smart Plug. Model #MSS620 and Hardware Version 7.0.0.

Thanks!
Matt

**Comment by bwp91** [comment]
@maconmatt

hi matt,
can you try the beta version 8.3.2-beta.1? this _should_ remove this device

**Comment by swampsnake1961** [comment]
Hi there - Hardware version 4.0.0

**Comment by bwp91** [comment]
Hi @swampsnake1961 

Can you update to the beta too, v8.3.2-beta.2?

Instructions here for installing beta:
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Let me know if it works, thanks!

**Comment by swampsnake1961** [comment]
I was just trying beta-1 but it would not load after restart, i'll try 2 and report back

**Comment by swampsnake1961** [comment]
Hi. Nightlight is now recognised thanks. beta 1 would not load, it was throwing a cloud error which I did not catch, but beta 2 is loading fine thanks

**Comment by maconmatt** [comment]
@bwp91, beta.2 appears to have fixed the issue. Thanks!
