### ISSUE TITLE
Devices setup directly in HomeKit?

### ISSUE THREAD

**Issue by skazzyskills** [donavanbecker/homebridge-meross#443]
Hi, for some reason, many of my Meross plugs got inputted directly into HomeKit and do not show up in the Meross app. I was hoping the plugin would detect these but it appears not to be the case. Do you know how I get them in? Thanks!

**Comment by bwp91** [comment]
hi, in the config do you have the “ignore homekit native devices” checked?

**Comment by skazzyskills** [comment]
No I don’t. It’s unchecked. Hmm...


Shawn Skalinski
***@***.***

**Comment by swampsnake1961** [comment]
If you added the plugs directly into the Apple Home app then they won't show in the Meross app, and I believe that would mean the plugin won't detect them. If you add the device to your home through the Meross app, even if it's a HomeKit device then it should show in both apps, and the plug-in should detect it then although it would mean the device would appear twice in Home unless the "don't show native HomeKit devices" option ticked.

**Comment by bwp91** [comment]
thanks @swampsnake1961 this may be the issue

**Comment by bwp91** [comment]
which then makes me think, if they are already in homekit then why would you want to use the plugin?

**Comment by skazzyskills** [comment]
Because I have found that these plugs go unresponsive in HomeKit when they were in the app. I was hoping the plug-in would solve that. But I am curious as why people use the plug-in if the devices are HomeKit compatible? I thought I may be missing something?

>

**Comment by swampsnake1961** [comment]
Some Meross devices aren't HomeKit compatible, so I use the plugin to integrate them into Apple's ecosphere. Also I find the some of the automations in the Meross app (like Power off a plug after 3 hours) is a lot more reliable than letting HomeKit take care of it. I still have access to Siri to turn a device on and then let the app's timers to turn it off again.
