### ISSUE TITLE
Energy Monitoring

### ISSUE THREAD

**Issue by pmahli** [donavanbecker/homebridge-meross#448]
First of all thx for such a smart and easy way to integrate Meross devices to HomeKit. 

I was wondering, whether it is possible to not only switch devices on and off, but also to receive energy meter data. 
I am using the smart plug MSS310 with offers power consumption information. It would be beyond awesome to have this information in HomeKit. Is this possible or am I overseeing something? 

Thx!!

Pedro

**Comment by jnmmoore** [comment]
Thanks for the plugin. I would also love to see the energy usage exposed in HK.

**Comment by bwp91** [comment]
Energy monitoring _is_ exposed to homekit by the plugin.

The info, however, is only visible via the Eve app for HomeKit, as this kind of information is not exposed by the Home app itself.

**Comment by Dress13** [comment]
Would it be possible to pass on the value of the EU smart plug mini MSS315 and current electricity consumption to Homekit as Lux? Then automations and scenes depending on the lux value would also be possible.

Thanks in advance.

Daniel
