### ISSUE TITLE
General Question about setup

### ISSUE THREAD

**Issue by anand7825** [donavanbecker/homebridge-meross#449]
So just that I am clear about the setup and I am doing things correctly. My intent is to control my Garage Door opener locally. The steps I followed
1. Created a Meross Account and added my Garage Door Opener
2. Used the credentials from the account with connection type "None" in the plugin settings page.
3. I added the UUID, IP address and Firmware information on the Garage Devices Accessory
I was able to add the Garage Door successfully to Homekit. 

Here is my question , with Connection type "None" and Connection Information in the Garage Door Accessory, are my requests going locally or through the cloud?

**Comment by bwp91** [comment]
Hi @anand7825 

Apologies for delay in response, have you managed to set up okay? Still have these question? Happy to help
