### ISSUE TITLE
Add Support for Smart Wi-Fi LED Bulb with Dimmable Light MSL100

### ISSUE THREAD

**Issue by KutuzoffLeha** [donavanbecker/homebridge-meross#45]
Hello, I'd like to help adding this LED Bulb. 
I'm not good at programming stuff, but I can provide the logs and help with testing. It seems to be similar to other light bulbs.

Turning on and off.
```
{
  "payload" : {
    "togglex" : {
      "onoff" : 1,
      "channel" : 0
    }
  },
  "header" : {
    "messageId" : "XXXXXX",
    "method" : "SET",
    "from" : "http:\/\/XXXXXX\/config",
    "payloadVersion" : 1,
    "namespace" : "Appliance.Control.ToggleX",
    "sign" : "XXXXXX",
    "triggerSrc" : "iOS",
    "timestamp" : XXXXXX
  }
}

{
  "payload" : {
    "togglex" : {
      "onoff" : 0,
      "channel" : 0
    }
  },
  "header" : {
    "messageId" : "XXXXXX",
    "method" : "SET",
    "from" : "http:\/\/XXXXXX\/config",
    "payloadVersion" : 1,
    "namespace" : "Appliance.Control.ToggleX",
    "sign" : "XXXXXX",
    "triggerSrc" : "iOS",
    "timestamp" : XXXXXX
  }
}
```

Changing the luminance. It changes in range from 1 to 100. Not sure what capacity does, but it doesn't change.
```
{
  "payload" : {
    "light" : {
      "channel" : 0,
      "luminance" : 1,
      "capacity" : 4
    }
  },
  "header" : {
    "messageId" : "XXXXXX",
    "method" : "SET",
    "from" : "http:\/\/XXXXXX\/config",
    "payloadVersion" : 1,
    "namespace" : "Appliance.Control.Light",
    "sign" : "XXXXXX",
    "triggerSrc" : "iOS",
    "timestamp" : XXXXXX
  }
}

{
  "payload" : {
    "light" : {
      "channel" : 0,
      "luminance" : 100,
      "capacity" : 4
    }
  },
  "header" : {
    "messageId" : "XXXXXX",
    "method" : "SET",
    "from" : "http:\/\/XXXXXX\/config",
    "payloadVersion" : 1,
    "namespace" : "Appliance.Control.Light",
    "sign" : "XXXXXX",
    "triggerSrc" : "iOS",
    "timestamp" : XXXXXX
  }
}
```

**Comment by donavanbecker** [comment]
Thanks @KutuzoffLeha. potential, any pull requests are welcome.

**Comment by kieranmjones** [comment]
I have just got a pair of these bulbs as well, really good bulbs, but no support currently. I'll take a look and see if I can get it working then do a pull request for it, but I promise nothing, this is not my area of expertise!

**Comment by donavanbecker** [comment]
> I have just got a pair of these bulbs as well, really good bulbs, but no support currently. I'll take a look and see if I can get it working then do a pull request for it, but I promise nothing, this is not my area of expertise!

Thanks @kieranmjones!

**Comment by druth001** [comment]
Anyone have any luck?  I’m trying to add a pair of MSL120 lights, but haven’t gotten them to work yet.

**Comment by PatDal81** [comment]
Same request here, was able to get a MSL120J to work (On/Off) using the standard config (as a normal outlet) but this is it.  No options to change the light/brightness.  

Would be neat to add support for this light bulb!  Thanks!

**Comment by PatDal81** [comment]
Are we using the right channel for this kind of improvement?

**Comment by donavanbecker** [comment]
@PatDal81, @KutuzoffLeha, @druth001 

does dimming lights work for you in the latest beta? #78

**Comment by PatDal81** [comment]
I tried using the model "MSS560" but unfortunately ,setting the brightness is not working.  I can see in homebridge logs it's trying to change the brightness but the light is still 100%

[10/3/2020, 05:07:24] [Lumière Chalet Chambre] MSS560 set brightness to 100
[10/3/2020, 05:07:25] [Lumière Chalet Chambre] MSS560 set brightness to 54
[10/3/2020, 05:07:25] [Lumière Chalet Chambre] MSS560 turned On
[10/3/2020, 05:07:26] [Lumière Chalet Chambre] MSS560 set brightness to 34
[10/3/2020, 05:07:26] [Lumière Chalet Chambre] MSS560 turned On
[10/3/2020, 05:07:26] [Lumière Chalet Chambre] MSS560 set brightness to 31
[10/3/2020, 05:07:26] [Lumière Chalet Chambre] MSS560 turned On
[10/3/2020, 05:08:34] [Lumière Chalet Chambre] MSS560 set brightness to 23
[10/3/2020, 05:08:34] [Lumière Chalet Chambre] MSS560 turned On
[10/3/2020, 05:08:35] [Lumière Chalet Chambre] MSS560 set brightness to 26

Still able to open/close the light.

**Comment by donavanbecker** [comment]
@PatDal81 Use the model you have, not the one in the comments. Which is?

**Comment by PatDal81** [comment]
Model that I'm using is MSL120J.  If I configure it with this model number, I'm getting a simple on/off switch, no dimming capabilities.

**Comment by KutuzoffLeha** [comment]
I don't have those bulbs anymore unfortunately. But can confirm with MSS560 config for MSL420 that only on/off works, not the brightness adjustment.

**Comment by PatDal81** [comment]
Anything else that can be done to help you on this one?

**Comment by kieranmjones** [comment]
I haven’t yet had a chance to have a look at this, although the addition of other dimming devices to the plug-in gives me a good starting point so I’ll have another look as soon as I find some time.

**Comment by rickybright** [comment]
Also looking forward to this being supported. If there's anything that we can do to assist, please let me know.

**Comment by jbouganim** [comment]
@donavanbecker added basic support for the MSL-1XX bulbs if you're interested!
https://github.com/donavanbecker/homebridge-meross/pull/100

**Comment by donavanbecker** [comment]
Added!

**Comment by kieranmjones** [comment]
Working perfectly! Thank you. Sorry I couldn't get it done, just never managed to get the time to work it out.

**Comment by acer589** [comment]
Completely out of my depth here. How long does it usually take for updates to make their way to npm?
