### ISSUE TITLE
[Wohnzimmer] is not supported...

### ISSUE THREAD

**Issue by IT-X-TREME** [donavanbecker/homebridge-meross#450]
{"uuid":"2207127082948460120148e1e99a4fd3","onlineStatus":1,"devName":"Wohnzimmer","devIconId":"device_mts200_eu","bindTime":1664044948,"deviceType":"mts200b","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"7.6.3","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-eu.meross.com","reservedDomain":"mqtt-eu.meross.com","firmware":"7.6.3","hbDeviceId":"2207127082948460120148e1e99a4fd3","model":"MTS200B"}

**Comment by bwp91** [comment]
Hi @IT-X-TREME 

Please update to latest version of plugin
