### ISSUE TITLE
MRS100 missing the switch names after iOS 16 update

### ISSUE THREAD

**Issue by AN1MATEK** [donavanbecker/homebridge-meross#451]
Since updating to iOS 16, the Roller Shutter does not show the button's names anymore (Up/Stop/Down) but rather just "Roller Shutter" on the three of them.

### Details of your setup.
Meross MRS100
Homebridge UI-X v1.5.0
Node.js v16.17.1
homebridge-meross v8.3.1
Raspberry Pi 4 Model B Rev 1.4
```
pi@homebridge:/var/lib/homebridge $ uname -a
Linux homebridge 5.10.63-v7l+ #1496 SMP Wed Dec 1 15:58:56 GMT 2021 armv7l GNU/Linux
```
![WhatsApp Image 2022-10-05 at 10 56 25](https://user-images.githubusercontent.com/15142596/194023769-c6d18c50-0bd2-4934-a395-86954d50ca8d.jpeg)

**Comment by jonathanfontaine91** [comment]
Hello,

Same here

Thx

**Comment by AN1MATEK** [comment]
Yup pretty much Apple changing things on their end as they always do. I am available for any testing, log collection, etc. that would need to be done. Just let me know. 

Thank you very much for the active development of this plug-in. It has made my life MUCH easier :)

**Comment by AN1MATEK** [comment]
So if you go down the inside the Roller Shutter, you will see that consist of a group of 3 Accessories. You can go inside each one and edit their name. Actually if you just delete the "Roller Shutter" name, you will see the default grayed out, which is the actual name from before the update. Why iOS changed the name is beyond me, but this ain't an issue of the plug-in.

**Comment by bwp91** [comment]
Actually this is something I keep meaning to fix, it is possible for the plugin to do this I will get to this!
