### ISSUE TITLE
Trying to Install on Hubitat

### ISSUE THREAD

**Issue by mattries** [donavanbecker/homebridge-meross#456]
I have 2 mss620 smart plugs, one is Hardware/Firmware 3.x and the other is 6.x. I have the the 3.x working great with the info from the install page but I'm struggling with where to put the userkey, etc for v6. Thanks for your help!

**Comment by bwp91** [comment]
Hi @mattries sorry for lack of response - please re-open if you still need some assistance

**Comment by mattries** [comment]
Nope! I don't have it working yet, still not sure where to put the userkey and all that for my v6 plug.
