### ISSUE TITLE
MSG100 Trigger Duration Change

### ISSUE THREAD

**Issue by alizhd** [donavanbecker/homebridge-meross#457]
I am trying to change the trigger duration to less than 0.5 seconds for MSG100. My garage door opener only opens if its around 0.1-0.2 seconds otherwise it just turns on the lights as anything longer is lights on. 

I was wondering if there is a way to set the duration manually. The app right now only allows 0.5 seconds.

**Comment by bwp91** [comment]
Hi @alizhd sorry for the delayed response. the plugin cannot do anything _more_ than the meross app can
