### ISSUE TITLE
MOD100 as humidifier rather than fan?

### ISSUE THREAD

**Issue by FezVrasta** [donavanbecker/homebridge-meross#459]
* **Please explain your feature request in a one or two sentences.**

Would it be possible to expose the oil diffuser as humidifier rather than a fan? Maybe have it configurable?

* **Is your feature request related to a problem? Please describe.**

* **Any particular Meross devices that this relates to?**

MOD100 oil diffuser

* **Anything else?**

**Comment by bwp91** [comment]
closing this issue, as similar to 

https://github.com/bwp91/homebridge-meross/issues/400
