### ISSUE TITLE
Smart Plugs should be Display as Outlets instead of Switch (or both ?)

### ISSUE THREAD

**Issue by laszlotuss** [donavanbecker/homebridge-meross#461]
On the left I have my 2 Tapo outlets _also thru Homebridge_ with can be displayed as Outlet, while the Smart Plug is a Meross one which displayed as a Switch.

![IMG_8214](https://user-images.githubusercontent.com/2952613/202460639-9a3ca17e-1b28-430d-875a-b67143910b52.jpg)

**Comment by bwp91** [comment]
Hi @laszlotuss 

You can use the plugin config to choose how these accessories appear (as a switch or outlet or even an air purifier if you want!)

You just need the long device uuid that is shown in the log when the plugin starts and the configuration items will appear in the settings

**Comment by laszlotuss** [comment]
Hey @bwp91 

So I fetched the long device uuid and tried to set it up manually as an outlet, yet not it's not appearing now.

```
[Meross] [Smart Plug] not initialising cloud device as ignored or configured locally.
[Meross] [undefined] could not be initialised as Cannot read properties of undefined (reading 'toUpperCase') at default.initialiseDevice (file:///volume2/homebridge/node_modules/homebridge-meross/lib/platform.js:410:42).
```

Am I missing something ?

<img width="485" alt="Képernyőfotó 2022-11-18 - 0 43 03" src="https://user-images.githubusercontent.com/2952613/202583914-126aef60-9d0f-4182-bddb-48a823559746.png">

**Comment by laszlotuss** [comment]
Okay, I guess it doesn't like deviceUrl if it's a default type connection.

Bot now it works and appears as an Outlet as it should be. Thank you for your help.

<img width="478" alt="Képernyőfotó 2022-11-18 - 1 17 22" src="https://user-images.githubusercontent.com/2952613/202588190-ea83477b-e39a-436d-a121-88ecc8b13d85.png">
