### ISSUE TITLE
Unable to login to meross 

### ISSUE THREAD

**Issue by FunnyDevs** [donavanbecker/homebridge-meross#462]
* Homebridge UI-X
* Homebridge 1.5.1
* MacOs
* 8.4.0

Hello, i'm unable to login to meross platform. 
The message at homebridge startup is: 
Disabling cloud client as login failed - {"apiStatus":1006,"sysStatus":0,"info":"","timeStamp":1669016924,"data":{}} at default.login (file:///usr/local/lib/node_modules/homebridge-meross/lib/connection/http.js:76:15).

Which could it be the problem?

**Comment by rwbisme** [comment]
I have the same issue running on Raspberry Pi 4.  

Node.js Version | v18.12.1
Homebridge 1.6.0

**Comment by bwp91** [comment]
Hey @FunnyDevs and @rwbisme is this still an issue?

**Comment by rwbisme** [comment]
Not for me.  I did some upgrading of JSON and others and it is good now.  Thanks.
