### ISSUE TITLE
MSH300HK PUSH request

### ISSUE THREAD

**Issue by andreground** [donavanbecker/homebridge-meross#466]
Hello

I managed to integrate practically everything needed to control the thermostatic valves locally, with the exception of this single message that the MSH300HK keeps sending because it doesn't receive the adequate response.

Have you ever come across a similar message?
Can you direct me on what the correct answer would be?

Thank you

{
"header": {
"messageId": "b58cd1cadba3eb43ae01481cab47XXXX",
"namespace": "Appliance.Hub.SubdeviceList",
"method": "PUSH",
"payloadVersion": 1,
"from": "/appliance/XXX/publish",
"timestamp": 1669216809,
"timestampMs": 592,
"sign": "de62fe92ac87f005ea0d4db9822eXXXX"
},
"payload": {
"subdeviceList": {
"subdevice": [
{
"id": "0300XXXX",
"status": 1,
"time": 1669216199,
"hardware": "1.1.5",
"firmware": "6.1.7"
}
],
"needReply": 1
}
}
}

**Comment by bwp91** [comment]
Hi @andreground 

are you talking about extending the plugin that you have done or something separate?

Doesn't matter either way!
