### ISSUE TITLE
MSS425ER support missing

### ISSUE THREAD

**Issue by craeft-io** [donavanbecker/homebridge-meross#467]
* **Please explain your feature request in a one or two sentences.**
My home bridge Installation tells me, that support for device MSS425ER is missing

* **Is your feature request related to a problem? Please describe.**
Cannot find this device in home bridge

* **Any particular Meross devices that this relates to?**
MSS425ER

* **Anything else?**

Bug report from Homebridge logs:
{"uuid":"2104302773553790850748e1e97036a9","onlineStatus":1,"devName":"Steckdosenleiste Schreibtisch","devIconId":"device020_eu","bindTime":1669538341,"deviceType":"mss425er","subType":"eu","channels":[{},{"type":"Switch","devName":"Bett","devIconId":"device001"},{"type":"Switch","devName":"Schreibtisch","devIconId":"device001"},{"type":"Switch","devName":"Weihnachtsbaum","devIconId":"device001"},{"type":"USB","devName":"USB Schreibtisch","devIconId":"device001"}],"region":"eu","fmwareVersion":"4.2.3","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"4.2.3","hbDeviceId":"2104302773553790850748e1e97036a9","model":"MSS425ER"}

**Comment by bwp91** [comment]
Hi @timstrakeljahn 

Thanks for this.

Does your model support homekit natively?

**Comment by craeft-io** [comment]
Yes it does.
This is my workaround to just add it to the HomeKit app.

**Comment by bwp91** [comment]
Thanks, please install the beta version of the plugin, this device should start working

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

**Comment by craeft-io** [comment]
Thank you very much ☺️
Now it works
