### ISSUE TITLE
New Device: Meross MOD150 Smart Essential Oil Diffuser

### ISSUE THREAD

**Issue by NateUT99** [donavanbecker/homebridge-meross#471]
* **Please explain your feature request in a one or two sentences.**
Meross has released a new version of their smart diffusers; MOD150. While it does have native HomeKit support, I find the humidity sensor in these units to be very unreliable (ie. always reading 98-100% in HomeKit), which means the diffuser stops working. I would like to be able to add this device into HomeKit via the plugin, so that is exposed as a fan (and hopefully bypasses the above issue since it works fine via the Meross app). Here is the log info that is provided when the plugin starts up:

`{"uuid":"2204274164093164110248e1e9918fad","onlineStatus":1,"devName":"Smart Essential Oil Diffuser","devIconId":"device_mod100_un","bindTime":1666468462,"deviceType":"mod150","subType":"un","channels":[{}],"region":"us","fmwareVersion":"4.2.2","hdwareVersion":"4.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":1,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","firmware":"4.2.2","hbDeviceId":"2204274164093164110248e1e9918fad","model":"MOD150"}`
* **Is your feature request related to a problem? Please describe.**

* **Any particular Meross devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Hi @NateUT99 

Please install the beta of the plugin, this device should be recognised and (hopefully) uses the same command structure as the MOD100.

Note that if you have the "Hide Native HomeKit" global option checked then this device will still be hidden in homebridge.

**Comment by NateUT99** [comment]
@bwp91 thanks; that seems to have worked as expected. 

Now I just need to figure out a way to configure the wifi settings on this model without having to pair it to HomeKit directly... seems like it should be possible since it supports Alexa/Google, but for the life of me I can't get it to direct it natively in the Meross app. :/

**Comment by bwp91** [comment]
'fraid I can't help with that, surely you can add it to the meross app like any other device?

**Comment by NateUT99** [comment]
> 'fraid I can't help with that, surely you can add it to the meross app like any other device?

Unfortunately it doesn't seem to let me... it doesn't show up in the automatic scan, and if you select the device from the list it requires you to add it to HomeKit. I found some other projects that appear to be able to connect and configure wifi (with the intent of connecting Meross devices to a local MQTT server), so perhaps I'll get that a try.

As far as this issue is concerned, I think we can close it. :)
