### ISSUE TITLE
[MTS100H] - Feature request

### ISSUE THREAD

**Issue by KiraPC** [donavanbecker/homebridge-meross#472]
Hi,

Thanks for your work.

Do you think you will add support to MTS100H Smart Thermostat Valve?

**Comment by bwp91** [comment]
Hi @KiraPC 

I can only add support for devices once someone owns one and either confirms it already works or work together to implement it.

Since the plugin already supports the MTS100V3, this device may already work

**Comment by KiraPC** [comment]
Hi, thanks for reply.

I think I'm doing something wrong because I cannot see the list of my devices.
Il 18 dic 2022, 15:44 +0100, Ben ***@***.***>, ha scritto:

**Comment by bwp91** [comment]
is it added to the same meross account as you have configured in the plugin settings?

**Comment by KiraPC** [comment]
Sure.

I cannot see any error in the startup logs
Il 18 dic 2022, 17:22 +0100, Ben ***@***.***>, ha scritto:

**Comment by bwp91** [comment]
Can you show all your plugin startup logs here? feel free to obfuscate any device ids or names etc

**Comment by KiraPC** [comment]
HI,

These are my logs filtered by meross plugin
 ```logs
[12/18/2022, 9:33:48 PM] Loaded plugin: homebridge-meross@8.4.0
[12/18/2022, 9:33:48 PM] Registering platform 'homebridge-meross.Meross'
[12/18/2022, 9:33:48 PM] [Meross] Initializing Meross platform...
[12/18/2022, 9:33:48 PM] [Meross] Initialising plugin v8.4.0 | System darwin | Node v16.15.0 | HB v1.6.0 | HAPNodeJS v0.11.0...
[12/18/2022, 9:33:48 PM] [Meross] Plugin initialised. Setting up accessories....
[12/18/2022, 9:33:51 PM] [Meross] ✓ Setup complete. Have a feature request? Visit https://bit.ly/hb-meross-issues to ask!
[12/18/2022, 9:35:51 PM] [Homebridge UI] [homebridge-meross] Terminating child process...
[12/18/2022, 9:35:51 PM] [Homebridge UI] [homebridge-meross] Child process ended
```

**Comment by bwp91** [comment]
So there are no devices in your meross account that you configured in the plugin?

**Comment by KiraPC** [comment]
I've enabled the debug mod and now I have a new log:

[Smart Hub] not initialising cloud device as matched as HomeKit native model.

I think I figured out.

I have 2 new model of the SmartValve that are ready for homekit and an old model that it is not, but the HB plugin is fetching just the Hub (that is the new version) and it is skipping all the devices connected.

**Comment by bwp91** [comment]
for now can you disable the “ignore native homekit” option?

**Comment by KiraPC** [comment]
Yes I did, and now they are displayed

**Comment by bwp91** [comment]
and working?

**Comment by KiraPC** [comment]
Yes, they are correctly working. 

Thank you so much for support and sorry for disturb :D

**Comment by bwp91** [comment]
If you update to the latest version of the plugin you should be able to re-enable the "ignore native homekit" option with these MTS devices still appearing in your homebridge

**Comment by KiraPC** [comment]
@bwp91 I updated to latest version, I re-enabled the flag, now all the devices appear, also the 2 homekit native

**Comment by bwp91** [comment]
what are the models of the homekit native devices?

**Comment by KiraPC** [comment]
The model shown by the plugin is the same for all the devices "MSH300HK" but it is the model number of the Hub the devices are connected.

**Comment by bwp91** [comment]
Can you tell from the Meross app whether the existing HomeKit ones are `MTS100V3` or `MTS150`? also in the meross app does it provide a hardware version for the valves rather than for the main hub?

**Comment by KiraPC** [comment]
Yes

Basically, MTS100V3 is an hub compatible with HomeKit if the smartValve connected are MTS150, but if I connect the oldest valve MTS100 that are not compatible with homekit.
