### ISSUE TITLE
MSL100R Showing up via plugin but is HomeKit native.

### ISSUE THREAD

**Issue by Tongo91** [donavanbecker/homebridge-meross#473]
MSL100R is showing up via the plug-in but is HomeKit native so it should be disabled.

**Comment by bwp91** [comment]
can you let me know the hardware version?

**Comment by Tongo91** [comment]
Of course, Hardware version is 4.0.0 and firmware 4.1.7

**Comment by bwp91** [comment]
great thank you! if you update to the beta version of the plugin you should find this device is now hidden.

note to anyone reading in the future:
my list of homekit native devices is purely based on user feedback so please let me know!

**Comment by Tongo91** [comment]
That worked for me, thanks a lot!
