### ISSUE TITLE
Improve security, myQ cloud password is visible, not encrypted or scrambled

### ISSUE THREAD

**Issue by LeoOttawa** [donavanbecker/homebridge-meross#474]
* **Please explain your feature request in a one or two sentences.**
The myAQ plugin password is in plain text and visible in the config.json file or directly in the Homebridge configuration editor.
Wouldn't it be better if it was in base64 or some other kind of encryption instead of plain text, even in an encrypted file.

* **Is your feature request related to a problem? Please describe.**
Security flaw by having the password visible in plain text instead of an encrypted or scrambled format.

* **Any particular Meross devices that this relates to?**
No

* **Anything else?**
Example - Current
{
            "name": "Meross",
            "username": "yourmail@domain.com",
            "password": "HelloWorld1234",
            "connection": "default",
            "platform": "Meross"
        }

Example - hidden password in base64
{
            "name": "Meross",
            "username": "yourmail@domain.com",
            "password": "SGVsbG9Xb3JsZDEyMzQK",
            "connection": "default",
            "platform": "Meross"
        }

**Comment by bwp91** [comment]
Hi @LeoOttawa 

You can already use a base64 version of your password in the meross plugin config 😉

**Comment by LeoOttawa** [comment]
Thanks Ben.  I am new to Homebridge and was expecting and looking for some sort of password encryption support in the plugin config UI.  I used base64encode.org, updated the Homebridge config file and restarted the server - all good.  Thanks!
