### ISSUE TITLE
Hoobs 4.2.8 Homekit 1.50 Any verions of Meross won't intsall. 

### ISSUE THREAD

**Issue by lesbranton** [donavanbecker/homebridge-meross#479]
### What issue do you have? Please be as thorough and explicit as possible.
When I updateed to 4.2.2 Meross was saying couldnt install because of Homekit version was too old.  1.4.0 and need 1.5.0 Now HOOBS Install Meross and keeps coming up with WARNING plugin site unavailable.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
3 Hoobs

* Which version of Homebridge/HOOBS do you have?
4.2.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 3B+
Node.js version 16.19.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
Trying to install any version doesn't work. Homebridge version is 1.5.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

In the Meross app devices work fine.  In Hoobs and trying to get it into HomeKit doesn't work.

### Please paste any relevant logs below.

```
1/11/2023, 11:00:19 PMWARNINGunhandled rejection: undefined
1/11/2023, 11:00:20 PMWARNINGplugin site unavailable
1/11/2023, 11:07:01 PMWARNINGplugin site unavailable
1/11/2023, 11:11:15 PMWARNINGplugin site unavailable
1/11/2023, 11:12:01 PMWARNINGplugin site unavailable
1/11/2023, 11:12:02 PMyarn add v1.22.19
1/11/2023, 11:12:02 PMinfo No lockfile found.
1/11/2023, 11:12:03 PM[1/4] Resolving packages...
1/11/2023, 11:12:03 PMerror An unexpected error occurred: "https://registry.yarnpkg.com/homebridge-meross: getaddrinfo EAI_AGAIN registry.yarnpkg.com".
1/11/2023, 11:12:03 PMinfo If you think this is a bug, please open a bug report with the information provided in "/var/lib/hoobs/merossbridge/yarn-error.log".
1/11/2023, 11:12:03 PMinfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by bwp91** [comment]
Hi @lesbranton 

This may be an issue with HOOBS that needs to be fixed, see

https://support.hoobs.org/topics/connectivity/plugin-site-unavailable
