### ISSUE TITLE
Ignoring Meross native hk devices

### ISSUE THREAD

**Issue by bobbergen** [donavanbecker/homebridge-meross#481]
### What issue do you have? Please be as thorough and explicit as possible.
The only way I can get the Meross plugin to ignore native hk devices is to not insert cloud credentials and add devices individually into the plugin with name, uuid, ip address, etc. 
Is this expected behavior ?

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
V1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Windows 11 Pro in a Hyper-V machine
Node.js v18.13.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
V8.5.1-beta.3, first install 

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
HomeKit native MSS110, MSS510XR maybe others
Total of 14 out of 39, all at least 1 year old, no new models, the non-native hk devices that I’m adding are MSS110

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi,

Please can you provide a list of unique models that are homekit native along with their hardware versions?

I ignore these devices on a case by case basis from user feedback as obviously i cannot own every model!

**Comment by bobbergen** [comment]
Native to HomeKit
MSS110     4.0.0
MSS110     7.0.0
MSL120D     4.0.0
MSL120DR   4.0.0
MSS510X     4.0.0
MSS510XR   4.0.0
MSS550X     4.0.0
MSS560X     4.0.0
MSS570X     4.0.0
MSS620       7.0.0

Non-native
MSS110     2.0.0

**Comment by bwp91** [comment]
Ah, are you aware there is an option in the configuration to hide native homekit devices?

If you enable this, most of these models would get removed.

In the new beta version I have just added the rest, so if you update to the beta and enable this option, all these models will be hidden from Homebridge.

**Comment by bobbergen** [comment]
Yes, I had that option enabled and yet 14 of my 40 or so Meross devices were doubled

**Comment by bwp91** [comment]
These may have been the models that weren’t added to my list, they are updated in the beta version now.

**Comment by bobbergen** [comment]
Thanks for updating, installed the latest beta, inserted my Meross account credentials and all is good.

**Comment by bobbergen** [comment]
The list I gave you is all my Meross devices, not the ones that were doubled. Couldn’t remember which ones specifically weren’t recognized as HomeKit native.

**Comment by bwp91** [comment]
The only ones i had missing were the MSS110 (v4) and MSS510XR 👍🏻

**Comment by bobbergen** [comment]
Thank you

**Comment by bwp91** [comment]
Thanks for your support 🙂
