### ISSUE TITLE
Requesting support for the Smart Wi-Fi 3-Way Dimmer Switch Kit, MSS570 US

### ISSUE THREAD

**Issue by g00gl3** [donavanbecker/homebridge-meross#488]
* **Please explain your feature request in a one or two sentences.**
Requesting support for the Smart Wi-Fi 3-Way Dimmer Switch Kit, MSS570 US

* **Is your feature request related to a problem? Please describe.**
Requesting support for the Smart Wi-Fi 3-Way Dimmer Switch Kit, MSS570 US

* **Any particular Meross devices that this relates to?**
Smart Wi-Fi 3-Way Dimmer Switch Kit, MSS570 US
https://www.amazon.com/Dimmable-Halogen-Incandescent-Assistant-Control/dp/B07QPD9QBH
https://www.meross.com/smart-switch/three-way-dimmer-switches/42

* **Anything else?**
{"uuid":"1904201848988039083334298f1e2506","onlineStatus":1,"devName":"Stairway Light","devIconId":"device051_us","bindTime":1584643919,"deviceType":"mss570m","subType":"us","channels":[{}],"region":"us","fmwareVersion":"2.1.6","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"cluster":2,"domain":"mqtt-us-2.meross.com","reservedDomain":"mqtt-us-2.meross.com","firmware":"2.1.6","hbDeviceId":"1904201848988039083334298f1e2506","model":"MSS570M"}

Thanks for your time & efforts!

**Comment by bwp91** [comment]
Hi @g00gl3 

Can you please update to the beta version of the plugin to see if this device is working?
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by g00gl3** [comment]
Thanks for the quick response, Ben!  

I updated the plugin to the latest beta version, v8.5.4-beta.1 - beta.  The 3-way dimmer (MSS570 US) device is now recognized and functions for on/off via Homebridge.  

However, the 3-way dimmer (MSS570 US) device defaulted to be a switch where I expected it to be a light with dimming capability.  The other Meross smart light switches with dimming capabilities I already have setup via Homebridge were recognized by default as such.  Is there a configuration change I may make?  I didn't see any option on my end to enable the dimming functionality for this device manually but of course may have missed that.

Thanks again!

**Comment by bwp91** [comment]
Hi @g00gl3 sorry I should have realised from the issue title that this was a dimmer.
Please update to the new beta.
You will probably need to remove this accessory from the homebridge cache as the lightbulb service will now be added but the switch won't be removed - hense the reason for the need to reset in the homebridge cache

**Comment by g00gl3** [comment]
Thanks again.  I updated to v8.5.4-beta.2 - beta, cleared the light from cache, and restarted Homebridge.  It was then detected as a light with dimming functionality as expected!  Cheers!
