### ISSUE TITLE
MTS200B support

### ISSUE THREAD

**Issue by akargas** [donavanbecker/homebridge-meross#490]
Hi, I was wondering if you could add support for the Meross MTS200B Thermostat. Thank you for your work so far.

**Comment by bwp91** [comment]
Hi @akargas in fact this device is a work in progress right now!

**Comment by akargas** [comment]
Thank you for your immediate response. I will be waiting

**Comment by DeadlyVirez** [comment]
according to your release notes for version [8.3.0](https://github.com/bwp91/homebridge-meross/blob/latest/CHANGELOG.md#830-2022-09-25) it should be supported.

Do I need to configure anything else?

**Comment by bwp91** [comment]
Hi @DeadlyVirez closing this issue in favour of

https://github.com/bwp91/homebridge-meross/issues/401

will update there
