### ISSUE TITLE
MS100 local control not working after updating to latest firmware

### ISSUE THREAD

**Issue by cryptobrian** [donavanbecker/homebridge-meross#493]
MS100 Firmware 4.2.6
Meross Homebridge plugin 8.5.3

When forcing Meross garage door opener to only connect via local mode, AND, garage door opener is restricted from accessing the external internet, it doesn’t seem like local commands are working anymore.  This was not an issue with the prior MS100 firmware. Unfortunately, there is no way to downgrade. 

[2/5/2023, 9:03:01 PM] [Meross] [Garage Door Smart] sending update: {"header":{"from":"http://192.168.0.195/config","messageId":"72djz3sbfibsrag2vzz8q375tnum65lz","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"15d5fff024c24d1ecad424657d0027ab","timestamp":1675648981,"triggerSrc":"iOSLocal","uuid":"200820147142263610123123123123"},"payload":{}}.

[2/5/2023, 9:03:10 PM] [Meross] [Garage Door Smart] failed to request status as timeout of 9000ms exceeded at RedirectableRequest.handleRequestTimeout (file:///homebridge/node_modules/homebridge-meross/node_modules/axios/lib/adapters/http.js:570:16).

Allowing internet access back to the meross plug fixes the issue - but defeats the purposes of wanting to have a locally controlled set up.

**Comment by iTim314** [comment]
@cryptobrian How did you resolve this? I’m having the same issue.

**Comment by bwp91** [comment]
is this still an issue?

**Comment by cryptobrian** [comment]
Think it was user error. Pausing a device with Eero routers now seems to block LAN access as well.  Was never able to fully replicate as I have wyzecams internet paused with Eero router can still be accessed locally.  

Unless Meross did something with their firmware to restrict if cannot reach internet - similar behaviour with Eufy indoor 2k cameras.  

I ended up just letting meross connect back to internet.

**Comment by bwp91** [comment]
If you block the device with the eero app again, can you control via the meross app?

**Comment by cryptobrian** [comment]
Nope. The device goes offline in the Meross app.

**Comment by bwp91** [comment]
okay. it still could be that the payload has changed with the firmware update to control this device locally. i assume the meross app tries to control it locally first like other devices.

If you have some time it would be cool to try and see if the payload has changed.

Happy to message on discord if easier, i can tell you what i need
https://discord.gg/cMGhNtZ3tW
