### ISSUE TITLE
HomeKit msl100dnot following to "Ignore HomeKit Native Devices" setting

### ISSUE THREAD

**Issue by Xanderco** [donavanbecker/homebridge-meross#499]
### What issue do you have? Please be as thorough and explicit as possible.
I have 4 of these devices, they are HomeKit compatible and I have the  "Ignore HomeKit Native Devices" setting on, but they still show on the Home App

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
8.5.3, Nope, right after the bulbs were added to the Meross account

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
msl100d
FW 4.1.8
HW 4.0.0

**Comment by bwp91** [comment]
Hi @Xanderco 

Thanks for reporting this. Please update to the beta version of the plugin. You should find these models are now removed!
