### ISSUE TITLE
Connecting to Meross

### ISSUE THREAD

**Issue by 1987marco1987** [donavanbecker/homebridge-meross#5]
Hi,

i am very new at homebridge.
I have some issues to control my meross wifi plug.

"accessories": [
        {
            "name": "WLAN Steckdose",
            "deviceUrl": "http:// 192.168.0.44", //this is correct
            "hardwareVersion": 2, //where to find?
            "channel": 2, // my wifi plug has 2 sockets, is this here requested?
            "messageId": "xxxxx",// I dont know where to find
            "timestamp": xxx, // I dont know where to find
            "sign": "xxxx", // I dont know where to find
            "accessory": "Meross"
        }

I have got a whireshark trace while meross is creating its own wifi net (IP 10.10.10.1) where is the information in the trace i need to connect to the plug correctly?

Thanks for help

_____________________________________________________

Frame 11: 590 bytes on wire (4720 bits), 590 bytes captured (4720 bits) on interface en0, id 0
    Interface id: 0 (en0)
    Encapsulation type: Ethernet (1)
    Arrival Time: Jan 24, 2020 23:07:30.497736000 CET
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1579903650.497736000 seconds
    [Time delta from previous captured frame: 0.005067000 seconds]
    [Time delta from previous displayed frame: 0.005067000 seconds]
    [Time since reference or first frame: 0.362533000 seconds]
    Frame Number: 11
    Frame Length: 590 bytes (4720 bits)
    Capture Length: 590 bytes (4720 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:dhcp]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: ChengduM_51:ce:45 (48:e1:e9:51:ce:45), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
    Destination: Broadcast (ff:ff:ff:ff:ff:ff)
    Source: ChengduM_51:ce:45 (48:e1:e9:51:ce:45)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 10.10.10.1, Dst: 255.255.255.255
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 576
    Identification: 0x003e (62)
    Flags: 0x0000
        0... .... .... .... = Reserved bit: Not set
        .0.. .... .... .... = Don't fragment: Not set
        ..0. .... .... .... = More fragments: Not set
    ...0 0000 0000 0000 = Fragment offset: 0
    Time to live: 255
    Protocol: UDP (17)
    Header checksum: 0xa564 [validation disabled]
    [Header checksum status: Unverified]
    Source: 10.10.10.1
    Destination: 255.255.255.255
User Datagram Protocol, Src Port: 67, Dst Port: 68
    Source Port: 67
    Destination Port: 68
    Length: 556
    Checksum: 0x008c [unverified]
    [Checksum Status: Unverified]
    [Stream index: 3]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
Dynamic Host Configuration Protocol (ACK)
    Message type: Boot Reply (2)
    Hardware type: Ethernet (0x01)
    Hardware address length: 6
    Hops: 0
    Transaction ID: 0x78f65cdf
    Seconds elapsed: 0
    Bootp flags: 0x0000 (Unicast)
    Client IP address: 0.0.0.0
    Your (client) IP address: 10.10.10.2
    Next server IP address: 0.0.0.0
    Relay agent IP address: 0.0.0.0
    Client MAC address: Apple_bb:42:85 (48:d7:05:bb:42:85)
    Client hardware address padding: 00000000000000000000
    Server host name not given
    Boot file name not given
    Magic cookie: DHCP
    Option: (53) DHCP Message Type (ACK)
        Length: 1
        DHCP: ACK (5)
    Option: (58) Renewal Time Value
        Length: 4
        Renewal Time Value: (32400s) 9 hours
    Option: (59) Rebinding Time Value
        Length: 4
        Rebinding Time Value: (56700s) 15 hours, 45 minutes
    Option: (51) IP Address Lease Time
        Length: 4
        IP Address Lease Time: (64800s) 18 hours
    Option: (54) DHCP Server Identifier (10.10.10.1)
        Length: 4
        DHCP Server Identifier: 10.10.10.1
    Option: (1) Subnet Mask (255.255.255.0)
        Length: 4
        Subnet Mask: 255.255.255.0
    Option: (28) Broadcast Address (255.255.255.255)
        Length: 4
        Broadcast Address: 255.255.255.255
    Option: (3) Router
        Length: 4
        Router: 10.10.10.1
    Option: (6) Domain Name Server
        Length: 4
        Domain Name Server: 10.10.10.1
    Option: (255) End
        Option End: 255
    Padding: 000000000000000000000000000000000000000000000000…

**Comment by donavanbecker** [comment]
not sure. I am just a maintaining this repo. So if alone has a fix feel free to submit a PR

**Comment by tippchopp** [comment]
Does this Plugin work Witz the Meross MSG100?

**Comment by dylanfrankcom** [comment]
Hey @1987marco1987, what model of Meross device are you using?

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try.
