### ISSUE TITLE
plugin is cycling red amber green

### ISSUE THREAD

**Issue by andrewsixten** [donavanbecker/homebridge-meross#504]
homebridge-meross v8.5.3 raspi
on v1.6.0

no accessories are responding 

have tried different installing older and beta versions. many restarts. 
even clean install

all 12 other plugins are fine

started overnight 

can you advise? 

many thanks 

Andrew 
me@andrew610.com 

update 21:37
I've now been logged out of the meross app (and now have no access to 27 devices). app gives error “Failed to log in (1301)” - on the login screen ... which is to do with too many log in attempts. so it seems the plugin is 'polling'? meross servers each time is cycles green/ red and has caused meross to block me from the app!

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @andrewsixten 

Were you using the beta version of the plugin? If so I have fixed an issue here.

A quick email to Meross and they should unblock your account quickly - not the first time this has happened to a user! Just explain what happened and they should be happy.

**Comment by andrewsixten** [comment]
Hi Ben,

No. I’ve just been doing the updates as prompted thru the UI … so was on 8.5.3

However, after it stopped working I did an upgrade to the beta after trying a downgrade. Then did an uninstall. 

Each instance would just cause that ‘cycling’ issue. 

Thankfully, Meross app is now working again. 

Should I switch on the plugin again?

regards,

Andrew

**Comment by bwp91** [comment]
if you’re on the latest stable version of the plugin, do try enabling the plugin again.

watch the logs (or the status light), if you see any errors report them here and disable the plugin again to avoid the cycling of trying to access meross

**Comment by andrewsixten** [comment]
Hi Ben, 
I enabled it 30 mins ago and it began cycling again.

**Comment by bwp91** [comment]
can you post here what the homebridge log shows?

**Comment by andrewsixten** [comment]
Attachment available until 5 Apr 2023
herewith

(Hope ive exported correctly)

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAfWthSQVlDsm2JDrDFpSOn2ACjeDAUmycyQaQwSYP3yWpQCzkb8d6mFj%2F%24%7Bf%7D%3Fo%3DAmeaJB8MUOa8N-Bo9cyUWQBCRCUqNFx48UxjAq7DiNKw%26v%3D1%26x%3D3%26a%3DCAogkb8LtkaRRffrhnu7qC82KH2yur3lGHUmnmrmFepAL64SdBCT8cez6zAYk4HDh_UwIgEAKgkC6AMA_xZmCmJSBIAKN4NaBB3qYWNqJJBlY8ujXwbPb1k4OqiYeldnfqnMZwBdGRx9ImagsgjLPJh893IkdlvcxxOFS5rx44BzZX0zFoAgBA35SKHhLkhulBJKCu5LjhpU%26e%3D1680690167%26fl%3D%26r%3D2860CE43-FD3A-4911-B716-3DF0DFFEDE31-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DC9FA3A3F-B500-47FE-94DD-F6543C747116%26p%3D101%26s%3Dzud7reo0wenOjT-CzoVVbwaOS-I&uk=oVr_KnBaCSJttRsqllkpdw&f=homebridge.log-2.txt&sz=426333981>homebridge.log-2.txt
426.3 MB

**Comment by bwp91** [comment]
Thanks, can you try updating to the latest beta (9.0.0-beta.4), enable the plugin again and see if you still have cycling issues?

**Comment by andrewsixten** [comment]
Beta update just done. All accessories back online and solid green status light so far
🤞
