### ISSUE TITLE
MTS150 Not ignored with active "Ignore HK Native"

### ISSUE THREAD

**Issue by jahudi84** [donavanbecker/homebridge-meross#509]
* **Please explain your feature request in a one or two sentences.**
Please add the MTS150 thermostat to the "IgnoreHKNative" list.

* **Is your feature request related to a problem? Please describe.**
MTS150 thermostat is showing twice in HomeKit app, once added by the meross hub, once by homebridge.

* **Any particular Meross devices that this relates to?**
MTS150 via MSH300HK
Hardware Version 4.0.0
Firmware Version 4.5.23

**Comment by bwp91** [comment]
Thanks for your issue, closing this as a similar issue exists here:

https://github.com/bwp91/homebridge-meross/issues/482

**Comment by jahudi84** [comment]
Sorry, somehow missed that one...

**Comment by guigsguigs** [comment]
Idem
