### ISSUE TITLE
Garage door not working anymore with 9.0.0 update

### ISSUE THREAD

**Issue by mao832** [donavanbecker/homebridge-meross#510]
MSG100 not opening anymore the garage door, downgraded to 8.5.3 and working again. Anyone else?

![D24E8F77-6AAB-40CA-825A-1DE0EBEC9B93](https://user-images.githubusercontent.com/121161067/224478968-2800208b-1d07-4149-9f7f-de1af45d228a.png)

**Comment by Barolo7** [comment]
I have the same problem after the update.

**Comment by bwp91** [comment]
Please try 9.0.1-beta.0 version, if this works then I will release a new version, thanks!

**Comment by mao832** [comment]
> Please try 9.0.1-beta.0 version, if this works then I will release a new version, thanks!

Confirmed working for me after update to 9.0.1-beta.0, thank you!

**Comment by emcepe** [comment]
does not work for me with anything >v8.5.3

does not work with v9.0.0, does not work with v9.0.1-beta.0 and does not work with v9.0.1

back to 8.5.3 for now.

Let me know if I can do anything to track this problem. The device is connected using local mode.

**Comment by bwp91** [comment]
@emcepe please can you create a new issue on here with some more context on how it is not working and also some homebridge logs that (hopefully) show some errors? Appreciated!

Closing this for OP as this particular issue is closed!

**Comment by emcepe** [comment]
@bwp91: after completely restarting homebridge stack I see the problem in the log: new version needs Homebridge v1.6.0 but I am on v1.4.1.

Funny thing that one can upgrade the plug-in even if the requirements are not met :)

Well, I do not upgrade my Homebridge. In the past years I did that twice and twice it b0rked my complete setup so I had to start from scratch - I do not want to do that a third time.
Issues @ homebridge did not get any attention from the homebridge author, not in the past and not for 1.6.0 (see issues there) so I'm far away from upgrading my perfectly working homebridge setup.

Is there any good reason why your v9.x needs homebridge v1.6.0 as a minimum?

**Comment by bwp91** [comment]
@emcepe please update to beta version of plugin, have set min version back to 1.4.0

**Comment by emcepe** [comment]
Hi @bwp91,

thank you. Newest beta is flooding my homebridge log with tons of:

```
[Garagentor] incoming poll: {"header":{"mess...
```

**Comment by bwp91** [comment]
Have released a version with min hb 1.4, so no more log flooding. can anyone confirm (or not!) that garage door device is working on new version of the plugin?

**Comment by mao832** [comment]
Mine is working properly with latest version.

**Comment by bwp91** [comment]
okay great thanks @mao832 will close this since you are issue opener and working for you.

anyone else please open a new issue if anything not working!

**Comment by bwp91** [comment]
anyone here with an MSG100 device? would you have any insight into this issue?
https://github.com/bwp91/homebridge-meross/issues/512
