### ISSUE TITLE
[Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND].

### ISSUE THREAD

**Issue by bkarakashev** [donavanbecker/homebridge-meross#511]
### What issue do you have? Please be as thorough and explicit as possible.
After updating the Homebridge plugin to homebridge-meross v9.0.0 I start having this error:

```
[Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND].
```

### Details of your setup.
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge - [v1.6.0]

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Homebridge - Raspberry Pi
Node Version - v18.15.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

homebridge-meross v9.0.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSS550L - Light Switch

### Please paste any relevant logs below.
```
[Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND].
```

**Comment by bednarekluc** [comment]
I have the same issue.
Running homebridge V1.6.0 in docker on a Synology RS822+
Node.js Versie | v18.13.0
Downgraded to homebridge-meross v8.5.3 and it worked again.
9 Merros MSS210 plugs Hardware version 7.0.0 Firmware version 7.2.15

**Comment by bwp91** [comment]
Please try 9.0.1-beta.0 version, if this works then I will release a new version, thanks!

**Comment by bkarakashev** [comment]
I can confirm it is all working with the new version 9.0.1.

**Comment by bednarekluc** [comment]
For me to, the V9.0.1 is working perfect
