### ISSUE TITLE
roller shutter connection problem

### ISSUE THREAD

**Issue by dimed89** [donavanbecker/homebridge-meross#516]
Hello, 

I want to use the meross plug in on my home bridge for integrate my roller shutter ton my streamdeck. 

I installed the plug in, connected my meross account and it detects me a pane which is marked as "online" but when I restart homebridge to apply the changes nothing appears in homebridge.

Home bridge version : 1.6.0

For information, the pane is already added to homekit via the native meross qr code. I post the configuration below:

`{
    "name": "Meross",
    "username": "",
    "password": "!",
    "connection": "default",
    "ignoreHKNative": false,
    "rollerDevices": [
        {
            "name": "MRS100",
            "serialNumber": "2205136133550970080148e1e99291a6",
            "connection": "default",
            "deviceUrl": "192.168.1.199"
        }
    ],
    "platform": "Meross"
}`

Update : 

It appears in my homekit interface but it's like a switch and when I use this switch nothing happens

**Comment by bwp91** [comment]
hi first i would change your meross password 🙂 and any other accounts you may have with this user/pass combination

**Comment by bwp91** [comment]
Hi @dimed89 if this device is already homekit native then why would you need to use the plugin?

**Comment by dimed89** [comment]
Hello, I Have alrady change my password, I use the correct password on the plug in beacuse he see my roller shutter.

I want to use this device with home bridge because I have Elgato stream deck and I want to controll my roller shutter with him. 

It's doesn't working with your plug in I only have switch for roller shutter in home bridge and no reaction from the roller shutter.

I fount another solution with the app "smart things" and "smart things" plug in on my stream deck. 

Thank's for all.
