### ISSUE TITLE
Add EU smart plug mini MSS315 (Matter)

### ISSUE THREAD

**Issue by DeutscheMark** [donavanbecker/homebridge-meross#519]
{"uuid":"xxxxxxxxxxxxxxxxxxxxx","onlineStatus":1,"devName":"Reiskocher","devIconId":"device024","bindTime":1681137596,"deviceType":"mss315","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"9.3.26","hdwareVersion":"9.0.0","userDevIcon":"","iconType":1,"domain":"mqtt-eu-3.meross.com","reservedDomain":"mqtt-eu-3.meross.com","cluster":3,"hardwareCapabilities":[],"firmware":"9.3.26","hbDeviceId":"xxxxxxxxxxxxxxxxxxxxx","model":"MSS315"

**Comment by bwp91** [comment]
Hi @DeutscheMark 

Please install the beta version of the plugin

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

**Comment by DeutscheMark** [comment]
Hi @bwp91

Thanks for the fast response and the beta version with support for the MSS315.

All the plugs I use are now found by the plugin (hybrid with simple config) and I can see their current status in Home and turn them on/off. I also have some offline plugs that are ignored as intended.

Thank you. :)
