### ISSUE TITLE
Debug Mode and User Key

### ISSUE THREAD

**Issue by ssbhv** [donavanbecker/homebridge-meross#521]
Hi, and thanks a lot for the plugin!

The online version works great for me and I love your work! I tried switching to the offline version with the user key but have been unable to retrieve the user key using the debug mode.

I don't have the checkbox to enable the debug mode using the plugin and Homebridge on my Synology NAS (not sure whether this might be an issue). I also tried enabling the debug mode by adding "debug": "true", to the config file with no success.

Thanks a lot!

Best,
Seb

**Comment by bwp91** [comment]
Hi @ssbhv sorry for late reply with this. Need to update the docs!
So debug logging only appears now on beta versions on the plugin, but this has reminded me that I need to do something about the user key that is logged in debug mode, as I don't expect users to need to update to a beta version to retrieve their key.
Now I'm thinking about this! 🧐

**Comment by ssbhv** [comment]
Thanks a lot for your feedback @bwp91. Good to know. The plugin works perfectly for me in the online mode. I would just prefer to explore the offline functionalities. Thank you.

**Comment by bwp91** [comment]
did you get the offline stuff working?
