### ISSUE TITLE
Please add support to [Smart Surge Protector]

### ISSUE THREAD

**Issue by Ludwigtch** [donavanbecker/homebridge-meross#522]
* **Please explain your feature request in a one or two sentences.**
I am using HomeKit and HomeBridge in my smart home. Just downloaded Homebridge Meross homebridge-meross v9.1.0. But it says [Smart Surge Protector] not supported

* **Is your feature request related to a problem? Please describe.**
The Smart Surge Protector (actually a smart power cord) "MSP843P", not supported.

* **Any particular Meross devices that this relates to?**
See above

* **Anything else?**
The error message log:
{"uuid":"2212016888452154030148e1e9b1f2fb","onlineStatus":1,"devName":"Smart Surge Protector","devIconId":"device033_uk","bindTime":1688213507,"deviceType":"msp843p","subType":"uk","channels":[{},{"type":"Switch","devName":"Switch 1","devIconId":"device001"},{"type":"Switch","devName":"Switch 2","devIconId":"device001"},{"type":"Switch","devName":"Switch 3","devIconId":"device001"},{"type":"Switch","devName":"Switch 4","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"ap","fmwareVersion":"7.1.2","hdwareVersion":"7.0.0","userDevIcon":"","iconType":0,"domain":"mqtt-ap.meross.com","reservedDomain":"mqtt-ap.meross.com","cluster":1,"hardwareCapabilities":[],"firmware":"7.1.2","hbDeviceId":"2212016888452154030148e1e9b1f2fb","model":"MSP843P"}

**Comment by bwp91** [comment]
Hi @Ludwigtch 

Please try the beta version of the plugin
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

I don't already have implementation for an `MSP` model, but I'm hoping it uses the same methods as similar `MSS` devices!

Should add 8 switches to your homekit, 7 for the individual sockets and a master all on/off switch. You can use the config to hide any that you don't use.

Let me know if all works okay.

**Comment by Ludwigtch** [comment]
It worked! Your beta saved my day!

You are my hero!
PS Only that 6 switches (1 master switch, 4 plugs, and 1 USB) were added to my HomeKit. Bravo!

**Comment by bwp91** [comment]
> It worked! Your beta saved my day!
> 
> You are my hero! PS Only that 6 switches (1 master switch, 4 plugs, and 1 USB) were added to my HomeKit. Bravo!

Is this the correct amount of switches?! or do i need to add one more?

**Comment by Ludwigtch** [comment]
It is correct. My bad I haven't explained the 6 switches thing.

The power cord has 4 13A sockets and 3 USBs. It is the default to have 6 switches - one for the master, one for each of the 13A, and one switch for all USBs. That means, the USB has all-in and all-out properties. This is the product feature of MSP843P.
