### ISSUE TITLE
Meross MSL120DA not recognized

### ISSUE THREAD

**Issue by aia832003** [donavanbecker/homebridge-meross#523]
### What issue do you have? Please be as thorough and explicit as possible.
Two Meross apps activated and working on the Meross app, but can't be recognized by HomeBridge plugin.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
HomeBridge v1.6.1 running on Synology DSM

* Which version of Homebridge/HOOBS do you have?
HomeBridge v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
 running on Synology DSM

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
homebridge-meross v9.1.0 

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
[Kitchen Sink] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2207186423771852050148e1e99a9e93","onlineStatus":1,"devName":"Kitchen Sink","devIconId":"device036","bindTime":1688748424,"deviceType":"msl120da","subType":"us","channels":[{}],"region":"us","fmwareVersion":"7.2.4","hdwareVersion":"7.0.0","userDevIcon":"","iconType":0,"domain":"mqtt-us-2.meross.com","reservedDomain":"mqtt-us-2.meross.com","cluster":2,"hardwareCapabilities":[],"firmware":"7.2.4","hbDeviceId":"2207186423771852050148e1e99a9e93","model":"MSL120DA"}
[7/7/2023, 1:23:00 PM] [Meross] [Living Room Floor Lamp] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2207186841209252050148e1e99a9098","onlineStatus":1,"devName":"Living Room Floor Lamp","devIconId":"device036","bindTime":1680274037,"deviceType":"msl120da","subType":"us","channels":[{}],"region":"us","fmwareVersion":"7.2.4","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"domain":"mqtt-us-2.meross.com","reservedDomain":"mqtt-us-2.meross.com","cluster":2,"hardwareCapabilities":[],"firmware":"7.2.4","hbDeviceId":"2207186841209252050148e1e99a9098","model":"MSL120DA"}

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @aia832003
Please install the beta version of the plugin, this model should now be recognised and supported!
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
Thanks!

**Comment by aia832003** [comment]
Nailed it! Thanks Ben.
