### ISSUE TITLE
MRS100 percentage support

### ISSUE THREAD

**Issue by ggfunnn** [donavanbecker/homebridge-meross#524]
* **Please explain your feature request in a one or two sentences.**

As far as I know there are three types of MRS100 switches: 
- non-homekit version without automatic calibration (no percentage support),
- non-homekit version with automatic calibration (percentage support),
- homekit version with automatic calibration (percentage support).

This plugin currently works only by adding three switches (open, close, stop) to the home app as it was created to support 1st version of these switches. Is there a possibility to add support for 2nd version of them (particularly percentage control)?

* **Is your feature request related to a problem? Please describe.**

No percentage control support in home app.

* **Any particular Meross devices that this relates to?**

Meross MRS100 non-homekit version with automatic calibration

* **Anything else?**

I would love to have this feature (I bought non-homekit switches because I thought the percentage would work via homebridge...). I can provide information, logs etc. - just tell me what you need.

**Comment by bwp91** [comment]
Hi @ggfunnn 

happy to try and implement this functionality - do you have discord? with new stuff like this i find it easier on there - my username is bwp91 - please feel free to add me as a friend on there

**Comment by ggfunnn** [comment]
I sent you a request ;)
