### ISSUE TITLE
Smart Plug is not suppport

### ISSUE THREAD

**Issue by sateeshruttala** [donavanbecker/homebridge-meross#525]
{"uuid":"2204013886737151070148e1e98e22e1","onlineStatus":2,"devName":"Smart Plug","devIconId":"device023_au","bindTime":1689213618,"deviceType":"mss210p","subType":"au","channels":[{}],"region":"ap","fmwareVersion":"7.1.2","hdwareVersion":"7.0.0","userDevIcon":"","iconType":0,"domain":"mqtt-ap.meross.com","reservedDomain":"mqtt-ap.meross.com","cluster":1,"hardwareCapabilities":[],"firmware":"7.1.2","hbDeviceId":"2204013886737151070148e1e98e22e1","model":"MSS210P"}* **Please explain your feature request in a one or two sentences.**

**Comment by bwp91** [comment]
Hi @sateeshruttala 

Please can you update to the beta version of the plugin and check this device is now working?

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!
