### ISSUE TITLE
MS400 Support

### ISSUE THREAD

**Issue by Rowbby** [donavanbecker/homebridge-meross#526]
Any possibility of adding support for the MS400 leak sensor? Thanks!

[Meross] [Smart Water Leak Sensor] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2206170830318962080148e1e998f4ac","onlineStatus":2,"devName":"Smart Water Leak Sensor","devIconId":"device040_un","bindTime":1689370531,"deviceType":"msh300hk","subType":"un","channels":[{}],"region":"us","fmwareVersion":"4.5.14","hdwareVersion":"4.0.0","userDevIcon":"","iconType":0,"domain":"mqtt-us.meross.com","reservedDomain":"mqtt-us.meross.com","cluster":1,"hardwareCapabilities":[],"firmware":"4.5.14","hbDeviceId":"2206170830318962080148e1e998f4ac150010100EEA","model":"MS400"}

**Comment by bwp91** [comment]
Hi @Rowbby 

i find it a lot easier implementing new devices being able to message on discord if you are on there, please add me as a friend, my username is `bwp91` 

This is a totally new device model for this plugin, so I will need some extra help on this from you too!
