### ISSUE TITLE
not supported meross device 

### ISSUE THREAD

**Issue by 0elfinger** [donavanbecker/homebridge-meross#527]
Hi,

at first thx. for your Homebridge plugin. It works very good in combination with some Meross MSS310.
But i have some issues with my two new power strips. I hope, that you can help me to fix this problem.

Here some Informations about my system and also the given error messages: 

[7/18/2023, 6:48:20 PM] [Meross] [Strom Couch rechts] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2209264259477454030148e1e9axxxx","onlineStatus":1,"devName":"Strom Couch rechts","devIconId":"device001","bindTime":1687281034,"deviceType":"mss425fc","subType":"eu","channels":[{},{"type":"Switch","devName":"Bose Surround links","devIconId":"device001"},{"type":"Switch","devName":"Bose Surround rechts","devIconId":"device001"},{"type":"Switch","devName":"Couch LED","devIconId":"device001"},{"type":"Switch","devName":"…frei…","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"eu","fmwareVersion":"7.2.4","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"domain":"mqtt-eu-3.meross.com","reservedDomain":"mqtt-eu-3.meross.com","cluster":3,"hardwareCapabilities":[],"firmware":"7.2.4","hbDeviceId":"2209264259477454030148e1e9axxxxx","model":"MSS425FC"}
[7/18/2023, 6:48:20 PM] [Meross] [Strom Couch links] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"2209269846534754030148e1e9axxxx","onlineStatus":1,"devName":"Strom Couch links","devIconId":"device001","bindTime":1686844789,"deviceType":"mss425fc","subType":"eu","channels":[{},{"type":"Switch","devName":"Headset Workshop","devIconId":"device001"},{"type":"Switch","devName":"Notebook Workshop","devIconId":"device001"},{"type":"Switch","devName":"Logitech HUB","devIconId":"device001"},{"type":"Switch","devName":"Ventilator","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"eu","fmwareVersion":"7.2.4","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"domain":"mqtt-eu-3.meross.com","reservedDomain":"mqtt-eu-3.meross.com","cluster":3,"hardwareCapabilities":[],"firmware":"7.2.4","hbDeviceId":"2209269846534754030148e1e9axxxxx","model":"MSS425FC"}

Docker Installation with Ubuntu Focal Fossa (20.04.6 LTS) on QNAP-NAS (TVS-672XT) 
Homebridge v.1.6.1
Node.js Version	v18.16.1

I anonymized the last 4 chars of the UUIDs, and i hope, that you got all needed Informations.

Many thx for your great work and help.

Alex

**Comment by bwp91** [comment]
Hi @0elfinger 

Please update to the beta version of the plugin
https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

You should find this device starts working :)

**Comment by 0elfinger** [comment]
Hi @bwp91

Works like Magic ;)

Many thx for your Support
