### ISSUE TITLE
Smart Bulbs appearing in homebridge even though added directly to homekit

### ISSUE THREAD

**Issue by JaiR236** [donavanbecker/homebridge-meross#528]
Model number: MSL120D

Probably just needed to be added to the list of models which can be directly added to homekit.

**Comment by bwp91** [comment]
Hi @JaiR236 please let me know which hardware version you have of this model

**Comment by JaiR236** [comment]
7.0.0

**Comment by bwp91** [comment]
Thank you. New beta should remove this device:

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
