### ISSUE TITLE
MSS710R Not ignored by ignoreHKNative

### ISSUE THREAD

**Issue by badgertastic** [donavanbecker/homebridge-meross#529]
### What issue do you have? Please be as thorough and explicit as possible.

MSS710R Is HomeKit version of MSS710 but isn’t ignored by setting ignoreHKNative true

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

HB 1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Intel Mac, HB 1.6.1, Node 18.16.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

9.2.1. Same issue previous versions. 

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

MSS710R Smart Wi-Fi switch, homebridge compatible. 

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @badgertastic  please let me know which hardware version you have of this model

**Comment by badgertastic** [comment]
Hi. Looks to be 4.0.0

**Comment by bwp91** [comment]
Thank you. New beta should remove this device:

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
