### ISSUE TITLE
MSL320CR Is HomekitVersion but isn't being ignored by ignoreHKNative true

### ISSUE THREAD

**Issue by dawnchorus6010** [donavanbecker/homebridge-meross#530]
What issue do you have? Please be as thorough and explicit as possible.
MSL320cr Is HomeKit version but isn’t ignored by setting ignoreHKNative true

Details of your setup.
Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
1

Which version of Homebridge/HOOBS do you have?
Latest

Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Docker, Node 18.16.0

Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
latest.

Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSL320CR LED RGB Light Strip, Homekit compatible.

**Comment by dawnchorus6010** [comment]
[7/23/2023, 5:46:43 PM] [Meross] [Monitor-RGB] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"connection":"hybrid"}.
[7/23/2023, 5:46:43 PM] [Meross] [Monitor-RGB] initialised with id [22082566349166560F0248e1e9a4dced}].

**Comment by bwp91** [comment]
Hi @dawnchorus6010  please let me know which hardware version you have of this model

**Comment by dawnchorus6010** [comment]
4.0.0
  
  
  
  
  
  
  

  
  
>

**Comment by bwp91** [comment]
Thank you. New beta should remove this device:

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
