### ISSUE TITLE
[Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND]. again

### ISSUE THREAD

**Issue by alanXdev0** [donavanbecker/homebridge-meross#531]
### What issue do you have? Please be as thorough and explicit as possible.
It shows up this error after rebooting, new installation, found an issue in march tried 9.0.1 and same error appears
`[Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND].`

### Details of your setup.
* Homebridge v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Raspberry Pi 4

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version? 9.2.2 latest

* Which Meross devices do you have that are causing issues? 

### Please paste any relevant logs below.
`[Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND].`

```

```

**Comment by bwp91** [comment]
Hi @alananayadev 

Do you have any firewalls that might be preventing the plugin from reaching the meross servers?

**Comment by alanXdev0** [comment]
nope, I used iotx-us.meross.com, on Proxyman it appears like this.
<img width="349" alt="image" src="https://github.com/bwp91/homebridge-meross/assets/13240817/ea6c6bcf-ad1b-4b8f-aaad-1e0b2f722b18">

**Comment by bwp91** [comment]
plugin uses `iot.meross.com`

**Comment by alanXdev0** [comment]
if I use iot.meross.com it shows the next error, and I don't know where to register
<img width="1053" alt="image" src="https://github.com/bwp91/homebridge-meross/assets/13240817/480d6c7e-8141-4f67-8edf-12313c94e17e">

**Comment by bwp91** [comment]
Have you created an account in the meross app? you need to use the credentials in the plugin settings from your meross app

**Comment by alanXdev0** [comment]
yeah I've created my account using Meross app, also on Proxyman that intercepts the api calls from the app it uses iotx-us.meross.com itstead of iot-meross.com

**Comment by bwp91** [comment]
Yes my meross app uses `iotx-eu.meross.com`, but my plugin uses the default `iot.meross.com` and they both seem to work for me and other users.

Have you tried using the domain option in the plugin settings to change to `iotx-us.meross.com`?

![Screenshot 2023-07-29 at 23 50 09](https://github.com/bwp91/homebridge-meross/assets/43026681/fd99e214-8090-4148-9419-dcee6d2f6c86)

**Comment by alanXdev0** [comment]
if I use iotx-us.meross.com it shows me this error:
`[Meross] Unable to reach Meross, retrying in 30 seconds [login() - ENOTFOUND].`

There is no firewall activated on my router because I can connect with no issues from my phone

**Comment by bwp91** [comment]
and there is no firewall installed on your pi?

is your meross account _very_ old or _very_ new? trying to work out any reason why this would not work for you.

**Comment by alanXdev0** [comment]
I'm really sorry, I've found out that my email got registered with .con instead of .com
@bwp91 thanks a lot for your support

**Comment by bwp91** [comment]
ah good to know! otherwise this scenario was gonna get me slightly concerned that i would need to make some changes!

no worries hope all is working well now 😄
