### ISSUE TITLE
Meross MRS100 Rolling Shutter Switch

### ISSUE THREAD

**Issue by CASCSX** [donavanbecker/homebridge-meross#532]
Hi,

first of all, thank you very much for your plugin :) 
I'm currently facing some problems. 
The installation was really easy. Now I'm trying to configure my MRS100 Rolling Shutter Switch. 
But I cannot find the UUID. I find only a serial number with 15 characters, but according to the plugin 32 char's are needed.
Also can I test if the connections to Meross CLoud is working?

Thanks in advance.

**Comment by bwp91** [comment]
Hi @CASCSX 

Device long UUIDs are visible in the homebridge log when the plugin starts
