### ISSUE TITLE
MRS100 Roller device

### ISSUE THREAD

**Issue by tombolini** [donavanbecker/homebridge-meross#535]
### What issue do you have? Please be as thorough and explicit as possible.
First, thank you for your work! Much appreciated.

According to your changelog (9.2.0 (2023-07-18)) you added "Support for MRS100 models that have % position capabilities)".
I have one of those, and I only get the three switches in Homekit.
I have the MRS100 Homekit Version that is absolutely unreliable in Homekit, but works fine when using the Meross app, so I would like to use it with Homebridge.

See my log output, it even says "showAs:switch". Is there any way for me to change the behavior?
I do have the percentage set bar in the Meross app.

Please let me know if you need additional logs.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?
1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
homebridge-meross v9.2.5

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MRS100 Roller device

### Please paste any relevant logs below.
[15/09/2023, 10:46:27] [Meross] [Roller] initialising with options {"connection":"hybrid","showAs":"switch"}.
[15/09/2023, 10:46:27] [Meross] [Roller] initialised with id [220927197210.......a96307}]. (I removed the id just in case)

**Comment by bwp91** [comment]
Hi @tombolini couple of questions:

1. do you have position % capabilities in the meross app? or just similar up/down/stop switches?
2. which hardware version is your device? You can find this in the plugin settings screen - my devices tab

**Comment by tombolini** [comment]
Yes, I can set the percentage in the Meross app.

![IMG_0174](https://github.com/bwp91/homebridge-meross/assets/68784136/2eb51377-9367-4d1f-939e-89324194c72f)

According to the app, I have hardware version 7.0.0 and I'm using firmware 7.6.1.0 in case that matters.

**Comment by bwp91** [comment]
Please try the new beta version of the plugin:

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by tombolini** [comment]
Now it works! Thank you very much.

**Comment by bwp91** [comment]
Awesome. Just released a new version of the plugin with the updates. Will close this now, feel free to reopen if any further issues.
