### ISSUE TITLE
Problem updating 9.2.5 →  9.2.6

### ISSUE THREAD

**Issue by juanfal** [donavanbecker/homebridge-meross#536]
I get the following error message:

    278 error ENOTEMPTY: directory not empty, rename '/var/lib/homebridge/node_modules/homebridge-meross' -> '/var/lib/homebridge/node_modules/.homebridge-meross-wacUV3ZQ'

* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

I use (1) Homebridge 1.6.1
on Raspberry Pi zero copy

Had the version 9.2.5 of hb-meross

```
278 error ENOTEMPTY: directory not empty, rename '/var/lib/homebridge/node_modules/homebridge-meross' -> '/var/lib/homebridge/node_modules/.homebridge-meross-wacUV3ZQ'
```

**Comment by bwp91** [comment]
Hi @juanfal 

From the homebridge terminal, can you run this:

```
sudo rm -rf /var/lib/homebridge/node_modules/homebridge-meross
```

don't restart homebridge at this point (have to say it!) then run this:

```
sudo npm i -g homebridge-meross
```

**Comment by bwp91** [comment]
if neither of the above commands fail, then restart homebridge

**Comment by juanfal** [comment]
$ sudo rm -rf /var/lib/homebridge/node_modules/homebridge-meross
pi23:31:21 homebridge-shelly-consumption $ sudo npm i -g homebridge-meross
sudo: npm: command not found
pi23:31:29 homebridge-shelly-consumption $ sudo npm i -g homebridge-meross

**Comment by bwp91** [comment]
ah ok don’t restart homebridge at all yet

**Comment by bwp91** [comment]
in the homebridge ui can you search for the meross plugin, and does it let you install it?

**Comment by juanfal** [comment]
It has disappeared.  I spent 1 hour reconfiguring every automation and organising everything in the previous dissaster ()

**Comment by juanfal** [comment]
I my gosh! I had an old non updated safari window still with the Meross plugin asking to be updated.  Oh my!  it has update it (installed it) without breaking everything as it did before with that crash!

Thanks anyway!

**Comment by bwp91** [comment]
vaya tela!
