### ISSUE TITLE
MSS315 is HomeKit native

### ISSUE THREAD

**Issue by Perilax-De** [donavanbecker/homebridge-meross#537]
Thanks for the great plugin. 

Please add the MSS315 to the HomeKit native list, that we can ignore it. 

Thank you !

**Comment by bwp91** [comment]
Hi @Perilax-De can you provide the hardware version of your MSS315?

**Comment by Perilax-De** [comment]
Hardware version: 9.0.0
Firmware version: 9.5.33

Sorry I just saw that it is only Matter compatible. Is there any way to hide Matter devices that are directly connected to HomeKit ?

**Comment by bwp91** [comment]
Please install the beta version of the plugin, I have added another configuration option to ignore matter devices

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions
