### ISSUE TITLE
Meross MSS425FC is a HomeKit Native

### ISSUE THREAD

**Issue by hajar97** [donavanbecker/homebridge-meross#538]
### What issue do you have? Please be as thorough and explicit as possible.
A HomeKit Native device isn't filtered out by the plugin and as a result I end up having it twice in Home app.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1.

* Which version of Homebridge/HOOBS do you have?
1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
9.2.6

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
mss425fc 

### Please paste any relevant logs below.

![image](https://github.com/bwp91/homebridge-meross/assets/16057214/dd696f49-ca0f-4804-bca6-8aa081bdfa7f)

```

```

**Comment by bwp91** [comment]
Please update to v10 of the plugin, this device should be removed
