### ISSUE TITLE
MSL120DA HomeKit Native

### ISSUE THREAD

**Issue by AndreGT6** [donavanbecker/homebridge-meross#542]
* **Please explain your feature request in a one or two sentences.**
Added some MSL120DA smart bulbs which are native HomeKit items but they showing up as not native and therefore replicating inside Home as native and via bridge.

* **Is your feature request related to a problem? Please describe.**

* **Any particular Meross devices that this relates to?**
Model			MSL120DA
Hardware Version	7.0.0
Firmware Version	7.2.7

* **Anything else?**

**Comment by bwp91** [comment]
Hi @AndreGT6 thanks for this

I published a beta version of the plugin which should remove this device from your homebridge

**Comment by AndreGT6** [comment]
@bwp91 thank you so much! That did the trick.
