### ISSUE TITLE
Cannot Read properties. toUpperCase error

### ISSUE THREAD

**Issue by deboy69** [donavanbecker/homebridge-meross#543]
### What issue do you have? Please be as thorough and explicit as possible.
[Meross] ***** Cannot read properties of undefined (reading 'toUpperCase') at file:///homebridge/node_modules/homebridge-meross/lib/platform.js:358:46. *****

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Home Brige UI

* Which version of Homebridge/HOOBS do you have?

1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

v20.9.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

homebridge-meross v10.0.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

Garage door. MSG100HK

### Please paste any relevant logs below.
[11/3/2023, 12:14:03 PM] [Meross] ***** Disabling plugin. *****
[11/3/2023, 12:14:03 PM] [Meross] ***** Cannot read properties of undefined (reading 'toUpperCase') at file:///homebridge/node_modules/homebridge-meross/lib/platform.js:358:46. *****

Appears to only give this error when trying to use local connection to the Meross Garage door system.

**Comment by Brwndude2160** [comment]
I am also having the same issue.  Homebridge Version: 1.7.0 ,  Raspberry Pi 4 ,  home bridge-meross v10.0.0, MSG100 , Node.js version: 21.0.0


It seems to give that error when configuring the Meross Garage Door Module ( Non-Homekit Version) as a local device.

**Comment by bwp91** [comment]
If you are tying to use this model locally, have you entered the user key into the config?
