### ISSUE TITLE
MSL120DA Meross LED Bulbs not being ignored natively.

### ISSUE THREAD

**Issue by dawnchorus6010** [donavanbecker/homebridge-meross#548]
### What issue do you have? Please be as thorough and explicit as possible.
Device not being ignored, showing duplicates.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?  1

* Which version of Homebridge/HOOBS do you have?  1.7.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known. DSM NAS

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
10.0.0 latest

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSL120DA
Serial: 2307248966654752050248e1e9d25a1
Firmware v: 7.2.7

**Comment by bwp91** [comment]
Hi @dawnchorus6010 which hardware version has your device?

**Comment by dawnchorus6010** [comment]
Hw version is 7.0.0
  
  
  
  
  
  
  

  
  
>

**Comment by bwp91** [comment]
Hi @dawnchorus6010 this device should now be hidden with the new version of the plugin :)
