### ISSUE TITLE
mss630 Native Ignore

### ISSUE THREAD

**Issue by AndreGT6** [donavanbecker/homebridge-meross#550]
* **Please explain your feature request in a one or two sentences.**
Please add mss630 {Meross Smart Outdoor Smart Plug, MSS630HK (US/CA Version)} to the native list.

* **Is your feature request related to a problem? Please describe.**

* **Any particular Meross devices that this relates to?**

* **Anything else?**

Love this plug in, thank you!

**Comment by bwp91** [comment]
Hi @AndreGT6 please can you grab me the hardware version of your Mss630?

**Comment by AndreGT6** [comment]
Hardware = 4.0.0
Firmware = 4.2.2

Thanks.

A.

**Comment by bwp91** [comment]
This should be fixed in recent versions of the plugin!
