### ISSUE TITLE
Meross MPD100

### ISSUE THREAD

**Issue by jDanCo** [donavanbecker/homebridge-meross#551]
I’am sorry to bother you but as beginners using Hoobs I don’t know what I doing wrong using your plugin. The plugins do not detect my only one Meross device. Outdoor dimmer plug 
MPD100.
Any recommendations?

**Comment by bwp91** [comment]
Hi @jDanCo the plugin should already work with this model.

Can you get the logs from hoobs for this plugin and paste here what it shows?

**Comment by bwp91** [comment]
Closing as no response
