### ISSUE TITLE
Multi-Channel Accessory Grouping

### ISSUE THREAD

**Issue by ZeliardM** [donavanbecker/homebridge-meross#555]
* **Please explain your feature request in a one or two sentences.**
First of all, I just started using this plugin today. It works great and I'm thankful for the work you've done. I have other Meross MSS630 devices that are HomeKit Native, but purchased one that was not, and this gives me the ability to use it in HomeKit.

Currently, when you add a Native HomeKit Meross device, the main name for the device is not added as a separate accessory, it is a group that is added of the other accessories related to it, in my case outlets in the MSS630. There are three outlets that all have their own name and then the main display name is used to group them in HomeKit. They can be split by choosing to show as separate tiles, or as a single tile. 

As of right now, when your plugin pulls in devices, it pulls in the main display name as a separate accessory that is also turned on and off when any one of the other accessories is turned on or off or it can be used to turn them all on or off.

It would be nice to have them show up as a single tile in a group with the main name and give us the option to split them into separate tiles.

* **Is your feature request related to a problem? Please describe.**
There is no problem, it's just an aesthetically pleasing way to look at the tiles and for them to operate as a group.

* **Any particular Meross devices that this relates to?**
I believe this could possibly affect any multi-channel device.

* **Anything else?**
I also have the same issue as Issue #550, where the Native Ignore does not work for my Native HomeKit Outlets, they use the same firmware and hardware version as the issue lists:
Firmware: 4.2.2
Hardware: 4.0.0

The non-native device uses:
Firmware: 3.2.2
Hardware: 3.0.0

**Comment by bwp91** [comment]
Hi @ZeliardM yes the main approach that I went for (as I do in all my plugins) is to split multi-channel devices into separate accessories, mainly the reason being that you can then add them to different homekit rooms, whereas with a "grouped accessory" (even when split into single tiles) cannot.

> I also have the same issue as Issue https://github.com/bwp91/homebridge-meross/issues/550, where the Native Ignore does not work for my Native HomeKit Outlets

should be fixed in new version of plugin

offering an option to group them and display as a single homekit accessory is not impossible, and something i could look into perhaps with a configuration option to enable this

**Comment by ZeliardM** [comment]
@bwp91 I understand the reasoning behind it, yea.

I would appreciate the ability to have it as one in a setting when you get the time to do it, I appreciate it. I see the use for the setting for items like power strips or multi-outlets where the actual plugs aren't in multiple rooms. It'd be nice from a UI standpoint to have them consolidated.

I'll try the new version to make sure the native ones get hidden properly.

Thanks!

**Comment by ZeliardM** [comment]
@bwp91 the update worked great and the native mss360's that I have are now hidden! Thanks!

**Comment by ZeliardM** [comment]
@bwp91 hey, I know this is back burner, but I've been looking around to find examples of what I'm thinking and I think this might be a viable option:
https://github.com/iRayanKhan/homebridge-tuya/blob/main/lib/MultiOutletAccessory.js
https://github.com/iRayanKhan/homebridge-tuya/wiki/Supported-Device-Types#smart-power-strips

I don't have a Tuya device, but from what I've heard it adds multiple subtypes together and the outlet service type.

I'm not one for javascript, but I can see if I can throw together a PR, if that would help?

Thanks!

**Comment by ZeliardM** [comment]
@bwp91 see https://github.com/bwp91/homebridge-meross/pull/569

**Comment by ZeliardM** [comment]
I had some issues with the state of the outlets not being updated correctly. I fixed those issues and pushed those updated commits.

**Comment by ZeliardM** [comment]
@bwp91 hey, just saw you merged everything, thank you so much! I checked the beta and when I loaded it, the Enable Power Strips Option from the config doesn't show up, any thoughts or are you not done with setting up the beta? I went back to my version from my repo and it works like expected.

**Comment by ZeliardM** [comment]
Tested the latest 10.3.1 beta 3 and it's working great! Thanks so much sir! And glad I could help. I think we can close this discussion now was well!
