### ISSUE TITLE
Changed switch name in Meross app, not reflected in the plug in

### ISSUE THREAD

**Issue by kitenski** [donavanbecker/homebridge-meross#560]
### What issue do you have? Please be as thorough and explicit as possible.
I changed the name of a switch in the Meross app, but the "old" name has persisted on the Homebridge plugin, despite reboots, upgrades etc.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

[Homebridge v1.7.0](https://github.com/homebridge) · [UI v4.54.1](https://github.com/homebridge/homebridge-config-ui-x) · UI developed by [oznu](https://github.com/oznu)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry PI/Docker version,  node.js v18.19

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?

v1.1.5

* Which Meross devices do you have that are causing issues? Please include product models if applicable.

mss210 switch

### Please paste any relevant logs below.

```

```

**Comment by gileswells** [comment]
It's likely that your switch's config is cached by Homebridge. In the top right of Homebridge click the 3 dots and then go to Homebridge Settings. Near the bottom is `Remove Single Cached Accessory`. Give that a shot, restart Homebridge, and I believe that should bring it back with the new name. Alternatively, you can just update the name in Homebridge yourself on the Accessories page.

Be warned that clearing a cached item can remove it from any automations that you might have setup through the Home or Shortcuts apps so it could force you to need to reset those automations. If you have a lot of them I would recommend just manually updating the name.

**Comment by kitenski** [comment]
thanks, that did the trick, I did try renaming it on the accessories page, but the log still referred to it as the old name.

**Comment by gileswells** [comment]
I don't have an ability to close your issue but if you're able to that'll help to reduce load on the maintainer from having to triage this issue at some point in the future.
