### ISSUE TITLE
Meross Powerstrip (MSP844) and sensor MS100F gets duplicated 

### ISSUE THREAD

**Issue by Michelasso** [donavanbecker/homebridge-meross#585]
Hi Ben,

I use (1) Homebridge UI-X, updated to the latest release. It's running on Raspberry Pi 3b. I also just updated the Node.js to 2.0 (?) following the Home Bridge instructions.

The plugin version is v10.7.0, but I think the issue started after I updated to v10.6.2 (I can't swear on it).

The devices are Meross Powerstrip (MSP844) and sensor MS100F. They both support HomeKit (even Matter the power strip) but they don't get ignored, getting duplicated in HomeKit.

I attach part of the log:

> [27/07/2024, 10:29:10] [Meross] Initializing Meross platform...
> [27/07/2024, 10:29:10] [Meross] Initializing child bridge 0E:C1:D7:C4:49:3F
> [27/07/2024, 10:29:16] [Meross] Launched child bridge with PID 24746
> [27/07/2024, 10:29:21] [Meross] Loaded homebridge-meross v10.7.0 child bridge successfully
> [27/07/2024, 10:29:24] [Meross] Initialising plugin v10.7.0 | System linux | Node v20.15.1 | HB v1.8.4 | HAPNodeJS v0.12.2...
> [27/07/2024, 10:29:24] [Meross] Plugin initialised. Setting up accessories....
> [27/07/2024, 10:29:25] Homebridge v1.8.4 (HAP v0.12.2) (Meross) is running on port 42267.
> [27/07/2024, 10:29:25] 
> [27/07/2024, 10:29:26] [Meross] [Intrattenimento] not initialising cloud device as matched as Matter model.
> 
> [...] POWER STRIP:
> 
> [27/07/2024, 10:29:27] [Meross] [Gruppo Cinema] initialising with options {"connection":"hybrid","showAs":"switch"}.
> [27/07/2024, 10:29:27] [Meross] [LG C3] initialising with options {"connection":"hybrid","showAs":"switch"}.
> [27/07/2024, 10:29:27] [Meross] [Sony Atmos] initialising with options {"connection":"hybrid","showAs":"switch"}.
> [27/07/2024, 10:29:27] Registering platform 'homebridge-ring.Ring'
> [27/07/2024, 10:29:28] [Meross] [PS5] initialising with options {"connection":"hybrid","showAs":"switch"}.
> [27/07/2024, 10:29:28] [Meross] [Mobile] initialising with options {"connection":"hybrid","showAs":"switch"}.
> [27/07/2024, 10:29:28] [Meross] [USB C] initialising with options {"connection":"hybrid","showAs":"switch"}.
> [27/07/2024, 10:29:28] [Meross] [Gruppo Cinema] initialised with id [24052027163574540303c4e7ae043c69].
> 
> [....] SENSORS:
> 
> [27/07/2024, 10:29:29] [Meross] [Sensore Camera] initialising with options {"connection":"hybrid","lowBattThreshold":20}.
> [27/07/2024, 10:29:29] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-ring) is running on port 36509.
> [27/07/2024, 10:29:29] [Meross] [Meross Hub] [Sensore Camera] subdevice initialised with id [39000DECB13E].
> [27/07/2024, 10:29:29] [Meross] [Sensore Terrazza] initialising with options {"connection":"hybrid","lowBattThreshold":20}.
> [27/07/2024, 10:29:30] [Meross] [Meross Hub] [Sensore Terrazza] subdevice initialised with id [39000DECB7B1].
> [27/07/2024, 10:29:30] [Meross] [Sensore Divano] initialising with options {"connection":"hybrid","lowBattThreshold":20}.
> [27/07/2024, 10:29:30] [Meross] [Meross Hub] [Sensore Divano] subdevice initialised with id [39000DECCE88].
> [27/07/2024, 10:29:30] [Meross] [Meross Hub] initialised with id [2308224723945962080448e1e9d73821].
> 
> 
> [...]
> 
> [27/07/2024, 10:29:31] [Meross] [Gruppo Cucina] has been reported [online].
> [27/07/2024, 10:29:31] [Meross] [Gruppo Salotto] has been reported [online].
> [27/07/2024, 10:29:34] [Meross] [Sensore Camera] current temperature [28.1°C].
> [27/07/2024, 10:29:34] [Meross] [Sensore Camera] current humidity [61%].
> [27/07/2024, 10:29:34] [Meross] [Sensore Terrazza] current temperature [31.7°C].
> [27/07/2024, 10:29:34] [Meross] [Sensore Terrazza] current humidity [51%].
> [27/07/2024, 10:29:34] [Meross] [Sensore Divano] current temperature [27.9°C].
> [27/07/2024, 10:29:34] [Meross] [Sensore Divano] current humidity [60%].
> [27/07/2024, 10:29:34] [Meross] [Sensore Camera] has been reported [online].
> [27/07/2024, 10:29:34] [Meross] [Sensore Terrazza] has been reported [online].
> [27/07/2024, 10:29:34] [Meross] [Sensore Divano] has been reported [online].
> [27/07/2024, 10:29:34] [Meross] [Meross Hub] has been reported [online].
> [27/07/2024, 10:34:28] [Meross] [Gruppo Cinema] current state [on].
> [27/07/2024, 10:34:28] [Meross] [Gruppo Cinema] current state [on].
> [27/07/2024, 10:34:28] [Meross] [Gruppo Cinema] current state [on].
> [27/07/2024, 10:34:28] [Meross] [Gruppo Cinema] current state [on].
> [27/07/2024, 10:34:28] [Meross] [Gruppo Cinema] current state [on].
> [27/07/2024, 10:34:28] [Meross] [Gruppo Cinema] has been reported [online].
> [27/07/2024, 10:34:28] [Meross] [LG C3] has been reported [online].
> [27/07/2024, 10:34:28] [Meross] [Sony Atmos] has been reported [online].
> [27/07/2024, 10:34:29] [Meross] [PS5] has been reported [online].
> [27/07/2024, 10:34:29] [Meross] [Mobile] has been reported [online].
> [27/07/2024, 10:34:29] [Meross] [USB C] has been reported [online].
> [27/07/2024, 10:34:29] [Meross] [Sensore Terrazza] current temperature [32°C].
> [27/07/2024, 10:34:29] [Meross] [Sensore Terrazza] current humidity [50%].
> [27/07/2024, 10:39:29] [Meross] [Sensore Camera] current temperature [28°C].
> [27/07/2024, 10:39:29] [Meross] [Sensore Divano] current temperature [28°C].
> [27/07/2024, 10:39:29] [Meross] [Sensore Divano] current humidity [59%].
> [27/07/2024, 10:44:29] [Meross] [Sensore Terrazza] current humidity [46%].

I also tried to hide them on each device configuration, but they still appeared in HomeKit. Any chance this can get fixed? Thanks!

**Comment by bwp91** [comment]
hi @Michelasso 

what are the hardware versions of both of these devices? this can be seen in the meross app i believe. something like “4.0.0” or “7.0.0”

**Comment by Michelasso** [comment]
Hi Ben,

thanks for the swift reply! I could find the HW version for the hub msh300hk. It's v4.0.0.  There is no mention of the HW version for the sensors.

The power strip is version 9.0.0.

**Comment by bwp91** [comment]
You can try the beta version of the plugin, it should remove these two devices

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by Michelasso** [comment]
Magical!! It worked! Thanks!!
