### ISSUE TITLE
Support for MSS210 Plug

### ISSUE THREAD

**Issue by phillippc** [donavanbecker/homebridge-meross#6]
Hey!
i tried to configure my meros mss210 plug,
however it fails to post, i sniffed all the information required, yet no success, has meross closed their API?
Thanks!

**Comment by donavanbecker** [comment]
not sure. I am just a maintaining this repo. So if alone has a fix feel free to submit a PR

**Comment by dylanfrankcom** [comment]
Hey @phillippc, could you post the payload for the plug as well as your config?

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try.
