### ISSUE TITLE
Meross MSS210 not working Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by monxas** [donavanbecker/homebridge-meross#61]
**Describe The Bug:**
Homebridge not able to comunicate with plugs, errors in console
**To Reproduce:**
Just using homebridge to turn on and off plugs
**Expected behavior:**
plugs responding to calls from homebridge
**Logs:**

    [7/30/2020, 11:51:21] [Enchufe] Failed to POST to the Meross Device MSS210 at 192.168.0.20: Error: connect EHOSTUNREACH 192.168.0.20:80
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
      errno: 'EHOSTUNREACH',
      code: 'EHOSTUNREACH',
      syscall: 'connect',
      address: '192.168.0.20',
      port: 80
    }
    [7/30/2020, 11:51:36] [Enchufe] Failed to POST to the Meross Device MSS210 at 192.168.0.20: Error: connect EHOSTUNREACH 192.168.0.20:80
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
      errno: 'EHOSTUNREACH',
      code: 'EHOSTUNREACH',
      syscall: 'connect',
      address: '192.168.0.20',
      port: 80
    }
    (node:19110) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'togglex' of undefined
        at Meross.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:327:41)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    (node:19110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
    (node:19110) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'togglex' of undefined
        at Meross.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:327:41)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    (node:19110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
    (node:19110) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'togglex' of undefined
        at Meross.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:327:41)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
    (node:19110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
    [7/30/2020, 11:53:58] [Enchufe] Failed to POST to the Meross Device MSS210 at 192.168.0.20: Error: connect EHOSTUNREACH 192.168.0.20:80
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
      errno: 'EHOSTUNREACH',
      code: 'EHOSTUNREACH',
      syscall: 'connect',
      address: '192.168.0.20',
      port: 80
    }

```

**Homebridge Config:**

```
    {
        "bridge": {
            "name": "Homebridge AA1B",
            "username": "0E:7E:93:4D:AA:1B",
            "port": 51018,
            "pin": "297-43-810"
        },
        "accessories": [
            {
                "model": "MSS210",
                "name": "Impresora 3D",
                "deviceUrl": "192.168.0.116",
                "channel": 0,
                "messageId": "c1779468dca8f744e0842c733b74e28e",
                "timestamp": 1596102034,
                "sign": "27232e3e6b88afe45f3205c72c8e1fd1",
                "accessory": "Meross"
            },
            {
                "model": "MSS210",
                "name": "Enchufe",
                "deviceUrl": "192.168.0.20",
                "channel": 0,
                "messageId": "7e8dd43a668da4cd3c3d5f885421974d",
                "timestamp": 1596102036,
                "sign": "4f60163a5356c80b460d866a8a2a4109",
                "accessory": "Meross"
            }
        ],
        "platforms": [
            {
                "name": "Config",
                "port": 8581,
                "platform": "config"
            }
        ]
    }

```
**Environment:**

* **Node.js Version**: v12.18.3
* **NPM Version**: 6.14.6
* **Homebridge Version**: 1.1.1
* **Homebridge Meross Plugin Version**: homebridge-meross v2.3.1
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.24.0
* **Operating System**:  raspbian buster lite

**Comment by dirkelko** [comment]
While it worked with two of my MSS210 plugs (hardware version 2.0, can be checked in the Meross App), I got the same error with two older MSS210 plugs (identical looking and same label but hardware version 1.0). It works if I select for the older plugs MSS-110-1.0 as device in the settings.
Seems that the MSS210 plug exists also in two versions with the older one being similar to the MSS-110 1.0

**Comment by dylanfrankcom** [comment]
> Seems that the MSS210 plug exists also in two versions with the older one being similar to the MSS-110 1.0

Interesting. Will look into getting that distinction implemented. Good find!

**Comment by songo-github** [comment]
> ` {
            "model": "MSS560",
            "name": "gimp basement lights",
            "deviceUrl": "X.X.X.X",
            "channel": 0,
            "messageId": "REMOVED",
            "timestamp": REMOVED,
            "sign": "REMOVED",
            "innerIP": "X.X.X.X",
            "accessory": "Meross"
        } `

I got a similar error on a MSS560 dimmer switch in homebridge fixed by adding the “innerIP”: “X.X.X.X” line in the config. The dimmer function was not actionable in homebridge, but the error message went away

**Comment by pinityoufairy** [comment]
I have this exact issue, was any progress made? Sorry i missed this before posting a new issue

**Comment by donavanbecker** [comment]
See #151
