### ISSUE TITLE
Beta Testing for v3.0.0

### ISSUE THREAD

**Issue by donavanbecker** [donavanbecker/homebridge-meross#66]
#### Changes
-  Converted Project to Typescript.

To Install:
```
sudo npm install -g --unsafe-perm homebridge-meross@beta
```
To Revert:
```
sudo npm install -g --unsafe-perm homebridge-meross@latest
```

**Comment by donavanbecker** [comment]
@CocoaBob @dylanfrankcom @

**Comment by CocoaBob** [comment]
The beta seems working well, so far so good, I will keep testing it for another day 👍

**Comment by donavanbecker** [comment]
v3.0.0 has been released.
