### ISSUE TITLE
Add Support for Meross MRC210 Fan Controller

### ISSUE THREAD

**Issue by LordJohnWhorfin** [donavanbecker/homebridge-meross#76]
The [Meross MRC210](https://www.meross.com/product/57/article/) is a multiple ceiling fan controller compatible with a variety of ceiling fans.
I can see my HVAC fans come on in HomeKit and I would like to be able to add automation to make the ceiling fans turn on automatically to assist them. Unfortunately the MRC210 seems to be the one Meross product that is not yet supported by this cool plugin.

**Comment by donavanbecker** [comment]
@LordJohnWhorfin have you used http catcher to get the data that is being set to the plug? if not see [Getting-Credentials](https://github.com/donavanbecker/homebridge-meross/wiki/Getting-Credentials) wiki.

**Comment by donavanbecker** [comment]
See #151
