### ISSUE TITLE
Meross MSG100

### ISSUE THREAD

**Issue by tippchopp** [donavanbecker/homebridge-meross#9]
Can you add the Meross MSG100EU ?

**Comment by donavanbecker** [comment]
If you can create a pull request for it. I can push it. I am just maintaining this Repo.

**Comment by dylanfrankcom** [comment]
Hey @tippchopp,

Have you attempted to setup the MSG100 following the guide and it is not working?

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try.
