### ISSUE TITLE
Homebridge is showing updates already done on Meross App

### ISSUE THREAD

**Issue by ziedby** [donavanbecker/homebridge-meross#97]
Hi,

Homekit is showing both accessories with an update available even if I already updated them.
I even updated them before configuring Homebridge.

What should I do ?

Thank you

**Comment by donavanbecker** [comment]
Need more info, need to see firmware and picture etc. potentially, restart homebridge.

**Comment by ziedby** [comment]
Hi @donavanbecker 

Thanks for your feedback. 

Here is my setup:
Homebridge Plugin version : 3.2.0
Hardware version : MSS210
Hardware firmware version : 2.1.7


With some pictures showing Meross being up to date and the Home app showing an available update for both plugs. 

![85E8DC8C-CBF7-4B6C-9F59-DC7B3DAC0D7E](https://user-images.githubusercontent.com/11686358/96333039-e2f03100-1067-11eb-8bf6-b52bf266fdcb.jpeg)
![7BB11463-A819-4CAB-B8A0-F7EA047320A0](https://user-images.githubusercontent.com/11686358/96333040-e4215e00-1067-11eb-8f8c-3c40721c60f2.jpeg)
![8EA44F73-819B-46D6-9145-376F8C7BF896](https://user-images.githubusercontent.com/11686358/96333042-e5528b00-1067-11eb-81d7-42b548c7478a.jpeg)
![C889E305-D3F7-41BB-9D72-1B9FA280AD8B](https://user-images.githubusercontent.com/11686358/96333045-e71c4e80-1067-11eb-8314-472ef61c4e6e.jpeg)
![569C40D9-66CA-43E4-8CFB-C050D7663BD9](https://user-images.githubusercontent.com/11686358/96333047-e7b4e500-1067-11eb-8f22-ecf512a5cbff.jpeg)

Let me know if anything else could be helpful.

**Comment by donavanbecker** [comment]
With the plugin being at 3.2 I don't believe this is coming from this plugin. It would have to be a lower version for it to think that.

**Comment by kieranmjones** [comment]
I too am seeing this with an MS210 outlet, an update was showing as available and to be fair there was so I updated the firmware in the Meross app, however it won’t now clear in the Home app. The plug-in is the latest version, as is Homebridge, and the firmware is up to date on Meross. Restarting Homebridge has no effect. I have four of these showing updates available in the Home app.
![1A81A0C9-55A8-458C-AFB7-421848AFC816](https://user-images.githubusercontent.com/19302628/97272055-4aa53980-1829-11eb-8c82-722f213f957c.png)
![0065FBCF-EB5C-45EC-825F-23C7894618FE](https://user-images.githubusercontent.com/19302628/97272064-4d079380-1829-11eb-8d7c-a1431ab59151.png)

**Comment by shehzaad10** [comment]
> I too am seeing this with an MS210 outlet, an update was showing as available and to be fair there was so I updated the firmware in the Meross app, however it won’t now clear in the Home app. The plug-in is the latest version, as is Homebridge, and the firmware is up to date on Meross. Restarting Homebridge has no effect. I have four of these showing updates available in the Home app.
> ![1A81A0C9-55A8-458C-AFB7-421848AFC816](https://user-images.githubusercontent.com/19302628/97272055-4aa53980-1829-11eb-8c82-722f213f957c.png)
> ![0065FBCF-EB5C-45EC-825F-23C7894618FE](https://user-images.githubusercontent.com/19302628/97272064-4d079380-1829-11eb-8d7c-a1431ab59151.png)

Hey did you manage to resolve this issue? As I am having the same issue, both my plugs have been updated via the Meross app onto the latest firmware but Home app still thinks there is an update available and directs me to the Meross app. I have tried to remove the plugs and add them again and even updated/restarted Homebridge but the issue is still there.

**Comment by kieranmjones** [comment]
I’ve not managed it no, I suspect if I was to remove the devices and clear the cache in Homebridge it would clear the issue so something is clearly getting stuck in there. This needs a fix of some kind in this plugin I guess.

**Comment by shehzaad10** [comment]
Yeah I have tried removing the plugs from Homebridge and configuring them again but no luck, even reset them within the Meross app and setup as brand new but the update bug is still there. @donavanbecker any advise?

**Comment by ziedby** [comment]
Same here I tried removing them from all place. Nothing changed.

**Comment by donavanbecker** [comment]
#121

**Comment by donavanbecker** [comment]
@ziedby @kieranmjones @shehzaad10 can you check out #121? And install latest beta?
